### PR TITLE
[@types/react-native] Fix: Animated Components are always any type

### LINKED ISSUE #40424: [@types/react-native] Animated components are defined as any
**Animated.*** are defined as "_any_".
So I can't use `Animated.FlatList` props because of this :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dc156f32b209433ddb998c44a3c730c584c881e7/types/react-native/index.d.ts#L8385-L8390

- [x] I tried using the `@types/react-native` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors:  @alloy, @huhuanming, @iRoachie, @Skn0tt, @timwangdev, @kamal, @alexdunne, @swissmanu, @a-tarasyuk, @mvdam, @Esemesek, @mrnickel, @souvik-ghosh, @nossbigg, @saranshkataria, @franzmoro, @tykus160, @jakebloom, @ceyhun, @mcmar

### PR DESCRIPTION
**Pull request by nnnnnoel**
Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Closes #40424

### CODE REVIEW

File: types/react-native/index.d.ts [hunk 1]
```diff
@@ -8467,21 +8467,25 @@ export namespace Animated {
...
 
+    export interface AnimatedComponent<T extends React.FC | typeof React.Component> extends React.FC<T['props']> {
+      getNode: () => T;
+    }
+
     /**
      * Make any React component Animatable.  Used to create `Animated.View`, etc.
      */
-    export function createAnimatedComponent(component: any): any;
+    export function createAnimatedComponent<T extends React.FC | typeof React.Component>(component: T): AnimatedComponent<T>;
```
Comment (alloy) [inline types/react-native/index.d.ts]: I wonder if this works too?

```suggestion
    export function createAnimatedComponent<T extends React.ComponentType>(component: T): AnimatedComponent<T>;
```

File: types/react-native/index.d.ts [hunk 2]
```diff
@@ -8467,21 +8467,25 @@ export namespace Animated {
...
-    export const Text: any;
-    export const ScrollView: any;
-    export const FlatList: any;
-    export const SectionList: any;
+    export const View: AnimatedComponent<View>;
+    export const Image: AnimatedComponent<Image>;
+    export const Text: AnimatedComponent<Text>;
+    export const ScrollView: AnimatedComponent<ScrollView>;
+    export const FlatList: AnimatedComponent<FlatList>;
+    export const SectionList: AnimatedComponent<SectionList>;
```
Comment (alloy) [inline types/react-native/index.d.ts]: Nice 👌

**Review by alloy — CHANGES_REQUESTED** [review]
This looks great, thanks 👌 

It would be great if you could add some test coverage that shows typical usage of these components doesn’t lead to any type errors.

**Comment by alloy** [comment]
The CI failures look legit too.

**Comment by zusinShinpei** [comment]
@alloy How can I use Recursive Type in DefinitelyTyped? I just try that but Travis CI needs Minimum TypeScript Version to lower than 3.7.

**Comment by alloy** [comment]
Hmm, it seems a bit of a stretch to bump the requirement that high. Some googling turned up [this](https://stackoverflow.com/a/47842314), could that help for your case?

**Comment by zusinShinpei** [comment]
@alloy I resolved that. can you approve this PR?

**Review by alloy — APPROVED** [review]

**Comment by alloy** [comment]
Aha, great! Thanks 🙏

**Comment by jenshandersson** [comment]
@zusinShinpei I'm getting this type error when setting `ref`. Am I doing something wrong or are the new types incorrect...?

Screenshot 2020-02-11 at 15 08 37

**Comment by zusinShinpei** [comment]
> @zusinShinpei I'm getting this type error when setting `ref`. Am I doing something wrong or are the new types incorrect...?
> 
> Screenshot 2020-02-11 at 15 08 37

#42446

**Comment by zanona** [comment]
I'm not sure if this is related but it looks that `Animated.*` props are not inferring the `data,sections` types as opposed to their original counterpart, for example: `FlatList.renderItem` and `Animated.FlatList.renderItem` 

```ts
<Animated.FlatList data={[1,2]} renderItem={a => <Text>{a}</Text>} />
```

    Parameter 'a' implicitly has an 'any' type.

While `a` is inferred from `data` on `FlatList`, as below: 

```ts
<FlatList data={[1,2]} renderItem={a => <Text>{a}</Text>} />
```

The same is happening for `keyExtractor`  and `renderSectionHeader` on `SectionList`

**Comment by alloy** [comment]
@zanona Would you be able to create a PR with ideally the solution but if too complex otherwise at least the test cases that demonstrate the problem?
