### PR TITLE
[jest] fix type inference for Mocked & mockResolvedValue/mockRejectedValue

### LINKED ISSUE #32890: jest: Regression: mock{Resolved|Rejected}... no longer has the correct return type
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @antoinebrault 

Assume a function:

```
function someDeferredResult(): Promise<SomeResultType> {...}
```

Expected:
The intention of mock{Resolved|Rejected}... is to pass in a value of type `SomeResultType` - AND NOT `Promise<SomeResultType>` - and generate a promise from it, see https://jestjs.io/docs/en/mock-function-api#mockfnmockresolvedvaluevalue.

Actual:
The 24.x typing broke this interface. It now assumes that mock{Resolved|Rejected}... gets a promise as an argument for a function that returns a promise.

This also breaks the mocking of async functions.

Background:

A mocked version of the above `someDeferredResult` should of course have the same signature as the original function. Let's assume that `someMockedDeferredResult` is just such a mock implementation.

Now const myMockFn = jest.fn(someMockDeferredResult) will have an inferred type of `Mock<Promise<SomeResultType>, []>`.

This means that myMockFn.mock{Resolved|Rejected}... will have the described undesired signature.

One possible fix for this would be to use conditional types so that mock{Resolved|Rejected} are only defined when the return type T extends `Promise<V>`.

Example:
``` 
mockResolvedValue<V>(value: T extends PromiseLike<V> ? V | PromiseLike<V> : never): Mock<T, Y>;
```

If you optionally want to support a return value of `Promise<T>` (why would you?) then you could also say:
``` 
mockResolvedValue<V>(value: T extends PromiseLike<V> ? V | PromiseLike<V> : T | PromiseLike<T>): Mock<T, Y>;
```
But I'd rather stick to what IMO the intended use case was for this method. I find the second option confusing and misleading.

### PR DESCRIPTION
**Pull request by antoinebrault**
Follow-up of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32579#issuecomment-460730562 , fixes #32890

Fixed Mocked interface & mockResolvedValue/mockRejectedValue

### Breaking Change

With types inferred, mockResolvedValue(), mockRejectedValue() will not compile if they are used on a function not returning a Promise.
e.g.
```typescript
class Test {
    method(x: string): string {
        return x;
    }
}
const test: Mocked<Test> = new Test() as any;

// this doesn't compile, because mockImplementation expects () => string
test.method.mockImplementation(() => Promise.resolve(''));

// this shouldn't compile either because mockResolvedValue() is sugar for mockImplementation(() => Promise.resolve());
test.method.mockResolvedValue('');
```

----

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: **private project**
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by antoinebrault** [comment]
@Chris-V updated code to be consistent with mockImplementation() & added tests

**Comment by Chris-V** [comment]
Thanks you! We had several helpers types in our code base to improve type-safety with jest. This will help us get rid of most of them!

**Comment by jerico-dev** [comment]
I provided an alternative proposal to solve this issue just for consideration, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32898 - Please feel free to close this PR if you prefer your own solution. :-)

File: types/jest/index.d.ts [hunk 1]
```diff
@@ -804,7 +804,7 @@ declare namespace jest {
      *  myApi.myApiMethod.mockImplementation(() => "test");
      */
     type Mocked<T> = {
-        [P in keyof T]: T[P] & MockInstance<T[P], ArgsType<T[P]>>;
+        [P in keyof T]: T[P] extends (...args: any[]) => any ? MockInstance<ReturnType<T[P]>, ArgsType<T[P]>>: T[P];
```
Comment (jerico-dev) [inline types/jest/index.d.ts]: Why don't you return to `MockInstance<F>` and derive ReturnType and ArgsType where needed? This is a breaking change anyway - so this shouldn't be a problem. Same is true for `Mock<F>` and `jest.fn<F>`. This would make the API less error prone/more obvious as I proposed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32864/files#r254967801.

File: types/jest/jest-tests.ts [hunk 2]
```diff
@@ -412,6 +412,61 @@ const spy6 = jest.spyOn(spiedTarget2, "value", "set");
...
+// $ExpectError
+mocked.test4.mockResolvedValueOnce({ a: 1 });
+// $ExpectError
+mocked.test4.mockResolvedValue(Promise.resolve({ a: 1 }));
+// $ExpectError
+mocked.test4.mockResolvedValueOnce(Promise.resolve({ a: 1 }));
+// $ExpectError
+mocked.test4.mockRejectedValue(new Error());
+// $ExpectError
+mocked.test4.mockRejectedValueOnce(new Error());
```
Comment (jerico-dev) [inline types/jest/jest-tests.ts]: Please add a reference to https://github.com/Microsoft/TypeScript/issues/29825 as your solution will be bitten by this problem as well. And this is really non-obvious to less seasoned TypeScript users.

You may also re-use some of my proposed tests to make the literal type vs. widened type problem more obvious. I also propose you include the link to the blog article that I had so that people understand what these additional use cases are about.

Comment (jerico-dev) [reply types/jest/jest-tests.ts]: See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32898/files#diff-830a7c9e24903b49e811209b6cd30c58R336

**Review by ghost — CHANGES_REQUESTED** [review]
Proposal to add additional tests + (optional) proposal to introduce correct (i.e. more strongly typed) signature for jest.fn, Mock, etc. Feel free to go along w/o the proposed changes if you think I'm off track. :-)

File: types/jest/jest-tests.ts (hunk 2 above)
Comment (antoinebrault) [reply types/jest/jest-tests.ts]: Shouldn't be a problem since im using types like: 

https://bit.ly/2MWoisL

I'll look at it tonight

Comment (jerico-dev) [reply types/jest/jest-tests.ts]: Yes - agreed, maybe you still want to include some of the test cases. See what you can use and consider this review comment to be obsolete. Just updated your test case a little to make it compile: https://bit.ly/2MWoisL

File: types/jest/index.d.ts (hunk 1 above)
Comment (antoinebrault) [reply types/jest/index.d.ts]: this will be discussed in #32901

File: types/jest/index.d.ts [hunk 3]
```diff
@@ -37,6 +37,8 @@ declare var xtest: jest.It;
 declare const expect: jest.Expect;
 
 type ArgsType<T> = T extends (...args: infer A) => any ? A : never;
+type RejectedValue<T> = T extends PromiseLike<any> ? any : never;
```
Comment (jwbay) [inline types/jest/index.d.ts]: Yikes, these are global. I didn't catch that on ArgsType. We should be more careful with naming here. Can we switch to naming like JestArgsType and JestRejectedValue, or put them in the jest namespace? Consumers may have their own global type helpers like this with slightly different semantics.

**Review by jwbay — CHANGES_REQUESTED** [review]

File: types/jest/index.d.ts (hunk 3 above)
Comment (antoinebrault) [reply types/jest/index.d.ts]: oh yeah. didn't know that was global. I'll update that

Comment (antoinebrault) [reply types/jest/index.d.ts]: done.

**Review by ghost — APPROVED** [review]

**Review by jwbay — APPROVED** [review]
