### PR TITLE
[dockerode] Use classes instead of interfaces where possible + fix #19437

### LINKED ISSUE #19437: Error when attaching an container - Property 'write' does not exist on type 'ReadableStream'
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d131a79ae894f23d26b8fac5859f040853ae2817/types/dockerode/index.d.ts#L104

**I'm receiving error: TS2339: Property 'write' does not exist on type 'ReadableStream'.**

The function .write() works but on method we have ReadableStream as return, then its showing error when compiling but its compiling and work. I am working in an electron app and when i try to build release package, i have the error and dont generate build.

Anyone can help me? Im thinking i have to convert ReadableStream to WritableStream, tried with TransformStream using pipes but not have success.

When i change signature of method on node_modules for make tests, it compile without errors.

Thanks for help!!!

### PR DESCRIPTION
**Pull request by P4sca1**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

`Container`, `Volume`, `Service` and more where defined as `interface`s, but they are created and used as `class`es in the dockerode source code. (See https://github.com/apocas/dockerode/blob/master/lib/docker.js#L314-L316)
Defining them as `class`es makes things like `class MyContainer extends Dockerode.Container` possible.

This PR also marks optional `id` / `name` field as non-optional because they are always present.

Also, the return type of the `container.attach()` method is changed to `NodeJS.ReadWriteStream`, which fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19437.
Here is an example where the returned `stream` is used as a `WriteStream`: https://github.com/apocas/dockerode/blob/543e49f53c48925c27d75b174a345dc133dff0b4/test/container.js#L238-L264

### CODE REVIEW

File: types/dockerode/index.d.ts [hunk 1]
```diff
@@ -894,8 +918,37 @@ declare namespace Dockerode {
...
+
+  interface DockerVersion {
+    ApiVersion: string;
+    Arch: string;
+    BuildTime: Date;
+    Components: Array<{
+      Details: {
+        ApiVersion: string;
+        Arch: string;
+        BuilTime: Date;
```
Comment (CameronDiver) [inline types/dockerode/index.d.ts]: Typo here
```suggestion
        BuildTime: Date;
```

**Review by CameronDiver — CHANGES_REQUESTED** [review]
Generally looks good, typo in one of the interfaces though

File: types/dockerode/index.d.ts (hunk 1 above)
Comment (P4sca1) [reply types/dockerode/index.d.ts]: Nice catch, however I just noticed that something got screwed up during the pull request. Note that the DockerVersion interface exists 2 times, because it was added one time with the pull request.
This was never intended.

**Review by CameronDiver — APPROVED** [review]

File: types/dockerode/index.d.ts (hunk 1 above)
Comment (CameronDiver) [reply types/dockerode/index.d.ts]: Ah I didn't notice the second instance of this, I thought it didn't exist and you added it in as part of these changes.

Comment (P4sca1) [reply types/dockerode/index.d.ts]: I removed the second instance. Also, just noticed, that the typo does currently exist in the master branch: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dockerode/index.d.ts#L909

**Comment by P4sca1** [comment]
I have made another commit, because I noticed that `container.stats` is missing type declarations.
Thought that it would be easier than making a new pull request.
Would be great to have another review before merging @CameronDiver.

**Review by CameronDiver — APPROVED** [review]
Looks good, it might be better to collapse the last three commits into a single one, other than that I'm happy though.

**Comment by P4sca1** [comment]
I'm kinda new to pull requests, is this something that can be done now after the commits already happened?

**Comment by CameronDiver** [comment]
You would need to add DefinitelyTyped as a remote to your fork, and then do an interactive rebase on their branch, switching the last two commits from `pick` to `f`, e.g
```bash
git remote add dt git@github.com:DefinitelyTyped/DefinitelyTyped
git fetch
git rebase -i dt/master
```
which will give something similar to
```
pick 168d5ac commit 1 message
pick e5ac8cd commit 2 message
pick 83c64e6 commit 3 message
```

so to squash the last two, you'd switch this to
```
pick 168d5ac commit 1 message
f e5ac8cd commit 2 message
f 83c64e6 commit 3 message
```

Either way I don't know how stringent the DT team are on having a super clean commit history, but at least you know how to do it for the future :)

**Comment by P4sca1** [comment]
I will try to avoid unnecessary commits in the future, thanks for the advice!
If the DT team accepts these 2 commits, I will not try to rebase the pull request, as I fear to break something 😅

**Comment by jessetrinity** [comment]
Cherry picking is for iconoclasts.
