### PR TITLE
[styled-components] Add support of `defaultProps`

### LINKED ISSUE #29540: [@types/styled-component] styled() does not recognize React defaultProps in Typescript 3
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek & @Igmat 

If you do not mention the authors the issue will be ignored.

Hello! This is a follow up from this issue in the styled-components repo (was directed here) https://github.com/styled-components/styled-components/issues/1914  

Initial post by @nathanbirrell quoted below
> Since Typescript [introduced support for defaultProps](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx) recently, it would be nice to have styled-components recognise their presence.
> 
> ## Reproduction
> Create a component with one required and one optional prop, set a default prop for the optional.
> 
> ```js
> interface IProps {
>   requiredProp: boolean
>   optionalProp: string // Shouldn't need to be optional here
> }
> 
> class MyComponent extends React.PureComponent<IProps> {
>   static defaultProps = {
>     optionalProp: 'fallback'
>   }
> 
>   render() {
>     const { requiredProp, optionalProp } = this.props
>     return (
>       <span>
>         {requiredProp.toString()}
>         {optionalProp.toString()}
>       </span>
>     )
>   }
> }
> ```
> 
> Then use that component, once as a normal react component and once as a styled-component:
> 
> ```js
> const MyComponentStyled = styled(MyComponent)``
> 
> // No type error (expected) because optionalProp is defined in defaultProps
> <MyComponent requiredProp />
> 
> // Type error (unexpected), styled() doesn't recognise optionalProp is defined in defaultProps
> <MyComponentStyled requiredProp />
> ```
> 
> ## Expected Behavior
> No type error when using `MyComponentStyled` without `optionalProp`.
> 
> ## Actual Behavior
> Type error, because styled() doesn't seem to recognise `optionalProp` is defined in `defaultProps`
> 
> `Property 'optionalProp' is missing in type '{ requiredProp: true; }'.`
> 
> ## Environment
> ```
> ## System:
>  - OS: Linux 4.15 Fedora 27 (Workstation Edition) 27 (Workstation Edition)
>  - CPU: x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
>  - Memory: 2.88 GB / 15.34 GB
>  - Container: Yes
>  - Shell: 4.4.19 - /bin/bash
> ## Binaries:
>  - Node: 8.9.4 - /usr/bin/node
>  - npm: 5.6.0 - /usr/bin/npm
> ## npmPackages:
>  - babel-plugin-styled-components: ^1.5.0 => 1.5.1
>  - styled-components: ^3.4.2 => 3.4.2
>  - typescript: ^3.0.1 => 3.0.1
> ```

EDIT: This other PR may apply https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28189, specifically lines https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28189/files#diff-ee7ace1841a23c70c0c2b663cfae1cb7R95

EDIT 2: I've created a failing test case in this branch. Unfortunately, the typing for this library a little out of my depth and I haven't been able to figure this out on my own. If someone could help I'd really appreciate it.

https://github.com/dan-kez/DefinitelyTyped/blob/styled_comp_failing_test_case_defaultDep/types/styled-components/styled-components-tests.tsx#L178-L201

### PR DESCRIPTION
**Pull request by Igorbek**
This PR fixes #29540 by adding `defaultProps` to the styled component type. The type of `defaultProps` simply is picked from the underlying decorated component.

Note, this will not cover more complicated cases where type or existence of default props may be changed via manipulations like `attrs`. We'll be looking in to this as such issues appear.

### CODE REVIEW

File: types/styled-components/test/index.tsx [hunk 1]
```diff
@@ -946,3 +946,41 @@ function validateArgumentsAndReturns() {
...
+        color: red
+    `;
+
+    // this test is failing in TS 2.9 but not in 3.0
+    // <MyComponent requiredProp />;
+
+    <StyledComponent requiredProp optionalProp="x" />;
+
+    // this test is failing in TS 3.0 but not in 3.1
+    // <StyledComponent requiredProp />;
```
Comment (Igorbek) [inline types/styled-components/test/index.tsx]: these tests are failing on 2.9 and 3.0.
Is there a way to ignore them only on specific versions of TS?

Comment (sheetalkamat) [reply types/styled-components/test/index.tsx]: You can create new definitions for ts 3.2+ version

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
Please fix the tests

File: types/styled-components/test/index.tsx (hunk 1 above)
Comment (Kovensky) [reply types/styled-components/test/index.tsx]: Yeah, this can only pass in TS >= 3.2. TS < 3.2 had a bug where it would _only_ apply `defaultProps` on class components, and styled components aren't class components.

File: types/styled-components/test/index.tsx [hunk 2]
```diff
@@ -270,7 +270,7 @@ const MyOtherComponentWithProps = () => (
 
 // Create a <LinkFromStringWithPropsAndGenerics> react component that renders an <a>
 // which takes extra props passed as a generic type argument
-const LinkFromStringWithPropsAndGenerics = styled("a")<LinkProps>`
+const LinkFromStringWithPropsAndGenerics = styled("a") <LinkProps>`
```
Comment (Kovensky) [inline types/styled-components/test/index.tsx]: Extra space

File: types/styled-components/index.d.ts [hunk 3]
```diff
@@ -141,6 +144,8 @@ export interface StyledComponentBase<
     //   props: StyledComponentPropsWithAs<AsC, T, O, A>
     // ): React.ReactElement<StyledComponentPropsWithAs<AsC, T, O, A>>
 
+    defaultProps: ReactDefaultProps<C>;
```
Comment (Kovensky) [inline types/styled-components/index.d.ts]: I'd add `readonly` here

File: types/styled-components/test/index.tsx (hunk 2 above)
Comment (Igorbek) [reply types/styled-components/test/index.tsx]: sorry, accidentally added

File: types/styled-components/test/index.tsx (hunk 1 above)
Comment (Igorbek) [reply types/styled-components/test/index.tsx]: I think @sheetalkamat meant to use [a new `typesVersions` TS 3.1 feature](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions), if I'm not mistaken.

I could do that but the issue has nothing to do with definition itself, and only appears in the tests. So if were a way to have tests for specific versions of TS that would help here.

I am not sure if we already have test/build infrastructure that allows to leverage the new feature.

My personal opinion, that since there's no real breaking changes in the definition, the minimal TS version should not be advanced. The tests, however, might have different expectations depending on TS version. And that's where we should look at.

File: types/styled-components/index.d.ts (hunk 3 above)
Comment (Igorbek) [reply types/styled-components/index.d.ts]: done

**Comment by Igorbek** [comment]
@sheetalkamat @Kovensky I'm going to merge this as is, assuming the more complicated questions regarding TS versions in the tests are left for addressing in the future.
If you have any concerns please say how they can be addressed in the short term.

**Comment by dan-kez** [comment]
@Igorbek - Thank you for putting this together! Reading your implementation makes a lot of sense.

File: types/styled-components/index.d.ts (hunk 3 above)
Comment (Kovensky) [reply types/styled-components/index.d.ts]: This is because of how the type copying works.

The `extends` clause will _only_ accept components that have already strictly defined `defaultProps`; if your component has a partial `defaultProps?: foo` it won't pick it up and will create a `defaultProps: never` key. You can't assign anything to it anyway.

If we accept partial `defaultProps?:`, then the `defaultProps` copying we are doing here is useless for `LibraryManagedAttributes` purposes, which is what this bug is intended to fix. Either we have to add a partial prop that will be ignored by `LibraryManagedAttributes`, or we have to lie and say that the `defaultProps` _are_ defined even if you don't initialize them, which is also wrong and the real issue I wanted to avoid by making it `readonly`.

This is because TypeScript doesn't support expando properties in TypeScript, only in JavaScript. There's no way in real TypeScript to have a property assignment or function call modify the type of its `this`, which is what we need to make `defaultProps` _actually_ work as you intended to.

Comment (dan-kez) [reply types/styled-components/index.d.ts]: This is slightly unfortunate as setting the defaultProps of a styled component is a fairly common pattern, at least in my experience. 

This is also more of a breaking change without a workaround (unless you count `// @ts-ignore`) for existing usage of styled-components.

Comment (gausie) [reply types/styled-components/index.d.ts]: I wasn't aware that TypeScript doesn't support expando properties, although when I think about it that is understandable.

The issue still stands that `defaultProps` is not `readonly` in reality and for me this is a breaking change. Do you think there's a way around this other than `ts-ignore`?

**Comment by kristian-puccio** [comment]
Agree the ability to set defaultProps is a requirement for me. I didn't find a problem with the previous implementation of defaultProps. Though maybe it's because I don't use extend, I tend to wrap the components in styled() if I want to 'extend' them.

Or am I misunderstanding the issue?

**Comment by dan-kez** [comment]
@kristian-puccio you can take a look a reproduction of the issue this PR is intended to solve here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29540

In short, even if you used `styled(MyComponent)`, if `MyComponent` had some defaultProps that were required the wrapped component would not recognize those defaults and require the user to supply them.

This resulted in either changing the type of `MyComponent` so that props with default values are optional, or requiring wrapped instances to supply all previously defaulted values.

That being said, the change to `readonly` is being discussed above in greater detail.  See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31903#discussion_r246035411

File: types/styled-components/index.d.ts (hunk 3 above)
Comment (Igorbek) [reply types/styled-components/index.d.ts]: Let me try to use this pattern and see if it helps. Any code snippet would be useful.

Comment (Kovensky) [reply types/styled-components/index.d.ts]: The workaround would be `.attrs`, but that has its own bugs (https://github.com/styled-components/styled-components/issues/2246) :(

Comment (artisologic) [reply types/styled-components/index.d.ts]: I second the feeling here, just updated the typings and i set defaultProps all the time, so it's an issue. I'll stick a `@ts-ignore` on it for now.

**Comment by Igorbek** [comment]
@gausie @kristian-puccio @dan-kez do you see any regression in your code base with `defaultProps` made read-only? I was unable to reproduce your use case with the change reverted. TS doesn't seem to support expando out of the box. Please give any repro code if it is still an issue.
