### PR TITLE
[ember] relax types around Ember.set & setProperties

### LINKED ISSUE #308: [@types/ember bug] - set() is not the same as this.set()
### Which package(s) does this problem pertain to?
  - [x] @types/ember

### What are instructions we can follow to reproduce the issue?
``` typescript
import EmberObject, { set } from '@ember/object';

export class Foo extends EmberObject {
  name!: string;

  changeName(name: string) {
    set(this, 'name', name);
  }
}
```
### Now about that bug. What did you expect to see?
It is expected to has no errors.

### What happened instead?
Typescript throws an error:

```
Argument of type 'string' is not assignable to parameter of type UnwrapComputedPropertySetter<this["name"]>'.
```

#### Note
1. use `name: any` instead of `name: string`, error will be gone
2. use `this.set` instead of `set()`, error will be gone

### PR DESCRIPTION
**Pull request by mike-north**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.emberjs.com/api/ember/3.4/functions/@ember%2Fobject/set
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---
- Fixes https://github.com/typed-ember/ember-cli-typescript/issues/308
- Workaround due to breaking change https://github.com/Microsoft/TypeScript/issues/26120
- Would much much cleaner w/ a fix for https://github.com/Microsoft/TypeScript/issues/27014

### CODE REVIEW

File: types/ember/test/object.ts [hunk 1]
```diff
@@ -49,3 +49,20 @@ class Foo extends Ember.Object.extend({
...
 }
+
+export class Foo2 extends Ember.Object {
+  name!: string;
+
+  changeName(name: string) {
+    let a: string = this.set('name', name);
+    let b: number = this.set('name', name); // $ExpectError
+    let x: string = Ember.set(this, 'name', name);
+    let y: number = Ember.set(this, 'name', name); // $ExpectError
```
Comment (mike-north) [inline types/ember/test/object.ts]: This would be much cleaner w/ `// $ExpectType string`, but for some reason (possibly related to https://github.com/Microsoft/TypeScript/issues/27014 ) the return type is `this['name']`, which is assignable to `string`
