### PR TITLE
Relax d3-array parameter definitions to ArrayLike

### LINKED ISSUE #18494: d3-array compatibility with TypedArrays
- [x] I tried using the `@types/d3-array` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @gustavderdrache, @borisyankov, @tomwanzek 

When using `d3-array` functions with a `TypedArray`, the typescript compiler doesn't recognize it as a valid parameter and gives me an error.

Example:
```typescript
const data = new Uint8Array([1, 2, 3]);
const [min, max] = extent(data);
```

That will yield an error: `Argument of type 'Uint8Array' is not assignable to parameter of type 'number[]'`

I can `any` my way out of it, but if I edit the type declaration to relax the parameter definition from `T[]` to `ArrayLike<T>`, everyone is happy.

```typescript
/**
 * Return the min and max simultaneously.
 */
export function extent<T extends Numeric>(array: ArrayLike<T>): [T, T] | [undefined, undefined];
```

This would apply to most functions in this library. If that change is acceptable, I'd be happy to submit a PR if you'd like. Thanks!

### PR DESCRIPTION
**Pull request by kirkedev**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Following discussion from #18494, this is a pull request to update the definitions to use `ArrayLike` rather than `Array` for most functions parameters. This will allow the type definitions for d3-array to work with any object implementing `ArrayLike`, which includes [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) and TypeScript's `ReadonlyArray`, without a cast. 

```typescript
interface ArrayLike<T> {
    readonly length: number;
    readonly [n: number]: T;
}
```

I've included test cases and also have manually run TypedArrays through d3-array functions to ensure they work, as well as a review of the source code. All looks good to me, but would appreciate review.

Resolves #18494

### CODE REVIEW

File: types/d3-array/d3-array-tests.ts [hunk 1]
```diff
@@ -380,11 +567,17 @@ numbersArray = d3Array.range(1, 10, 0.5);
 // shuffle() -------------------------------------------------------------------
 
 mergedArray = d3Array.shuffle(mergedArray);
-
 mergedArray = d3Array.shuffle(mergedArray, 1);
-
 mergedArray = d3Array.shuffle(mergedArray, 1, 3);
 
+mergedArray = d3Array.shuffle(readonlyMergedArray);
```
Comment (gumballhead) [inline types/d3-array/d3-array-tests.ts]: Just realized, we need to make this fail because shuffle is in place.

File: types/d3-array/index.d.ts [hunk 2]
```diff
@@ -289,14 +289,14 @@ export function tickStep(start: number, stop: number, count: number): number;
...
-export function transpose<T>(matrix: T[][]): T[][];
+export function transpose<T>(matrix: ArrayLike<ArrayLike<T>>): T[][];
 
 /**
  * Returns an array of arrays, where the ith array contains the ith element from each of the argument arrays.
  * The returned array is truncated in length to the shortest array in arrays. If arrays contains only a single array, the returned array
  * contains one-element arrays. With no arguments, the returned array is empty.
  */
-export function zip<T>(...arrays: T[][]): T[][];
+export function zip<T>(...arrays: Array<ArrayLike<T>>): T[][];
```
Comment (gumballhead) [inline types/d3-array/index.d.ts]: This is a special case due to the spread operator

File: types/d3-array/d3-array-tests.ts (hunk 1 above)
Comment (tomwanzek) [inline types/d3-array/d3-array-tests.ts]: I suppose, the cleanest way here is to overload the `shuffle` signature with one signature for the traditional `array` as it originally was, and then adding one overload per type of Typed Array, e. g.:

```ts
/**
 * Randomizes the order of the specified array using the Fisher–Yates shuffle.
 */
export function shuffle(array: Float32Array, lo?: number, hi?: number): Float32Array;
```

File: types/d3-array/index.d.ts (hunk 2 above)
Comment (tomwanzek) [inline types/d3-array/index.d.ts]: 👍

**Comment by tomwanzek** [comment]
@gumballhead Thanks for putting this together. I made a suggestion on the `shuffle` question your correctly identified.

File: types/d3-array/d3-array-tests.ts (hunk 1 above)
Comment (gustavderdrache) [inline types/d3-array/d3-array-tests.ts]: I'm not sure how I feel about maintaining that many overloads. The heart of the issue is that TypeScript doesn't consider the readonly-ness of a property when computing assignability of function arguments.

If `shuffle` is the only function that does in-place modification, maybe it's worth relaxing this to `ArrayLike<T>` as well and just noting in the documentation that it mutates its argument?

**Comment by gumballhead** [comment]
Wish there was a better way to mark shuffle's parameter as mutated and disallow ReadonlyArrays. You'd think there might be, but I couldn't figure it out.

File: types/d3-array/d3-array-tests.ts (hunk 1 above)
Comment (tomwanzek) [inline types/d3-array/d3-array-tests.ts]: You certainly have a point regarding the unusual number of overloads.

However, one issue is that one would expect that the return type matches the argument type passed in. I would be hesitant to actually pass in `T[]` and be returned `ArrayLike<T>`, similar with Typed Array inputs.

So I think, it might be better to simply bite the overload bullet here. An alternative with only one, yet cumbersome, overload would be something like:

```ts
export function shuffle<TA extends Float32Array | Float64Array | ...>(array: TA, lo?: number, hi?: number): TA;
```
The downside with this approach is, that we know changed the semantics of the generic from element type to array type for this overloaded signature.

**Comment by tomwanzek** [comment]
Ah, the virtues of distributed work 😄 

Below, is  the comment I had added into the original review thread, before the latest commit:

@gustavderdrache You certainly have a point regarding the unusual number of overloads.

However, one issue is that one would expect that the return type matches the argument type passed in. I would be hesitant to actually pass in `T[]` and be returned `ArrayLike<T>`, similar with Typed Array inputs.

So I think, it might be better to simply bite the overload bullet here. An alternative with only one, yet cumbersome, overload would be something like:

```ts
export function shuffle<TA extends Float32Array | Float64Array | ...>(array: TA, lo?: number, hi?: number): TA;
```
The downside with this approach is, that we know changed the semantics of the generic from "element type" to "array type" for this overloaded signature. All other signatures in the module, follow the "element type" convention.

Open for discussion...

**Review by gustavderdrache — APPROVED** [review]
Looks good to me. The number of overloads isn't quite as bad as I thought it would be, so I don't mind it.

**Comment by tomwanzek** [comment]
Alright. Then with thanks to all!!! 👍 
Ready to go.

**Comment by gumballhead** [comment]
Awesome. Thanks guys! 

I didn't bump the version in the header, as was on the checklist. Should I do that before the merge?

**Comment by tomwanzek** [comment]
The version number won't need a bump. It only gets bumped with minor/major version number changes in the underlying D3 module. So we are good.
