### PR TITLE
relay-runtime: Added identifierField to ReaderRefetchMetadata

### LINKED ISSUE #200: Typescript error in Relay generated files  "identifierField" not exist..
**# Issue**

Relay Generated files contains typescript error on _"identifierField"_.. App runs without problem in case ts is ignored...

This field does not exist under ReaderNode.d.ts

**Error:**

image

**TS Error Message**

(property) "identifierField": string
Type '{ connection: null; fragmentPathInResult: string[]; operation: any; identifierField: string; }' is not assignable to type 'ReaderRefetchMetadata'.
  Object literal may only specify known properties, and '"identifierField"' does not exist in type 'ReaderRefetchMetadata'.ts(2322)
`

**Is this field normaly part of relay ? because under ReaderNode.d i cannot find it...**

I saw _"identifierField"_ is searchable under **experimental** part...  can be missing typing...

```

Current one does not have it..
export interface ReaderRefetchMetadata {
    readonly connection: ReaderPaginationMetadata | null | undefined;
    readonly operation: string | ConcreteRequest;
    readonly fragmentPathInResult: ReadonlyArray<string>;
}
```
I have all in last versions  ( i think )  I also tried to go back with _react-relay_ from experimental to 10.0.1 but not results...

**# Versions** 
    "@types/relay-compiler": "^8.0.0",
    "@types/relay-runtime": "^10.0.1"
    "typescript": "^3.9.7"
    "babel-plugin-macros": "^2.8.0",
    "babel-plugin-relay": "^10.0.1",
     relay-compiler": "^10.0.1",
    "relay-compiler-language-typescript": "13.0.0",
    "relay-config": "^10.0.1",
    "relay-hooks": "^3.5.2",
    "react-relay": "0.0.0-experimental-8058ef82",

**Code include query** 

```
  const userquery = graphql`
    query UserDetailQuery($user_id: ID!) {
      userByID(user_id: $user_id) {
        ...UserDetail_user
      }
    }

  `;

  //@ts-ignore
  const UserDetailfragment = graphql`
    fragment UserDetail_user on User_DTO
      @refetchable(queryName: "UserDetailRefetchQuery") {
      id
      firstName
      lastName
      avatarImageName
      deactivated
      activTimestamp
      role {
        iD
        name
        code
      }
      # ...UserDetailGroups_user
      # ...UserDetailRole_user
      # ...UserDetailPremissions_user
    }
  `;

    const userdetaildata = useLazyLoadQuery<UserDetailQuery>(
      userquery ,
      {
        user_id: props.userid,
      },
      {
        fetchPolicy: "store-or-network",
      }
    );
  
    const [data, refetch] = useRefetchableFragment<
      UserDetailRefetchQuery,
      UserDetail_user$key
    >(UserDetailfragment, userdetaildata.userByID as UserDetail_user$key);

```

### PR DESCRIPTION
**Pull request by maraisr**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/relay/blob/7c67b4750592e469d499128108fe16afe2adaf51/packages/relay-runtime/util/ReaderNode.js#L70

resolves: https://github.com/relay-tools/relay-compiler-language-typescript/issues/200

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. MutationTypes
1. RangeOperations
1. MutationHandlers
1. VIEWER_ID

<details>
<summary>as well as these 9 other properties...</summary>
<p>VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against baff2544c4012a241aceb8e25d32ae208ac75f6a
</p>

File: types/relay-runtime/lib/util/ReaderNode.d.ts [hunk 1]
```diff
@@ -134,9 +134,10 @@ export interface ReaderRootArgument {
 }
 
 export interface ReaderRefetchMetadata {
-    readonly connection: ReaderPaginationMetadata | null | undefined;
+    readonly connection?: ReaderPaginationMetadata | null;
     readonly operation: string | ConcreteRequest;
     readonly fragmentPathInResult: ReadonlyArray<string>;
+    readonly identifierField?: string;
```
Comment (maraisr) [inline types/relay-runtime/lib/util/ReaderNode.d.ts:140]: @alloy @sibelius im not 100% clued up with Flow. 

This is the reference type:
https://github.com/facebook/relay/blob/7c67b4750592e469d499128108fe16afe2adaf51/packages/relay-runtime/util/ReaderNode.js#L66-L71

Does that mean both `connection` and `identifierField`, are optional, and nullable? Maybe I should also add `null` to `identifierField`??

**Review by sibelius — APPROVED** [review]

File: types/relay-runtime/lib/util/ReaderNode.d.ts (hunk 1 above)
Comment (damikun) [reply types/relay-runtime/lib/util/ReaderNode.d.ts]: @maraisr 

Super i tested my use-case with `"readonly identifierField?: string;"`  and it is working fine... 

Connection from my prospective can get undefined or null but custom identifierField field only undefined... I don`t know in what scenario it can become null...

But super thx for fixing ;)

**Review by damikun — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]

**Comment by maraisr** [comment]
Ready to merge

File: types/relay-runtime/lib/util/ReaderNode.d.ts (hunk 1 above)
Comment (alloy) [reply types/relay-runtime/lib/util/ReaderNode.d.ts]: Correct, Flow’s Maybe type also accepts `null`, but you already figured that out :)
