### PR TITLE
@types/yup: Add a ValidationError class to match the source code

### LINKED ISSUE #31950: [@types/yup] Error definition when catching ValidationError
I _think_ this is an issue but it may well be my TS knowledge letting me down.

When I catch a validation error the definition for the error is incorrect and does not give me access to the properties I expect.

```typescript
try {
  // yup.boolean().validate(null)
  await yup.boolean().validate(null)  // Updated https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31950#issuecomment-452388726
} catch (error) {
  if (error instanceof ValidationError) {
    // I get here however...
	error; // (local var) error: {}
    error.message // "Property 'message' does not exist on type '{}'"
  }
}
```

ValidationError is defined in two places, [L26](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L26) and [L295](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L295), as a function and an interface respectively.

- Authors: 
  - @dhardtke
  - @vtserman
  - @MoretonBayRC
  - @sseppola
  - @YashdalfTheGray
  - @vincentjames501
  - @robertbullen

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
Fixes #31950 

### Context
The existing typings for `ValidationError` were a function that returned an interface which is not sufficiently representing what is [happening in the code](https://github.com/jquense/yup/blob/master/src/ValidationError.js). As can be seen, the source code for the package contains a constructor function called `ValidationError` so I added a class that inherits from `Error` and added the properties and static methods accordingly. 

### DefinitelyTyped Checklist
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/yup/index.d.ts [hunk 1]
```diff
@@ -292,7 +295,12 @@ export interface SchemaDescription {
     fields: object;
 }
 
-export interface ValidationError {
+// ValidationError works a lot more like a class vs. a constructor
+// function that returns an interface. It's also got a couple of
+// static methods and it inherits for the generic Error class in
```
Comment (robertbullen) [inline types/yup/index.d.ts]: ...inherits _from_ the generic...

**Comment by rbuckton** [comment]
Thanks for the contribution!

**Comment by rockingskier** [comment]
Thanks @YashdalfTheGray
