### PR TITLE
lodash: fix partition, pick, and iteratee functions like trim

### LINKED ISSUE #18350: lodash: _.partition should return a tuple instead of an array
Currently [`_.partition`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/765d26a240fbec46db60791be84703f4ad30c7fe/types/lodash/index.d.ts#L8752-L8827) returns `T[][]`. The returned array always has two elements so returning a tuple (`[T[], T[]]`) would be more accurate.

### LINKED ISSUE #18774: Lodash - trim() as Iterator
- [x] I tried using the `@types/lodash` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel @chrootsu @stepancar 

```
_.map<string, string>(stringArray, _.trim).forEach((s: string) => {
  console.log(s);
});
```

Above code got error:

> error TS2345: Argument of type '(string?: string | undefined, chars?: string | undefined) => string' is not assignable to parameter of type 'string | undefined'.
>   Type '(string?: string | undefined, chars?: string | undefined) => string' is not assignable to type 'string'.

I check the typing of `_.map`. It expects the second parameter in type `ListIterator<T, TResult>`. But `_.trim` doesn't match `ListIterator`.

### PR DESCRIPTION
**Pull request by aj-r**
This PR is for a few small fixes:

- fixes #18350: `_.partition` should return a tuple instead of an array
- fixes #18774: `trim()` as Iterator
- `_.pick` should not allow `null`/`undefined` inputs to return a `Pick<>` type. We don't have an issue for this, but it's discussed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21291#issuecomment-342529138). I'm fixing this here because there seems to be no progress on that PR.

Quick guide to the changes in this PR:

- Any change that adds a `guard` parameter is for #18774.
- Changes to `_.partition` are for #18350.
- Changes to `_.pick` are for the last issue mentioned above.

Checklist:

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:   
  - partition: https://lodash.com/docs/4.17.4#partition
  - `trim()` as Iterator: https://lodash.com/docs/4.17.4#map
    > Many lodash methods are guarded to work as iteratees for methods like _.every, _.filter, _.map, _.mapValues, _.reject, and _.some.
    > The guarded methods are:
    > ary, chunk, curry, curryRight, drop, dropRight, every, fill, invert, parseInt, random, range, rangeRight, repeat, sampleSize, slice, some, sortBy, split, take, takeRight, template, trim, trimEnd, trimStart, and words
- [ ] Increase the version number in the header if appropriate. N/A
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by aj-r** [comment]
@RyanCavanaugh this PR has been open for 2 weeks now. Is there any plan to merge it soon?

File: types/lodash/index.d.ts [hunk 1]
```diff
@@ -11667,14 +11667,30 @@ declare namespace _ {
...
+         *
+         * @param min The minimum possible value.
+         * @param index Not used in this overload.
+         * @param guard Enables use as an iteratee for methods like _.map. You should not pass this parameter directly in your code.
+         * @return Returns the random number.
+         */
+        random(
+            min: number,
+            index: string | number,
+            guard: object
```
Comment (minestarks) [inline types/lodash/index.d.ts]: Reading the documentation and this comment, it looks like `floating` is optional. So I think these are the complete overloads you need. Also, this last overload doesn't look right -- where does it come from?

```ts
declare function random(floating?: boolean): number
declare function random(upper: number, floating?: boolean): number
declare function random(lower: number, upper: number, floating?: boolean): number
```

File: types/lodash/index.d.ts [hunk 2]
```diff
@@ -16807,6 +16914,21 @@ declare namespace _ {
...
+         * descending order.
+         *
+         * @param start The start of the range.
+         * @param index Not used in this overload.
+         * @param guard Enables use as an iteratee for methods like _.map. You should not pass this parameter directly in your code.
+         * @return Returns a new range array.
+         */
+        rangeRight(
+            end: number,
+            index: string | number,
```
Comment (minestarks) [inline types/lodash/index.d.ts]: I'm not understanding the `index - not used in this overload` comments. If it's not used, why have it? Could you provide an example of how it's used?

**Review by minestarks — CHANGES_REQUESTED** [review]

File: types/lodash/index.d.ts (hunk 1 above)
Comment (aj-r) [reply types/lodash/index.d.ts]: Yes it's optional, but if you pass `_.random` as the iteratee to `_.map`, then `_.map` will pass a string as the second parameter, and an object as the third parameter.

According to the [map documentation](https://lodash.com/docs/4.17.4#map), `random` was designed to be used as an iteratee for `map`, e.g.

```ts
_.map({ a: "foo", b: "bar" }, _.random);
```

The last overload is to support that use case.  It's the same reason I added similar overloads for functions like `trim`, `range`, and `rangeRight`.

File: types/lodash/index.d.ts (hunk 2 above)
Comment (aj-r) [reply types/lodash/index.d.ts]: If `guard` is present, lodash ignores the second parameter. Lodash does this so `rangeRight` can be used as an iteratee for `map` (see my other comment).

File: types/lodash/index.d.ts (hunk 1 above)
Comment (minestarks) [reply types/lodash/index.d.ts]: Sorry I was more talking about the overloads of `random` above. I think they were incorrect before. They're more correct now but you still turned `floating` into a required parameter on one, which I don't think is right?

File: types/lodash/index.d.ts (hunk 2 above)
Comment (minestarks) [reply types/lodash/index.d.ts]: Gotcha. This library always throws me for a loop.

**Review by minestarks — CHANGES_REQUESTED** [review]

File: types/lodash/index.d.ts (hunk 1 above)
Comment (aj-r) [reply types/lodash/index.d.ts]: Oh I see what you're saying. You're right that it's optional, but the first overload handles all cases where `floating` is unspecified:

```ts
         random(
             min?: number,
             max?: number,
             floating?: boolean
         ): number;
```

This overload allows me to do `_.random()`, `_.random(10)`, and `_.random(1, 10)`. So there's no point in making the `floating` parameter optional in the other overloads because it would be redundant.

Comment (aj-r) [reply types/lodash/index.d.ts]: Although I suppose doing it your way makes it clear that when you call `_.random(10)`, the `10` is the maximum not the minimum. I'll make the change.

**Review by minestarks — APPROVED** [review]
