### PR TITLE
[node] Add fetch types

### LINKED ISSUE #60924: node@18.x.x version not fetch global api ?
I use @types/node@18.0.0 version ,but use fetch fail,typescript to me "fetch is not defined"
Could I know , why "fetch is not defined" ?

### PR DESCRIPTION
**Pull request by andrewbranch**
Closes #60924

Undici has published their included types in a standalone a package `undici-types` specifically for use here. The types are added as a dependency and exposed as globals via the conditional merging tricks @thw0rted came up with for `Blob` et al. They disappear in favor of the DOM-defined globals in the presence of lib.dom.d.ts, though the types there and in undici-types are nearly identical—most users will not notice a difference.

Due to a [limitation of DefinitelyTyped infrastructure](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66824#issuecomment-1734391407), this cannot currently be added to the v18 typings 😕. @jakebailey, @sandersn and I are working on an infrastructure overhaul that fixes the issue, but I don’t think it’s worth holding this PR up for—our ETA is unknown still.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#fetch
  - #60924 
  - https://github.com/nodejs/undici/issues/2261
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

File: types/node/globals.d.ts [hunk 1]
```diff
@@ -320,4 +320,48 @@ declare namespace NodeJS {
     interface ReadOnlyDict<T> {
         readonly [key: string]: T | undefined;
     }
+
+    namespace undici {
+        type Request = typeof globalThis extends { onmessage: any } ? {} : import('undici-types').Request;
+        type Response = typeof globalThis extends { onmessage: any } ? {} : import('undici-types').Response;
+        type FormData = typeof globalThis extends { onmessage: any } ? {} : import('undici-types').FormData;
+        type Headers = typeof globalThis extends { onmessage: any } ? {} : import('undici-types').Headers;
+    }
```
Comment (andrewbranch) [inline types/node/globals.d.ts:329]: Where to expose these and what to name them is eligible for bikeshedding.

File: types/node/package.json [hunk 2]
```diff
@@ -3,5 +3,8 @@
     "types": "index",
     "typesVersions": {
         "<=4.8": { "*": ["ts4.8/*"] }
+    },
+    "dependencies": {
+        "undici-types": "~5.25.1"
```
Comment (andrewbranch) [inline types/node/package.json:8]: This is the first version of undici-types available, but it reflects a newer minor version than is actually included in Node.js so far. It sounded from https://github.com/nodejs/undici/issues/2261#issuecomment-1728599811 like we will be able to wait on a new Node.js version comes out containing undici 5.25 and bump the `@types/node` version accordingly if we want this dependency mapping to be perfectly accurate. cc @Ethan-Arrowood

File: types/node/test/globals.ts [hunk 3]
```diff
@@ -51,3 +51,27 @@ declare var RANDOM_GLOBAL_VARIABLE: true;
...
+        // lib.dom.d.ts.
+        response.json(); // $ExpectType Promise<any>
+        response.text(); // $ExpectType Promise<string>
+    });
+    const fd = new FormData();
+    fd.append("foo", "bar");
+    const headers = new Headers();
+    headers.append("Accept", "application/json");
+    fetch("https://example.com", { body: fd });
+}
```
Comment (andrewbranch) [inline types/node/test/globals.ts:77]: Open to additional test content suggestions

File: types/node/package.json (hunk 2 above)
Comment (Ethan-Arrowood) [reply types/node/package.json:8]: Yeah, I don't think there's much of an issue shipping this now and then getting synced up later. If there's an actual issue (some bug or whatever), then just tell me exactly which version you want me to publish and I'll manually go a publish the `undici-types` version.

**Comment by andrewbranch** [comment]
It seems like `types/node` is getting included in the `types/node/v18` test run. `undici-types` does `/// <reference types="node" />` but I think that should get intercepted by the `paths` defined in `types/node/v18/tsconfig.json`. Not sure what’s going on exactly.

**Comment by andrewbranch** [comment]
>  I think that should get intercepted by the `paths`

Type reference directives don’t go through `paths` 🥴 

I have a workaround, but it’s really ugly and requires a tsconfig.json change that’s currently illegal according to dtslint.

**Comment by andrewbranch** [comment]
The other thing we can do in the short term is not include fetch typings in `v18` until we work out another solution. The real fix is completely restructuring DT into a proper monorepo and not using tsconfig hacks to override module resolution, but that will take a while.

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## formidable ([<kbd>unpkg</kbd>](https://unpkg.com/browse/formidable@latest/))
was missing the following properties:
1. OctetstreamParser
1. QueryStringParser
1. octetstream
1. querystring
1. multipart

<details>
<summary>as well as these 1 other properties...</summary>
<p>json</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b6a3e0f4e2202c04d6e16af8ddb6e06782000d33
</p>

File: types/node/globals.d.ts [hunk 4]
```diff
@@ -320,4 +320,48 @@ declare namespace NodeJS {
...
+}
+
+declare function fetch(
+    input: import('undici-types').RequestInfo,
+    init?: import('undici-types').RequestInit,
```
Comment (jakebailey) [inline types/node/globals.d.ts:334]: Do these need to be conditional? If you have both this and DOM, do you just get two signatures and everything's okay?

**Review by carsonfarmer — COMMENTED** [review]
I was asked to review this, just doing a quick one. Not sure why levelup types are being touched here?

File: types/levelup/levelup-tests.ts [hunk 5]
```diff
@@ -63,7 +63,7 @@ db.isOpen();
 // $ExpectType boolean
 db.isClosed();
 
-// $ExpectType "closed" | "open" | "opening" | "new" | "closing"
+// $ExpectType "closed" | "open" | "opening" | "new" | "closing" || "open" | "closed" | "opening" | "new" | "closing"
```
Comment (carsonfarmer) [inline types/levelup/levelup-tests.ts:66]: typo? is this needed for tests to pass?

Comment (jakebailey) [reply types/levelup/levelup-tests.ts:66]: Union ordering is based on internal type IDs, and the type IDs are generated in an arbitrary order depending on the code that's loaded and the TS version. In this case, the undici types bring in more strings that node didn't have before, which means that the IDs shifted around and so these types have to be fixed.

File: types/node/globals.d.ts (hunk 4 above)
Comment (andrewbranch) [reply types/node/globals.d.ts:334]: The two overloads are almost unnoticeably different as it is, but that could be worth looking into. I’ll take a look.

**Review by nelsonni — APPROVED** [review]
From the perspective of `hidefile`, this is just a reordering of the expected types in the test. LGTM.

File: types/node/package.json (hunk 2 above)
Comment (Semigradsky) [reply types/node/package.json:8]: JFI, the latest undici version for Node.js versions:
- Node.js 18 - [`5.22.1`](https://github.com/nodejs/node/blob/v18.x/src/undici_version.h)
- Node.js 20 - [`5.25.2`](https://github.com/nodejs/node/blob/v20.x/src/undici_version.h)

File: types/levelup/levelup-tests.ts (hunk 5 above)
Comment (Semigradsky) [reply types/levelup/levelup-tests.ts:66]: Isn't it problem with `$ExpectType`? To me ordering doesn't matter in string union.

Comment (jakebailey) [reply types/levelup/levelup-tests.ts:66]: One could make the argument that it's a problem with ExpectType, or a problem with TypeScript, or both. It's just that (IIRC) nobody's figured out a way to improve this without negatively affecting performance. Until then, this really doesn't happen that often and is pretty easy to work around.

Comment (thw0rted) [reply types/levelup/levelup-tests.ts:66]: Feel free to vote on / follow https://github.com/microsoft/TypeScript/issues/17944.  It looks like https://github.com/microsoft/dtslint/issues/191 wasn't resolved before that repo was closed.  They're tracking at https://github.com/microsoft/DefinitelyTyped-tools now but unfortunately they don't seem to have cloned over the open issues from the old one.  Might not hurt to open a new issue and link back to the unresolved one?

Comment (jakebailey) [reply types/levelup/levelup-tests.ts:66]: To be clear, nobody _likes_ to have to do this; I don't intend for my comment to be some sort of official "as designed" status 😅

Thanks for linking that thread, which I entirely forgot to find and reread...

File: types/node/globals.d.ts (hunk 4 above)
Comment (jakebailey) [reply types/node/globals.d.ts:334]: Yeah, it just occurred to me that no matter which overload is selected, they'll both return the same `Response`, so it can't matter, right?

**Review by jakebailey — APPROVED** [review]

**Comment by Semigradsky** [comment]
I see that headers type in 'node:http' (`OutgoingHttpHeaders`) and 'undici' (`HeadersInit`) are incompatible. But I am not sure that should we do here smth or not.

```ts
// 'node:http'
    type OutgoingHttpHeader = number | string | string[];
    interface OutgoingHttpHeaders extends NodeJS.Dict<OutgoingHttpHeader> {
    ...
    
// 'undici'
export type HeadersInit = string[][] | Record<string, string | ReadonlyArray<string>> | Headers

export declare class Headers implements SpecIterable<[string, string]> {
...
```

For example, if library returns `OutgoingHttpHeaders` then user can't use them with `fetch`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66783#issuecomment-1741346687

**Comment by andrewbranch** [comment]
@Semigradsky that is a little unfortunate. Maybe undici would take a PR to loosen their `HeadersInit` type to be compatible. I guess @types/node should at least expose `HeadersInit` and anything else referenced by `RequestInit` and `RequestInfo` 🤔

File: types/node/globals.d.ts (hunk 4 above)
Comment (andrewbranch) [reply types/node/globals.d.ts]: I took your suggestion and added a test that shows the minor way in which it matters.

File: types/node/package.json (hunk 2 above)
Comment (SimonSchick) [reply types/node/package.json:8]: Kinda concerned about the impact of this on users of `@types/node` I've already seen a ton of duplicate installations of the package with different versions, using a restrictive version range for undici is likely going to make this worse.

Comment (andrewbranch) [reply types/node/package.json:8]: Can you elaborate? This isn’t undici, just undici-types.

Comment (mcollina) [reply types/node/package.json:8]: All those patch versions are identical, minus tiny bugfixes for other issues.

**Review by mcollina — APPROVED** [review]
lgtm

File: types/node/package.json (hunk 2 above)
Comment (SimonSchick) [reply types/node/package.json:8]: More curious if we should make this `>=5.22.1` to allow users squash/consolidate their dependencies more easily, a lot of libraries currently depend on `@types/node@*` to avoid this already, some don't and it causes multiple instances of @types/node to be installed which sometimes have been conflicting.

I'm not sure if I'm overstating the issue of if this is simply not a concern.

Comment (jakebailey) [reply types/node/package.json:8]: Yeah, mainly I assume this is a question of "what if there are multiple types packages in a project", where previously `@types/node` had no deps so could only "conflict" with itself in a compatible fashion, but adding a dep expands that risk (where restricting the version range increases that risk). I'm not sure that it will actually cause a problem, though.

**Review by nelsonni — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]
Seems like this is ready for a try?

File: types/node/package.json (hunk 2 above)
Comment (andrewbranch) [reply types/node/package.json:8]: The downside to loosening the range is indicating to a Node.js 20.3.X user (for example) that they have access to undici features that they actually don’t. undici just recently added support for HTTP2, so using a `>=` range could have incorrectly led users of a Node.js that hadn’t adopted that undici version to try to access those features, had this PR happened earlier.

On the other hand, I think you’re just automatically screwed if you have two `@types/node` versions in the same program, even without dependencies.

**Comment by andrewbranch** [comment]
Ready to merge

**Comment by andrewbranch** [comment]
Thanks everyone! I’ll be watching to see if anything blows up 😅

**Comment by jdeniau** [comment]
Hi @andrewbranch !

I do land here and I see that the types is quite recent. (2 hours only !)

I'm trying do test things with `globalThis.fetch` type, but I got this errors :

```ts
globalThis.fetch = async (
  input: URL | RequestInfo,
  options: RequestInit | undefined,
) => {};
```

does output:

```ts
Type '(input: URL | RequestInfo, options: RequestInit | undefined) => Promise<Response>' is not assignable to type '{ (input: URL | RequestInfo, init?: RequestInit | undefined): Promise<Response>; (input: RequestInfo, init?: RequestInit | undefined): Promise<...>; }'.
  Types of parameters 'input' and 'input' are incompatible.
    Type 'RequestInfo' is not assignable to type 'URL | RequestInfo'.
      Type 'Request' is not assignable to type 'URL | RequestInfo'.
        Property 'referrer' is missing in type 'import("/home/jdeniau/code/metch-fock/node_modules/undici-types/fetch").Request' but required in type 'Request'.ts(2322)
lib.dom.d.ts(18715, 14): 'referrer' is declared here.
```

By sniffing the .d.ts file, I found that you sometimes use `NodeJS.fetch.XXX`, so I tried this:

```ts
globalThis.fetch = async (
  input: URL | NodeJS.fetch.RequestInfo,
  options: NodeJS.fetch.RequestInit | undefined,
) => {};
```

But another issue there:

```
Type '(input: URL | NodeJS.fetch.RequestInfo, options: NodeJS.fetch.RequestInit | undefined) => Promise<Response>' is not assignable to type '{ (input: URL | RequestInfo, init?: RequestInit | undefined): Promise<Response>; (input: RequestInfo, init?: RequestInit | undefined): Promise<...>; }'.
  Types of parameters 'input' and 'input' are incompatible.
    Type 'URL | RequestInfo' is not assignable to type 'URL | import("/home/jdeniau/code/metch-fock/node_modules/undici-types/fetch").RequestInfo'.
      Type 'Request' is not assignable to type 'URL | RequestInfo'.
        Property 'duplex' is missing in type 'Request' but required in type 'import("/home/jdeniau/code/metch-fock/node_modules/undici-types/fetch").Request'.ts(2322)
fetch.d.ts(154, 12): 'duplex' is declared here.
```

If I roll back from ` "@types/node": "20.8.4"` to ` "@types/node": "20.8.3"`, then the error disappear.

**Comment by andrewbranch** [comment]
How about

```ts
globalThis.fetch = async (input, options) => {
    
}
```

The types will be inferred from context.

**Comment by jdeniau** [comment]
Indeed, it is inferred, but having the types written makes it really easier to navigate into the types.

Furthermore, I do call other methods, for example to extract the url of the `input`, and I need to type that. If I want to infer, I will need to do weird TS tricks. Probably something like:

```
function getInputUrl(input: Parameters<typeof globalThis.fetch>[0]) {
```

Pushing this a little forward, I found that `input` is not an instance of URL:

```ts
function getInputUrl(
  input: Parameters<typeof globalThis.fetch>[0],
): string {
  if (typeof input === 'string') {
    return input;
  }

  if (input instanceof URL) {
    return input.toString();
  }

  return input.url;
}
```

The last `return` line does throw this error:
```
Property 'url' does not exist on type 'URL | Request'.
  Property 'url' does not exist on type 'URL'.ts(2339)
```

Is it a conflict between typescript's `libdom.d.ts` and `@types/node` ?

**Comment by andrewbranch** [comment]
Yes. Users should avoid having @types/node and lib.dom.d.ts at the same time, but this PR jumped through many hoops to ensure that usage of `fetch` will still work. As someone mocking `fetch`, I unfortunately expect you’ll have to jump through some hoops as well.

**Comment by jdeniau** [comment]
OK, no problem, I will try to do this.

Thanks for your time 👍

**Comment by xconverge** [comment]
Sorry for this notifying a lot of people, I figured the MR would notify less people than the issue, but I can also open a new issue to ask more direct questions and provide more snippets.

@andrewbranch if I want to assign the dispatcher by creating an Agent or MockAgent or call setGlobalDispatcher, should I be importing using undici-types directly? 

I know that this issue is primarily focused on fetch itself, but there are other aspects of undici which I use for testing and I was wondering if I just need to keep undici-types as an explicit devDependency, or if I should rely on the dependency that types/node is pulling it in, or some other solution?

Prior to undici-types being created, I have been including undici as a dependency.

Examples:
```
import { Agent } from "undici-types"

const httpsAgentInsecure = new Agent({
  connect: { rejectUnauthorized: false },
})

fetch(url, {
  method: "GET",
  headers: {},
  dispatcher: httpsAgentInsecure,
}),
```

```
import { MockAgent, setGlobalDispatcher } from "undici"

// Mock the fetch requests
const mockAgent = new MockAgent()
setGlobalDispatcher(mockAgent)
mockAgent.disableNetConnect()
```
```

**Comment by andrewbranch** [comment]
You can’t import values from `undici-types` and actually use them in value-space:

```ts
import { Agent } from "undici-types";

new Agent(); // this will crash in Node.js
```


So you would want to continue to depend on undici, yes.

**Comment by huw** [comment]
Hey @andrewbranch! As mentioned in cloudflare/workerd#1298, it’s not your fault but this breaks anything which overrides the fetch global with an incompatible type if they’re doing so through `tsconfig.json#types`. Cloudflare Workers is a great but not exclusive example of this, since they recommend users add `"types": ["@cloudflare/workers-types"]` to their `tsconfig.json`, but if a single one of their dependencies imports `@types/node`, which is very common (ex. `openai-node`, `stripe-node`), they’ll start to get type incompatibilities. Cloudflare can’t fix this because they rely on non-standard extensions to `fetch`, and it seems reasonable but a huge lift to ask every ecosystem package to remove their `@types/node` references, which in many cases will involve splitting their entrypoints.

I wanted to raise the idea here (discussed further in [this comment](https://github.com/cloudflare/workerd/issues/1298#issuecomment-1756830290)) of using TypeScript 5’s `customConditions` to neutralise `@types/node` under certain conditions. The idea would be that a user could add `"customConditions": ["workerd"]` to their `compilerOptions` to hint to TypeScript that they’re overriding the global types in some other way. Then `@types/node` would upgrade to use `package.json#exports` like so:

```json
"exports": {
    "workerd": {
        "node": {
            "types": "./index.workerd.d.ts",
        },
        "types": "./noop.d.ts"
    },
    "types": "./index.d.ts"
}
```

By default, this neutralises `@types/node` but would also allow runtimes to operate in Node compatibility mode (which Deno, Bun, and Cloudflare have), where they’d have custom entrypoints that omit anything that would be overridden by their global types. We could even omit types that aren’t available in their respective Node compat modes, but at the risk of introducing a few type incompatibilities that could be corrected with patches and PRs.

(We would also add keys for anything else in WinterCG’s [Runtime Keys list](https://runtime-keys.proposal.wintercg.org/), but AFAIK only `workerd` has `fetch` incompatibilities right now; other runtimes have their own solutions to this or just remain compatible in ways that Cloudflare can’t).

I think this solution would be reasonable because it would remain backwards-compatible by default and require users to add `customConditions` in the rare case that they’re affected. I also think it’s a reasonable and idiomatic use of `customConditions` (although, arguably, the _most_ idiomatic solution is to upgrade the entire package ecosystem). The only problems this would really raise are if a user is running their runtime in Node compatibility mode, and their runtime lacks types for a Node package that one of their dependencies need, but solving this is a _much_ lower lift than adding `exports` conditions to every package.

As a bonus, this could also solve a _lot_ of the concerns and hangups in microsoft/TypeScript#18588 w/r/t browser packages accidentally polluting their namespaces with `@types/node`.

I’m not asking to solve this immediately, but would the `@types/node` maintainers be open to something like this?

(BTW I don’t work for Cloudflare; just a concerned user :P)

**Comment by andrewbranch** [comment]
There’s kind of a fundamental problem with any approach that removes types from a program. While it’s true that sometimes users wind up with `@types/node` in their compilation for absolutely no good reason and it can be fully removed without consequence, more often you have something like this:

```ts
// user code running on Cloudflare
import { querySmartAI } from "openai-node";
const res = querySmartAI("what is the melting point of mushrooms (my grandma used to tell me)");

// node_modules/openai-node/index.d.ts
/// <reference types="node" />
export function querySmartAI(query: string): NodeJS.ReadableStream;
```

If you override `@types/node` to resolve to a no-op, that will cause errors in the user’s program. Even if they can be silenced with `skipLibCheck`, their `res` will be infected with type `any` from the error. So which types should be omitted and which included in a given combination of import conditions? I think any viable solution needs to put the responsibility of answering that question on the target runtime, not the types package that’s being accidentally included.

**Comment by huw** [comment]
Thanks for explaining a bit more of the motivation there! I also liked [your comment in the original issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924#issuecomment-1739948070), which really gave me pause to think.

Perhaps I should just back up and ask what you think the idiomatic solution looks like? (You have much much more insight into what TypeScript think about this than I do 😅)

- Can you explain what a runtime-led solution would look like? I am having a hard time understanding what role they can play here beyond maintaining their own patched fork of `@types/node`—is that what you mean? (And in that case, is it a stretch for them to just maintain a conditional export here?) 
  - Given your point above, would they deliberately type unavailable APIs as `never` or `unknown` instead of omitting them?
- …or does it look more like playing whack-a-mole with packages as they upgrade to v20.8.4? (Does this look like each package adding export conditions for types? Is the size of that effort across the entire ecosystem larger than the above option?)
- Something else?

**Comment by andrewbranch** [comment]
I honestly don’t know what the best way forward would be, but I think patching @types/node and having users replace it via package manager functionality sounds the most promising.

> Given your point above, would they deliberately type unavailable APIs as never or unknown instead of omitting them?

No, I think it would be correct to omit them. My point was only that (1) omitting _all_ of @types/node is probably not correct, but (2) I don’t want @types/node to be responsible for knowing how much of Cloudflare’s worker API overlaps with Node.js.

**Comment by kettanaito** [comment]
Can we please get an intended usage example for this? Simply adding `"node"` to `"types"` in tsconfig.json _does not_ expose global Fetch API types to the code. I've tried `"types": ["undici-types"]` in all shapes and forms to no avail either.

**Comment by jakebailey** [comment]
There shouldn't be anything special; it "just works" for me in a project where I just did:

```console
$ npm init --yes
$ npm install -D typescript @types/node
$ npx tsc --init
$ echo "fetch()" > index.ts
```

image

**Comment by thw0rted** [comment]
This PR exposed `RequestInit` globally but missed [other "Init" typedef/dictionary types](https://fetch.spec.whatwg.org/) that lib-dom exposes globally, which will cause compatibility errors like https://github.com/mswjs/msw/issues/1836 for isomorphic libraries.  I believe we're still missing:

* ResponseInit
* BodyInit
* HeadersInit
* XMLHttpRequestBodyInit
* RequestInfo

Some of these are very simple structurally but if they don't exist in the global namespace, any library that refers to them will break, sometimes in confusing ways.

**Comment by JasonKleban** [comment]
1000 * ❤️

I'm still having to directly depend on udici-types to be able to use these runtime values, which feels dirty.  Is it necessary?

```ts
import { Dispatcher, getGlobalDispatcher, setGlobalDispatcher, ProxyAgent } from "undici-types";
```

**Comment by thw0rted** [comment]
The `import` you wrote should fail at runtime because `undici-types` only exports the type side of things.  I haven't tried to use Dispatcher / ProxyAgent but they don't appear to actually be exposed at runtime in Node (yet?): https://github.com/nodejs/node/issues/43187

**Comment by AlekEagle** [comment]
This fails when building under an ESNext module. Stating it cannot find undici-types without specifying NodeNext for module resolution.

**Comment by GabrielDelepine** [comment]
> This fails when building under an ESNext module. Requiring to use NodeNext.

I am using ESNext module and it works well. Make sure you are using the latest version of `@types/node`

```
"lib": ["es2022"],
"module": "ESNext",
"moduleResolution": "Bundler",
```
