### PR TITLE
[redux-form] - Fix handleSubmit error

### LINKED ISSUE #22847: [@types/redux-form] Can't pass handleSubmit to onSubmit
- [x] I tried using the `@types/redux-form` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/redux-form) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CarsonF @aikoven @LKay @bancek @tehbi4 

# Situation
I have a ts error if i pass handleSubmit method to onSubmit

# Code 
```typescript
import * as React from "react";
import { InjectedFormProps } from "redux-form";

interface ITestFormData {
  foo: string;
}

type TestProps = {} & InjectedFormProps<ITestFormData>;

const test: React.StatelessComponent<TestProps> = ({ handleSubmit }: TestProps) => (
  <form onSubmit={handleSubmit}></form>
);
```
or
```typescript
class TestComponent extends React.Component<TestProps> {

  public render(): JSX.Element {
    const { handleSubmit } = this.props;

    return (
      <form onSubmit={handleSubmit}>
      </form>
    );
  }
}
```
# Error
`[ts]
Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>'.
  Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
    Types of property 'onSubmit' are incompatible.
      Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '((event: FormEvent<HTMLFormElement>) => void) | undefined'.
        Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '(event: FormEvent<HTMLFormElement>) => void'.`

`[ts]
Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>'.
  Type '{ onSubmit: SubmitHandler<ITestFormData, {}>; }' is not assignable to type 'FormHTMLAttributes<HTMLFormElement>'.
    Types of property 'onSubmit' are incompatible.
      Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '((event: FormEvent<HTMLFormElement>) => void) | undefined'.
        Type 'SubmitHandler<ITestFormData, {}>' is not assignable to type '(event: FormEvent<HTMLFormElement>) => void'.
          Types of parameters 'submit' and 'event' are incompatible.
            Type 'FormEvent<HTMLFormElement>' is not assignable to type 'FormSubmitHandler<ITestFormData, {}>'.
              Type 'FormEvent<HTMLFormElement>' provides no match for the signature '(values: Partial<ITestFormData>, dispatch: Dispatch<any>, props: {}): void | Promise<any> | FormErrors<ITestFormData, void>'.
`
# Versions
Packages | Versions
------------ | -------------
`typescript` | 2.6.2
`react` | 16.2.0
`redux-form` | 7.2.0
`@types/react` | 16.0.34
`@types/redux-form` | 7.0.12

### PR DESCRIPTION
**Pull request by tehbi4**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/erikras/redux-form/blob/84693b5a496fc36fe89ac0603b84084d028d5bb5/src/handleSubmit.js#L11>
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

fix #22847

### CODE REVIEW

File: types/redux-form/lib/reduxForm.d.ts [hunk 1]
```diff
@@ -18,15 +18,18 @@ import {
 } from "../index";
 
 export type FormSubmitHandler<FormData = {}, P = {}> =
-    (values: Partial<FormData>, dispatch: Dispatch<any>, props: P) => void | FormErrors<FormData> | Promise<any>;
+    (values: Partial<FormData>, dispatch?: Dispatch<any>, props?: P) => void | FormErrors<FormData> | Promise<any>;
```
Comment (19majkel94) [inline types/redux-form/lib/reduxForm.d.ts]: Why dispatch and props are optional?

Comment (tehbi4) [reply types/redux-form/lib/reduxForm.d.ts]: It's mistake 😳, thank you. I'v made them not optional in 7b6e78e

**Review by MichalLytek — APPROVED** [review]
