### PR TITLE
[next] Fixed query string types, add isServer to context

### LINKED ISSUE #26843: [@types/next] Wrong query types?
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @resir014

@resir014 May I ask why you reverted the query types in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25711/commits/512782a734254850dc31005b359cdf3f5239aa75 ? For the record, I think both versions are not quite correct … shouldn't it be like this?

```ts
query: { [key: string]: string | string[] | undefined }
```

AFAIK, the query can contain arrays but is never parsed into numbers/booleans. Also, any key can be undefined, so I think the type should need to account for that.

### PR DESCRIPTION
**Pull request by resir014**
Fixes #26562, fixes #26843.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #26562 #26843 
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/next/index.d.ts [hunk 1]
```diff
@@ -24,15 +29,7 @@ declare namespace next {
...
-        query: {
-            [key: string]:
-                | boolean
-                | boolean[]
-                | number
-                | number[]
-                | string
-                | string[];
-        };
+        query: QueryStringMapObject;
```
Comment (Dru89) [inline types/next/index.d.ts]: You could probably replace `QueryStringMapObject` with `Record<string, string | string[] | undefined>` instead of using an index type (since you don't have any other fields).

But nbd, and probably just preference. :)

**Review by dru89 — APPROVED** [review]

File: types/next/index.d.ts (hunk 1 above)
Comment (resir014) [reply types/next/index.d.ts]: @Dru89 Ah yes, good idea. Thanks!

**Review by dru89 — APPROVED** [review]
