### PR TITLE
[jest] fix jest.fn to match spec

### LINKED ISSUE #32863: jest.fn's implementation argument is no longer optional
If you know how to fix the issue, make a pull request instead.
- [x] I tried using the `@types/jest` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- Authors: @antoinebrault 

This was introduced by PR #31094 / Commit 3b921eff19a12be00fa9626fb1973e91b93398c9

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jestjs.io/docs/en/jest-object#jestfnimplementation => "optionally takes a mock implementation"
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

fixes #32863

### CODE REVIEW

File: types/jest/jest-tests.ts [hunk 1]
```diff
@@ -307,8 +307,8 @@ const mock7 = jest.fn((arg: number) => arg);
 const mock8: jest.Mock = jest.fn((arg: number) => arg);
 // $ExpectType Mock<Promise<boolean>, [number, string, {}, [], boolean]>
 const mock9 = jest.fn((a: number, _b: string, _c: {}, _iReallyDontCare: [], _makeItStop: boolean) => Promise.resolve(_makeItStop));
-// $ExpectType Mock<never, [never]>
-const mock10 = jest.fn((arg: never) => { throw new Error(arg); });
+// $ExpectType Mock<never, []>
+const mock10 = jest.fn(() => { throw new Error(); });
```
Comment (antoinebrault) [inline types/jest/jest-tests.ts]: could you add a test like: 
```typescript
interface TestFn {
  test(x: number): string
}
const mock12 = jest.fn<TestFn['test']>((x) => x + '');
```
It would prevent people from removing the optional implementation.

File: types/jest/index.d.ts [hunk 2]
```diff
@@ -121,7 +121,7 @@ declare namespace jest {
     /**
      * Creates a mock function. Optionally takes a mock implementation.
      */
-    function fn<T, Y extends any[]>(implementation: (...args: Y) => T): Mock<T, Y>;
+    function fn<F extends (...args: any[]) => any>(implementation?: F): Mock<ReturnType<F>, ArgsType<F>>;
```
Comment (antoinebrault) [inline types/jest/index.d.ts]: You can't change generics without a breaking change. It has to stay the same.

Before I introduced type inference in jest, it was:
```typescript
function fn<T>(implementation?: (...args: any[]) => any): Mock<T>;
```
I added a second generic for arguments
```typescript
function fn<T, Y extends any[]>(implementation: (...args: Y) => T): Mock<T, Y>;
```
The correct fix would be to set implementation as optional, without touching generics.
```typescript
function fn<T, Y extends any[]>(implementation?: (...args: Y) => T): Mock<T, Y>;
```
And add a test:
```
interface TestFn {
    test(x: number): string
}
// $ExpectType Mock<string, [number]>
const mock12 = jest.fn<ReturnType<TestFn['test']>, ArgsType<TestFn['test']>>();
```

**Review by antoinebrault — CHANGES_REQUESTED** [review]

File: types/jest/index.d.ts (hunk 2 above)
Comment (jerico-dev) [reply types/jest/index.d.ts]: To be honest, I much prefer the previous template, that's why I re-introduced it. In fact I believe that your upgrade has introduced unnecessary breaking changes (as compared to 23.x) that are actually regressions because they reduce typing in many cases and introduce potential for inconsistency. Example: I believe that something like jest.fn<number> or jest.fn<..., [never]> should NOT be valid. The same is true for other types like Mock which I didn't touch. But don't get me wrong: Introducing typed arguments was of course a good thing.

What was your rationale to do it like this? Do you agree in principle that my solution would have been easier to upgrade to for most 23.x users, introduces less redundancy and potential for error? Or am I just unaware of some subtlety or less obvious use case?

Maybe you can explain this a little for me and other who happen to stumble upon this?

If we agree that this solution is objectively better, though, then of course you're right that it is still formally another breaking change. :-( As the types packages are not semversioned there might be a way to change this anyways before most users try to upgrade and stumble upon this incompatibility? In practice this might be less of a breaking change for many as your code is only out since a few days.

Of course I'm just guessing and it's for you and the maintainers to decide...

**Comment by jerico-dev** [comment]
I pushed another version that introduces a test showcasing the Api-Mocking use case as proposed by @antoinebrault . Will change the template as soon as I fully understand the background (see my previous post).

File: types/jest/index.d.ts (hunk 2 above)
Comment (antoinebrault) [reply types/jest/index.d.ts]: > Example: I believe that something like `jest.fn<number>` or `jest.fn<..., [never]>` should NOT be valid.

Had a long discussion about default values in my first PR #31094 . There was a lot of pushback about removing defaults and introducing breaking change in existing generics. I would like to simplify the generics like you too. 

Passing the function as the generic should've been the way when they first did it, but it wasn't. I agree that we should change it in the future, I just don't think we should do it for a bug in 1 declaration. If we change it, it has to be consistent across the api (Mock, MockInstance, SpyInstance, etc.)

Comment (antoinebrault) [reply types/jest/index.d.ts]: > Example: I believe that something like `jest.fn<number>` or `jest.fn<..., [never]>` should NOT be valid.

Had a long discussion about default values in my first PR #31094 . There was a lot of pushback about removing defaults and introducing breaking change in existing generics. I would like to simplify the generics like you too. 

Passing the function as the generic should've been the way when they first did it, but it wasn't. I agree that we should change it in the future, I just don't think we should do it for a bug in 1 declaration. If we change it, it has to be consistent across the api (Mock, MockInstance, SpyInstance, etc.)

Comment (jerico-dev) [reply types/jest/index.d.ts]: Ok, I'll revert to the `<X, Y>` types and opened up an issue to track the `<X, Y>` -> `<F>` change, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32901. Stay tuned. :-)

**Comment by jerico-dev** [comment]
The last push addresses @antoinebrault 's review comments: Types have been reverted to `<X, Y>`. Tests reproduce the corrected issue.

**Review by antoinebrault — APPROVED** [review]

File: types/jest/jest-tests.ts [hunk 3]
```diff
@@ -307,10 +307,15 @@ const mock7 = jest.fn((arg: number) => arg);
...
 // $ExpectType Mock<unknown, [unknown]>
 const mock11 = jest.fn((arg: unknown) => arg);
+interface TestApi {
+    test(x: number): string;
+}
+// $ExpectType Mock<string, [number]>
+const mock12 = jest.fn<ReturnType<TestApi["test"]>, ArgsType<TestApi["test"]>>();
```
Comment (jwbay) [inline types/jest/jest-tests.ts]: Just a note: the ArgsType reference will break after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32816 is merged

Comment (jerico-dev) [reply types/jest/jest-tests.ts]: It doesn't seem to be a problem as the only change was that ArgsType was moved inside the jest namespace. I'm referencing it within the same namespace so it doesn't need the jest. prefix (tested).

Comment (antoinebrault) [reply types/jest/jest-tests.ts]: @jwbay you were right. This fails in master. I fixed it in #33117

File: types/jest/index.d.ts (hunk 2 above)
Comment (G-Rath) [reply types/jest/index.d.ts]: @jerico-dev would you be able to update your [Working sample implementation of the above mocking API](https://github.com/facebook/jest/issues/7832) to reflect this change, or otherwise update the link in the issue to point to your new PR, if that's required for it to work :)

Comment (jerico-dev) [reply types/jest/index.d.ts]: @G-Rath I'm sorry that my feature request still pointed to this issue. The actual change needed to make the feature request work is https://github.com/DefinitelyTyped/DefinitelyTyped/issues/32901 (see there). We initially had the two things mixed but then split them in two as one was easily acceptable to the maintainers and the other (the open one) isn't. As long as the maintainers do not show any interest in the change I won't update the PR.

Comment (jerico-dev) [reply types/jest/index.d.ts]: I updated https://github.com/facebook/jest/issues/7832 to point to the right issue/PR, thanks @G-Rath for your heads-up.
