### PR TITLE
[@types/recordrtc] Fixed RecordRTC setRecordingDuration type and updated tests

### LINKED ISSUE #51892: Wrong typing / interface for setRecordingDuration method
Wrong interface here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46b370ffd2c8e81b21fac6a50f85be7a32d70efc/types/recordrtc/index.d.ts#L231

`setRecordingDuration` method should pass 2 arguments, and additionally there is not returned void then:

```
setRecordingDuration: function(recordingDuration, callback)
```

return:
```
{
    onRecordingStopped: function(callback) {
        self.onRecordingStopped = callback;
    }
};
```

https://github.com/muaz-khan/RecordRTC/blob/ebae1da10f50a521000cbcced5c5adfb96f32411/RecordRTC.js#L413

```
/**
 * Ask RecordRTC to auto-stop the recording after 5 minutes.
 * @method
 * @memberof RecordRTC
 * @instance
 * @example
 * var fiveMinutes = 5 * 1000 * 60;
 * recorder.setRecordingDuration(fiveMinutes, function() {
 *    var blob = this.getBlob();
 *    video.src = this.toURL();
 * });
 * 
 * // or otherwise
 * recorder.setRecordingDuration(fiveMinutes).onRecordingStopped(function() {
 *    var blob = this.getBlob();
 *    video.src = this.toURL();
 * });
 */
```

### PR DESCRIPTION
**Pull request by ghost**
Fix #51892  
Checkout #51892 for more info

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test recordrtc`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #51892 
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~ (N/A)

### CODE REVIEW

File: types/recordrtc/index.d.ts [hunk 1]
```diff
@@ -228,7 +228,9 @@ declare class RecordRTC {
     resumeRecording(): void;
 
     /** auto stop recording after specific duration */
-    setRecordingDuration(): void;
+    setRecordingDuration(): {
+        onRecordingStopped: (callback: (...args: any[]) => any) => any;
+    };
```
Comment (k-yle) [inline types/recordrtc/index.d.ts:233]: based on [the source code](https://github.com/muaz-khan/RecordRTC/blob/eb16816757121bcfcbd198d394d4d47459cadd22/dev/RecordRTC.js#L405-L414), I think we can type this a bit stricter using two overloads:

```suggestion
    setRecordingDuration(milliSeconds: number): {
        onRecordingStopped: (callback: () => void) => void;
    };
    /** auto stop recording after specific duration */
    setRecordingDuration(milliSeconds: number, onRecordingStopped: () => void): void;
```

I would also suggest you copy-paste [these examples](https://github.com/muaz-khan/RecordRTC/blob/eb16816757121bcfcbd198d394d4d47459cadd22/dev/RecordRTC.js#L405-L414) into the test file to ensure it passes.

**Review by k-yle — CHANGES_REQUESTED** [review]
this is fine but I've suggested a change that makes the types even stricter

**Review by k-yle — APPROVED** [review]
lgtm. thanks!

**Comment by k-yle** [comment]
Ready to merge
