### PR TITLE
hapi: fix incorrect connection.table() result type

### LINKED ISSUE #17005: @types/hapi has wrong ServerConnection table() type
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jasonswearingen @AJamesPhillips

The Hapi.Server has a [ServerConnection array](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts#L75) which exposes a [`table()`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hapi/index.d.ts#L1569) method.
The official [hapi documentation](https://hapijs.com/api/16.1.1#serverconnections) doesn't tell readers what the return value is.

Looking at the [`table()` source](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L336) one can see that it calls the table method on its `_router`.
Turns out that `_router` is an instance of [`Call.Router`](https://github.com/hapijs/hapi/blob/master/lib/connection.js#L81) which gets imported from the [`hapijs/call`](https://github.com/hapijs/call) module.

The `call` routers `table` method returns an [array of its routes](https://github.com/hapijs/call/blob/master/lib/index.js#L358).
Here a route is an [object with some properties](https://github.com/hapijs/call/blob/master/lib/index.js#L51-L58).

This means that the current ServerConnection `table()` method types are wrong.

I would like to fix this but am unsure if this requires a type definition for the `hapijs/call` module or if it's ok to create an interface for the call route object for now.

See attachment for example call route object:

### PR DESCRIPTION
**Pull request by makepanic**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - fixes #17005
  - call returns its previously received hapi route [here](https://github.com/hapijs/call/blob/master/lib/index.js#L346)
  - hapi defines its route [here](https://github.com/hapijs/hapi/blob/v16.1.1/lib/route.js#L23)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The change basically extends type information of a hapi route (see screenshot in #17005 for example structure) and sets the correct return type for hapi/call `table()` result.
It also changes the type of settings to `RouteAdditionalConfigurationOptions` because, as seen in the screenshot, `settings` contains the whole configuration options and not only `RouteConfiguration`.

### CODE REVIEW

File: types/hapi/index.d.ts [hunk 1]
```diff
@@ -1256,20 +1256,33 @@ export interface RoutingTableEntry {
 
 /**
  * [See docs](https://hapijs.com/api/16.1.1#servertablehost) > return value
+ * For source [See docs](https://github.com/hapijs/hapi/blob/v16.1.1/lib/route.js#L71)
```
Comment (AJamesPhillips) [inline types/hapi/index.d.ts]: `[See source](`...

File: types/hapi/index.d.ts [hunk 2]
```diff
@@ -1619,7 +1632,7 @@ export interface ServerConnection {
     inject(options: string | InjectedRequestOptions, callback: (res: InjectedResponseObject) => void): void;
     inject(options: string | InjectedRequestOptions, ): Promise<InjectedResponseObject>;
     /** Described in server.table [See docs](https://hapijs.com/api/16.1.1#servertablehost) */
```
Comment (AJamesPhillips) [inline types/hapi/index.d.ts]: The assumption I made is wrong and confusing.  Could you change this to the following please:

`/** Mentioned but not documented under server.connections [See docs](https://hapijs.com/api/16.1.1#serverconnections) */`

File: types/hapi/test/server/connections.ts [hunk 3]
```diff
@@ -11,3 +11,9 @@ server.connection({ port: 8080, labels: 'b' });
 const a = server.select('a');
 
 // a.connections.length === 1
+
+server.connections[0].table().map(({method, path, settings: {description}}) => ({
+    method,
+    path,
+    description
+}));
```
Comment (AJamesPhillips) [inline types/hapi/test/server/connections.ts]: You can probably just replace this with something like:

    server.connections[0].table().map(({method, path, settings: {description}}) => ();

Bit shorter.

**Review by AJamesPhillips — COMMENTED** [review]
Looks good @makepanic.  And thanks for the screen shots too.  They were really useful for figuring out what was actually being returned without firing up a whole server and making requests.  Would be really amazing if you wanted to contribute some of this to the hapi docs.  Would be really helpful.  No expectation though, just if you want to.

File: types/hapi/test/server/connections.ts (hunk 3 above)
Comment (makepanic) [inline types/hapi/test/server/connections.ts]: Did that and also moved it to the `test/connection/table.ts` file. Didn't see that one previously

**Comment by AJamesPhillips** [comment]
@andy-ms good to merge.  Thanks @makepanic

**Comment by andy-ms** [comment]
Thanks!
