### PR TITLE
fix(lusca): missing CSRF 'header' base property

### LINKED ISSUE #45040: [@types/lusca] missing csrf option "header"
The lusca CSRF options have a property "header":
https://github.com/krakenjs/lusca/blob/0483eda77a6fcef08d9319369e1f2b6fd2a5dcba/lib/csrf.js#L49

Its missing in the type definitions:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f345d5ef8686cea2a136cb6b84d07b916dd50e15/types/lusca/index.d.ts#L44

@crutchcorn @builtinnya

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- `heaer` property added
- JSDoc comments added to the base options
- test amended

https://github.com/krakenjs/lusca/blob/0483eda77a6fcef08d9319369e1f2b6fd2a5dcba/lib/csrf.js#L49

/cc @shwao

Thanks!

Fixes #45040

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes

### CODE REVIEW

File: types/lusca/index.d.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 // Type definitions for lusca 1.6
 // Project: https://github.com/krakenjs/lusca#readme
-// Definitions by: Corbin Crutchley <https://github.com/crutchcorn>, Naoto Yokoyama <https://github.com/builtinnya>
+// Definitions by: Corbin Crutchley <https://github.com/crutchcorn>
+//                 Naoto Yokoyama <https://github.com/builtinnya>
```
Comment (crutchcorn) [inline types/lusca/index.d.ts:4]: @peterblazejewicz did you not want to add yourself to this definition?

**Review by crutchcorn — APPROVED** [review]

**Review by rbuckton — APPROVED** [review]
