### PR TITLE
[office-js][office-js-preview] fix syntax for associate method

### LINKED ISSUE #2017: The associate method is mistakenly configured as a property
https://learn.microsoft.com/en-us/javascript/api/office/office.actions?view=common-js-preview#office-office-actions-associate-member

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<(https://github.com/OfficeDev/office-js-docs-reference/issues/2017)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

Fixes [2017](https://github.com/OfficeDev/office-js-docs-reference/issues/2017)

### CODE REVIEW

**Review by ElizabethSamuel-MSFT — APPROVED** [review]

File: types/office-js-preview/index.d.ts [hunk 1]
```diff
@@ -3140,7 +3140,7 @@ declare namespace Office {
          * @param actionId The ID of an action that is defined in the manifest.
          * @param actionFunction The function that is run when the action is invoked. 
          */
-        associate: (actionId: string, actionFunction: (arg?: any) => void) => void;
+        associate(actionId: string, actionFunction: (arg?: any) => void) => void;
```
Comment (ElizabethSamuel-MSFT) [inline types/office-js-preview/index.d.ts:3143]: Does this need to be something like this?

```suggestion
        associate(actionId: string, actionFunction: (arg?: any) => void): Promise<void>;
```

Comment (Rick-Kirkham) [reply types/office-js-preview/index.d.ts:3143]: > Does this need to be something like this?

It's not async, so I don't think so.

Comment (ElizabethSamuel-MSFT) [reply types/office-js-preview/index.d.ts:3143]: right. Updated my suggestion inline without the "Promise"?
