### PR TITLE
fix(plotly.js): nested property attributes fix

### LINKED ISSUE #43735: @types/plotly.js Incorrect PlotRelayoutEvent type definition
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/plotly.js` package and had problems.

@peterblazejewicz 

I found another problem with the typescript definition file.  This time it is with the PlotRelayoutEvent interface.

based on my own experience with this event and based on the comments posted here
https://github.com/plotly/plotly.js/issues/168
https://github.com/plotly/plotly.js/issues/1877

and the documentation on this event here:
https://plotly.com/javascript/zoom-events/#binding-to-zoom-events

The interface should be changed to:

```
export interface PlotRelayoutEvent extends Partial<Layout> {
	'xaxis.range[0]'? : number; 
	'xaxis.range[1]'? : number; 
	'yaxis.range[0]'? : number; 
	'yaxis.range[1]'? : number; 
	'xaxis.autorange'? : boolean; 
	'yaxis.autorange'? : boolean;
}
```

If I knew how to create PR's I'd make this change myself, but I don't know how to use git, github, PR's etc, so I'm filing this issue instead.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This changes the shape of the PlotlyRelayoutEvent to use string based
property access as per-discussion here:
https://github.com/plotly/plotly.js/issues/1877

See:
https://plotly.com/javascript/plotlyjs-events/
https://plotly.com/javascript/zoom-events/#binding-to-zoom-events

/cc @mmakrzem

Thanks!

Fixes: #43735

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes

### CODE REVIEW

File: types/plotly.js/index.d.ts [hunk 1]
```diff
@@ -85,21 +85,19 @@ export type PlotRestyleEvent = [
...
-	autorange: boolean;
-}
-
 export interface PlotScene {
 	center: Point;
 	eye: Point;
 	up: Point;
 }
 
 export interface PlotRelayoutEvent {
```
Comment (mmakrzem) [inline types/plotly.js/index.d.ts:94]: When a plot is resized, it appears that the PlotRelayoutEvent contains the Layout information which is not included in this change.

Additionally, all the properties that were just added to the PlotRelayoutEvent interface should be marked as optional since not all of them are expected to be returned.  If you only zoom in horizontally, then the yaxis.* properties will not be included.  Similarly, if you use the toolbar button to reset the zoom level, then only the xaxis.autorange and yaxis.autorange values will be returned.

Therefore I believe the correct interface definition should be:

```
export interface PlotRelayoutEvent extends Partial<Layout> {
	'xaxis.range[0]'? : number; 
	'xaxis.range[1]'? : number; 
	'yaxis.range[0]'? : number; 
	'yaxis.range[1]'? : number; 
	'xaxis.autorange'? : boolean; 
	'yaxis.autorange'? : boolean;
}
```

Comment (mmakrzem) [reply types/plotly.js/index.d.ts:94]: @alexcjohnson

Comment (mmakrzem) [reply types/plotly.js/index.d.ts:94]: @etpinard

Comment (peterblazejewicz) [reply types/plotly.js/index.d.ts:94]: good point about optional, completely forgot about them, though I've used Codepen sample to catch differences at runtime. To be amended

Comment (peterblazejewicz) [reply types/plotly.js/index.d.ts:94]: So the event props are now optional after amending commit

Comment (peterblazejewicz) [reply types/plotly.js/index.d.ts]: > When a plot is resized, it appears that the PlotRelayoutEvent contains the Layout information which is not included in this change

I haven't seen that in the CodePen sample, but I've amended the PR to incorporate that change too. 
Thanks!
