### PR TITLE
[jquery] Improve declaration of Events API.

### LINKED ISSUE #17377: JQuery.Event is not assignable to Event
Some properties, such as `bubbles`, are not optional in the DOM `Event` type, but are in the JQuery type.

cc/ @leonard-thieu

(related?): The various `*Target` keys in `JQuery.Event` all share their type with `target`, but that is almost always incorrect unless the event was both not delegated and is being handled at the top of the bubbling order.

### LINKED ISSUE #30705: Using @types/angular with JQuery v3
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/angular` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @diegovilar @thorn0 @leonard-thieu @scipper 

If you're trying to use `@types/angular@^1.6.51` together with `@types/jquery@^3.3.22`  there will be mismatches that can cause issues. 

The exact issue I was running in to was working with events, `JQuery.Event` in JQuery v3 and `JQueryEventObject` in JQuery v2. 

Using `$.on()` will _work_, but falls to a `@deprecated` signature, which is suboptimal.

I've createda repo, https://github.com/oBusk/angular-jquery-event-issue that shows this situation.

I don't know if the solution is to upgrade JQLite to JQuery v3? Question is how that would work together with `@types/jquery@^1.0.0` or `@types/jquery@^2.0.0`

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

---

##### Improve declaration of Events API. (f13af8b / 00c5463 / 3a54bad0684cc88f91cfeac115d57554fc494c62 / db83bc7)

The `*Target` properties (`currentTarget`, `delegateTarget`, `relatedTarget`, and `target`) were all set to the same type parameter (`TTarget`). API methods passed the type of selected elements (`TElement`) to `TTarget`. This is only guaranteed to be correct for directly bound event handlers (excluding `relatedTarget`, which varies based on event type instead of binding type). This PR fixes this issue by replacing `TTarget` with `TDelegateTarget` for `delegateTarget`, `TCurrentTarget` for `currentTarget`, and `TTarget` for `target`. Methods that bind directly bound event handlers pass in `TElement` for all target-related type parameters as they are guaranteed to be the same object. Methods that bind delegate bound event handlers pass in `TElement` for `TDelegateTarget` and `any` for the rest of the target-related parameters. `unknown` would be better here but requires TypeScript 3.0. As the types of `currentTarget`, `relatedTarget`, and `target` cannot be known until run time, consumers will still need type assertions when accessing these properties but they are no longer presented with a type that could be outright wrong.

This PR also introduces the concept of a triggered event. A triggered event is a jQuery event that has been triggered (either manually by `.trigger()`/`.triggerHandler()` or automatically by the user agent). Many properties on a jQuery event are not set until it has been triggered. In particular, the `*Target` properties are not set on a freshly constructed `jQuery.Event` object. `JQuery.Event` now represents the object returned from the `jQuery.Event` constructor and serves as the base type for all jQuery events. This means that the `*Target` properties (and their type parameters) were removed from `JQuery.Event` and added to a new triggered event type ([`JQuery.TriggeredEvent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f13af8beb0b54f71d8a070c99fdf76cf5601433b/types/jquery/misc.d.ts#L4527)).

This PR also introduces event type-specific types for known events. When binding an event handler for a known event type, the event handler will receive an event type-specific type for that event type. For example, when binding to a "click" event, the event handler will receive a [`ClickEvent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/00c546398c4d3d98655a4bce525a077dd52c83c1/types/jquery/misc.d.ts#L5288) event that has all properties copied from `MouseEvent` (`button`, `ctrlKey`, `shiftKey`, etc) declared as non-nullable and `originalEvent` declared as `MouseEvent`. This should reduce the need for type assertions for consumers. Types have been added for event types that have an associated shorthand method and for touch events. Types for the rest of the DOM events may be added at a later point.

###### Migration notes

As a general note, there are many cases where the correct type can be inferred but consumers have annotated their code with an incorrect type. In these cases, it's best to just drop the annotation and let inference do its work.

Most breaks will be due to splitting `JQuery.Event` into `JQuery.TriggeredEvent`. As code that references `JQuery.Event` will typically be event handlers (and therefore dealing with a triggered event), the fix is to simply change the declaration from `JQuery.Event` to `JQuery.TriggeredEvent`. In cases where code actually wants to reference a base event type, the fix is to remove the type arguments from the declaration (the declaration will be simply `JQuery.Event`).

Fixes #17377
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26674#pullrequestreview-130294320
Fixes #30705 

##### Add deprecation notice for `Event.which`. (16770fa)

Deprecated since 3.3. See https://github.com/jquery/api.jquery.com/issues/821.

##### Remove `jQuery.event.props` and `jQuery.event.fixHooks`. (50b56a1 / e64bea6)

Removed since 3.0. See https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed.

##### Remove `jQuery.Event(EventLike)` signatures and `EventLike` interface. (32e0482)

These are undocumented and don't appear to be intended to be public.

###### Migration notes

If consumers still require the `EventLike` interface, they may add this declaration to their project.

```typescript
declare namespace JQuery {
    interface EventLike {
        type: string;
    }
}
```

##### Remove `JQuery.EventHandlerBase<TContext = any, JQuery.Event>` from handler types. (c1ec1c2)

Handler types previously included `JQuery.EventHandlerBase<TContext = any, JQuery.Event>`. This was a fix to what turned out to be a problem with `jQuery.proxy`. That issue was properly fixed by #29930.

---

Fixes 5 violations of `no-unnecessary-generics`.
Fixes 5 violations of `unified-signatures`.

---

Pinging @Kovensky @HolgerJeromin as they have expressed interest in this before.

---

@zhamid @nvivo @sventschui @razorness @confususs

The change to `@types/backbone` (68c38a8) was to fix a conflict with the [`EventsHash`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f9f6430117d025aef62ed56128deb65508edc86/types/backbone.marionette/index.d.ts#L261-L267) declaration in `@types/backbone.marionette`. You may wish to review that the change is appropriate.

---

The addition of touch events was to fix [test failures with `@types/viewporter`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f9f6430117d025aef62ed56128deb65508edc86/types/viewporter/viewporter-tests.ts#L119-L162). Not going to bother mentioning authors of `@types/viewporter` here as this was simply a matter of extending support.

### CODE REVIEW

File: types/jquery/misc.d.ts [hunk 1]
```diff
@@ -4707,114 +4631,1733 @@ $( "ul" ).click( handler ).find( "ul" ).hide();
...
+        TCurrentTarget,
+        TTarget,
+        TContext
+    > extends _TypeEventHandlers<TDelegateTarget, TData, TCurrentTarget, TTarget, TContext> {
+        // No idea why it's necessary to include `object` in the union but otherwise TypeScript complains that
+        // derived types of Event are not assignable to Event.
+        [type: string]: TypeEventHandler<TDelegateTarget, TData, TCurrentTarget, TTarget, TContext, string> |
+                        false |
+                        undefined |
+                        object;
```
Comment (leonard-thieu) [inline types/jquery/misc.d.ts]: Adding `object` to the union weakens the type a bit, although in practice, it's unlikely that users will attempt to a assign a non-function object to a property. I don't understand what's causing the assignability issue nor do I understand why including `object` in the union fixes it.

**Comment by HolgerJeromin** [comment]
Thanks for this change and pinging me. I will try to test it it on friday.

File: types/angular-agility/tslint.json [hunk 2]
```diff
@@ -74,6 +74,7 @@
         "typedef-whitespace": false,
         "unified-signatures": false,
         "void-return": false,
-        "whitespace": false
+        "whitespace": false,
+        "no-angle-bracket-type-assertion": false
```
Comment (minestarks) [inline types/angular-agility/tslint.json]: For consistency, please don't turn off linter rules. Especially on so many packages at once.

[You can use `as` instead.](https://palantir.github.io/tslint/rules/no-angle-bracket-type-assertion/)

**Review by minestarks — CHANGES_REQUESTED** [review]

File: types/jquery/misc.d.ts [hunk 3]
```diff
@@ -4712,10 +4708,6 @@ $( "ul" ).click( handler ).find( "ul" ).hide();
         target: TTarget;
     }
 
-    interface EventLike {
```
Comment (minestarks) [inline types/jquery/misc.d.ts]: Why were these added in the first place? Seems like 869c4ba5605d0dcdbe7804edae160dd2f984f1e3 introduced `EventLike`

File: types/jquery/misc.d.ts [hunk 4]
```diff
@@ -4704,17 +4631,173 @@ $( "ul" ).click( handler ).find( "ul" ).hide();
...
 
     // Extra parameters can be passed from trigger()
     type EventHandlerBase<TContext, T> = (this: TContext, t: T, ...args: any[]) => any;
 
+    type EventHandler<
+        TCurrentTarget,
+        TData = undefined
+    > = EventHandlerBase<TCurrentTarget, TriggeredEvent<TCurrentTarget, TData>>;
+
+    type TypeEventHandler<
```
Comment (minestarks) [inline types/jquery/misc.d.ts]: I can't find any instantiations of `TypeEventHandler` where `TCurrentTarget`, `TTarget` and `TContext` aren't all exactly the same type. It would be simpler to just have one type argument (`TTarget`?) instead of 3 separate ones.

Comment (minestarks) [reply types/jquery/misc.d.ts]: This comment was for an earlier commit -- I see you removed `TContext`, but my comment still applies to `TCurrentTarget` and `TTarget`. They could be simplified.

Comment (Kovensky) [reply types/jquery/misc.d.ts]: Sounds like a possible mistake elsewhere, an event's currentTarget is definitely not always the same as its target.

The way React dealt with it is that Change events and others that don't bubble have target = currentTarget, but other events have target being EventTarget.

TContext is supposed to be whatever was the 2nd argument of .on in 3-argument form so sounds like another omission.

File: types/angular-agility/tslint.json (hunk 2 above)
Comment (leonard-thieu) [reply types/angular-agility/tslint.json]: The lint failures were caused by an unrelated change (https://github.com/Microsoft/dtslint/pull/141).

I really wasn't interested in fixing all of those failures by hand.

Comment (minestarks) [reply types/angular-agility/tslint.json]: Hmm. The tests fail when you revert these changes?

File: types/jquery/misc.d.ts (hunk 3 above)
Comment (leonard-thieu) [reply types/jquery/misc.d.ts]: `EventLike` was used by an `Event` constructor overload. The overload does work but is not documented. I believe it's meant to be internal.

File: types/jquery/misc.d.ts (hunk 4 above)
Comment (leonard-thieu) [reply types/jquery/misc.d.ts]: For directly bound event handlers, `TElement` is passed for `TCurrentTarget` and `TTarget` because they are known to be the same object. For delegated event handlers, `any` is passed for `TCurrentTarget` and `TTarget` because they can be any element in the event propagation path and potentially refer to different objects.

I went with 2 type parameters because they're not semantically the same. I was also concerned there might be scenarios where say a user asserts that `currentTarget` is of a certain type which might allow TypeScript to infer that `target` is the same type since they share a type parameter. I don't know if TypeScript actually does this but it didn't seem unreasonable. There's also concern with what to name it. `jQuery.Event` has 4 properties that have `target` in the name, one of which is named `target`. I think if a user came across a type parameter named `TTarget`, they'd either expect it to cover just the `target` property or all 4 `*Target` properties, not just a particular 2 of the 4.

File: types/angular-agility/tslint.json (hunk 2 above)
Comment (leonard-thieu) [reply types/angular-agility/tslint.json]: Yes, they're still failing. 565 violations of the `no-angle-bracket-type-assertion` rule.

Comment (minestarks) [reply types/angular-agility/tslint.json]: Well I'm really sorry about that, I was unaware. That PR must have been merged without the necessary followup.

Thanks for fixing all the fallout. Could you revert your revert then? Once the tests pass I can merge this PR.

**Review by minestarks — APPROVED** [review]
