### PR TITLE
[@types/tar] Fixes type for mtime property of tar.Pack class

### LINKED ISSUE #67775: [@types/tar] PackOptions.mtime is a `Date`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2c68c9ee2fdae8c1e1a2748bcf3dc86d330fba14/types/tar/index.d.ts#L310

When used as a `number`, I get `TypeError: date.getTime is not a function` error at run-time:

```
$ node -e 'require("tar").c({mtime:1},["."])'
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: date.getTime is not a function
```

Also, `c`/`create` can take `PackOptions`, see https://github.com/isaacs/node-tar/blob/5bc9d404e88c39870e0fbb55655a53de6fbf0a04/lib/create.js#L108C22-L108C25

### PR DESCRIPTION
**Pull request by timagixe**
Fixes #67775 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [documentation for tar.Pack class](https://github.com/isaacs/node-tar/blob/5bc9d404e88c39870e0fbb55655a53de6fbf0a04/README.md#class-tarpack)

### CODE REVIEW

File: types/tar/index.d.ts [hunk 1]
```diff
@@ -307,7 +307,7 @@ export interface PackOptions {
      * Set to a Date object to force a specific mtime for everything added to
      * the archive. Overridden by noMtime.
      */
-    mtime?: number;
+    mtime?: Date;
```
Comment (timagixe) [inline types/tar/index.d.ts:310]: Hi @SomaticIT, @connor4312! Do we need to increment minor version introducing this change?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/945cb7690e8fb6989b3ccb6b4a6fdc9315f05d2c/types/tar/package.json#L4

```diff
-    "version": "6.1.9999",
+    "version": "6.2.9999", 
```

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by timagixe** [comment]
Ready to merge
