### PR TITLE
fix(mermaid): fix mermaid.render to take an Element as the fourth argument instead of a string

### LINKED ISSUE #51625: Wrong type definition mermaidAPI.render
Hello,

It seems that by looking at [the mermaid code](https://github.com/mermaid-js/mermaid/blob/9fafe5069342da6e59e23b5bd23a2a86b09701a3/src/mermaidAPI.js#L242), the optional `container` argument of `mermaidAPI.render` is more a `HTMLElement` than a `string`:

```js
const render = function(id, _txt, cb, container) {
    // …
    container.innerHTML = '';
```

Versus:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/85481972feb247630f53d421cf7a03e2b2a2f28b/types/mermaid/mermaidAPI.d.ts#L248

Best regards,
Nicolas

### PR DESCRIPTION
**Pull request by LeSuisse**
Closes #51625

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mermaid-js/mermaid/blob/9fafe5069342da6e59e23b5bd23a2a86b09701a3/src/mermaidAPI.js#L242
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

File: types/mermaid/mermaid-tests.ts [hunk 1]
```diff
@@ -26,5 +26,5 @@ const insertSvg = (
 
 const graphDefinition = "graph TB\na-->b";
 let graph: string;
-graph = mermaidAPI.render("graphDiv", graphDefinition, insertSvg);
+graph = mermaidAPI.render("graphDiv", graphDefinition, insertSvg, element);
```
Comment (peterblazejewicz) [inline types/mermaid/mermaid-tests.ts:29]:
```suggestion
graph = mermaidAPI.render("graphDiv", graphDefinition, insertSvg);
graph = mermaidAPI.render("graphDiv", graphDefinition, insertSvg, element);
```

**Review by peterblazejewicz — APPROVED** [review]
LGTM!
@LeSuisse thx!

**Review by peterblazejewicz — APPROVED** [review]

**Comment by LeSuisse** [comment]
Ready to merge
