### PR TITLE
[@types/mongodb] Fix deprecation warnings related to write concern

### LINKED ISSUE #51191: [@types/mongodb] Deprecation warnings for w, fsync, j and wtimeout
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT, @alanmarcell, @dante-101, @mcortesi, and others

When using `mongodb@3.6.4` with `@types/mongodb@3.6.7`, I get the following warning when trying to connect to a MongoDB:

> Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.

However, it is not possible to use `writeConcern` instead of `w`, because then `tsc` complains about:

> Object literal may only specify known properties, and 'writeConcern' does not exist in type 'MongoCallback<MongoClient>

So, I assume, that the types do not reflect the latest changes of the driver's API here. Could you maybe update this, eventually, please?

### PR DESCRIPTION
**Pull request by borfig**
Fixes #51191.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jira.mongodb.org/browse/NODE-1722 https://github.com/mongodb/node-mongodb-native/pull/2624

### CODE REVIEW

File: types/mongodb/index.d.ts [hunk 1]
```diff
@@ -34,6 +34,7 @@
 //                 Anna Henningsen <https://github.com/addaleax>
 //                 Emmanuel Gautier <https://github.com/emmanuelgautier>
 //                 Wyatt Johnson <https://github.com/wyattjoh>
+//                 Boris Figovsky <https://github.com/borfig>
```
Comment (amcasey) [inline types/mongodb/index.d.ts:37]: Note that this means that you want to be notified of future changes to these types so that you can provide feedback (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#definition-owners).

Comment (borfig) [reply types/mongodb/index.d.ts:37]: I am aware of this. I have done the same at @types/mongoose

Comment (amcasey) [reply types/mongodb/index.d.ts:37]: Thanks for confirming!

**Review by LinusU — APPROVED** [review]
Neat 👍

**Review by peterblazejewicz — APPROVED** [review]

**Comment by borfig** [comment]
Ready to merge
