### PR TITLE
fix(mssql): updated for 6.0.0

### LINKED ISSUE #32326: Upgrade @types/mssql to match with mssql@4.3.0
If you know how to fix the issue, make a pull request instead.

- [ Y ] I tried using the `@types/mssql` package and had problems.
- [ Y ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ Y ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ Y ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaminfarr @buzinas @mrrichar @elhaard @pkeuter @mcdado

If you do not mention the authors the issue will be ignored.

-----

@types/mssql is not up to date with the latest version of mssql as Promise-based functions such as mssql.connect and mssql.query are highlighted as invalid with @types/mssql installed.

### LINKED ISSUE #34514: @types/mssql - Support for readOnlyIntentOption in Ioptions
-  I tried using the `@types/mssql` package and I see it doesn't expose readOnlyIntent option though native JS library works fine. Below is the compile time error when you do tsc

**error TS2322: Type '{ readOnlyIntent: boolean; }' is not assignable to type 'IOptions'.
  Object literal may only specify known properties, and 'readOnlyIntent' does not exist in type 'IOptions'.**

@jaminfarr @buzinas @mrrichar  @mcdado @pkeuter @elhaard any plans on exposing this ?

### PR DESCRIPTION
**Pull request by achrinza**
fixes #34514
fixes #32326

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tediousjs/node-mssql/blob/5acf2c27b543f3f115744dfa00f86034076c314f/README.md
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

**Review by cahilfoley — APPROVED** [review]
Looks good to me 👍

File: types/mssql/index.d.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Type definitions for mssql 4.3.0
+// Type definitions for mssql 6.0.0
 // Project: https://www.npmjs.com/package/mssql
 // Definitions by: COLSA Corporation <http://www.colsa.com/>
 //                 Ben Farr <https://github.com/jaminfarr>
```
Comment (JaminFarr) [inline types/mssql/index.d.ts]: Can you remove my name in this pull request too?

I've changed jobs and haven't used mssql for awhile.

Comment (achrinza) [reply types/mssql/index.d.ts]: Sure, it's been removed

**Review by JaminFarr — APPROVED** [review]
LGTM!
