### PR TITLE
[react-material-ui-form-validator] Fix #38102, fix type of event argument in onSubmit

### LINKED ISSUE #38102: [@types/react-material-ui-form-validator] wrong onSubmit declaration
`onSubmit` currently have this signature:
```ts
onSubmit: (event: React.FormEventHandler) => void;
```

should be:
```ts
onSubmit: React.FormEventHandler;
```

... or something like:
```ts
(event: React.FormEvent<Element>) => void;
```

ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c92cef26e1a054b8367f56dd8d7c7f033804f49/types/react-material-ui-form-validator/index.d.ts#L13

### PR DESCRIPTION
**Pull request by orangain**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/NewOldMax/react-form-validator-core/blob/0.6.4/src/ValidatorForm.jsx#L64
  - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38102
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

File: types/react-material-ui-form-validator/react-material-ui-form-validator-tests.tsx [hunk 1]
```diff
@@ -6,7 +6,9 @@ import {
 } from 'react-material-ui-form-validator';
 
 class Test extends React.Component {
-    onSubmitted = (event: React.FormEventHandler) => {};
+    onSubmitted = (event: React.FormEvent) => {
+        alert(event.target);
```
Comment (FrankBrullo) [inline types/react-material-ui-form-validator/react-material-ui-form-validator-tests.tsx]: No UI Blocking code in test please

**Review by FrankBrullo — CHANGES_REQUESTED** [review]

File: types/react-material-ui-form-validator/react-material-ui-form-validator-tests.tsx (hunk 1 above)
Comment (orangain) [reply types/react-material-ui-form-validator/react-material-ui-form-validator-tests.tsx]: @FrankBrullo Thank you for the review. Changed test code. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38699/commits/626687de53049af6a993a5b2eeb69fc7816c6fdb

**Review by FrankBrullo — APPROVED** [review]
