### PR TITLE
[next] Fixed incorrect type signature of `next/dynamic`

### LINKED ISSUE #24537: next/dynamic doesn't match dynamic import spec
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/106d393592fe348ea3da2ef1fc1faa1317e045b5/types/next/dynamic.d.ts#L27

@andy-ms hey do you think you could update the definition to match the import spec?

by default dynamic import returns `{default: Promise<React.ComponentType<TCProps>>}` not `Promise<React.ComponentType<TCProps>>`

### PR DESCRIPTION
**Pull request by resir014**
Fixed a longstanding bug where `next/dynamic` cannot load dynamically-imported components due to incorrect type signatures. Also added tests with a "real-life" example of component imports.

I'm not sure how to handle components exported with `export { Component }` so I left this aside for now, ~~but I'll take a look again either later today or tomorrow~~ I give up. This might have to wait until the next PR.

Fixes https://github.com/zeit/next.js/issues/4515
Fixes #24537

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/zeit/next.js/issues/4515
  - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24537
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by resir014** [comment]
Let's wait for at least one review approval before merging, just in case someone has a solution for the named export components.

File: types/next/test/next-dynamic-tests.tsx [hunk 1]
```diff
@@ -53,7 +69,7 @@ const helloBundleJSX = <HelloBundle foo="bar" />;
 
 // 5. With plain Loadable options
 const LoadableComponent = dynamic({
-    loader: () => asyncComponent,
+    loader: () => import('./imports/with-default'),
```
[the remark this answers is not in the document]
Comment (joaovieira) [reply types/next/test/next-dynamic-tests.tsx]: I believe Next.js examples have changed - before were using the component promises directly instead of the loader functions. Do you know if that's required now? Or if it accepts both?

File: types/next-server/test/next-server-dynamic-tests.tsx [hunk 2]
```diff
@@ -17,30 +17,42 @@ const LoadingComponent: React.StatelessComponent<LoadingComponentProps> = ({
...
-const DynamicComponent2 = dynamic(() => asyncComponent);
+// 1.1 Basic Usage (Loader function, module shape with 'export = Component' / 'module.exports = Component')
+const DynamicComponent2 = dynamic(() => Promise.resolve(MyComponent));
 const dynamicComponent2JSX = <DynamicComponent2 foo="bar" />;
 
+// 1.2 Basic Usage (Loader function, module shape with 'export default Component')
+const DynamicComponent3 = dynamic(() => Promise.resolve({ default: MyComponent }));
+const dynamicComponent3JSX = <DynamicComponent3 foo="bar" />;
+
+// TODO: Work with module shape 'export { Component }'
```
Comment (joaovieira) [inline types/next-server/test/next-server-dynamic-tests.tsx]: how is this supposed to work? isn't the user supposed to resolve the component manually?

File: types/next/test/next-dynamic-tests.tsx [hunk 3]
```diff
@@ -17,26 +17,42 @@ const LoadingComponent: React.StatelessComponent<LoadingComponentProps> = ({
...
 });
 
 // 4. With Multiple Modules At Once
 const HelloBundle = dynamic<MyComponentProps>({
     modules: () => {
         const components = {
-            Hello1: asyncComponent,
-            Hello2: asyncComponent
+            Hello1: () => import('./imports/with-default'),
+            Hello2: () => import('./imports/with-default')
```
Comment (joaovieira) [inline types/next/test/next-dynamic-tests.tsx]: isn't this a different test? and isn't it already covered by `1.x` scenarios?

**Review by joaovieira — COMMENTED** [review]
@resir014 looks alright to me. I feel we can clean up tests slightly though. I feel we could've just updated the `asyncComponent` variable to be more realistic (using the `import()` as you did), keep the old tests, and only add new tests for the added `asyncComponentLoader` and the `{default: Component}` formats in the `1.x` group.

File: types/next/test/next-dynamic-tests.tsx (hunk 3 above)
Comment (resir014) [reply types/next/test/next-dynamic-tests.tsx]: I was thinking of deleting all the tests that were migrated to `next-server` but thought against it. Maybe I should just delete it after all since it's probably useless to duplicate these tests in the `next` package as well.

File: types/next-server/test/next-server-dynamic-tests.tsx (hunk 2 above)
Comment (resir014) [reply types/next-server/test/next-server-dynamic-tests.tsx]: `react-loadable` (of which `next/dynamic` is based off of since Next.js 7) supports the following import style:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-loadable/test/index.tsx#L40-L50

I haven't yet to test if it actually works for Next.js, but we couldn't actually do it with the way our types are structured. Besides, it might be better that we stick to default dynamic imports instead.

File: types/next/test/next-dynamic-tests.tsx [hunk 4]
```diff
@@ -17,26 +17,42 @@ const LoadingComponent: React.StatelessComponent<LoadingComponentProps> = ({
...
+// TODO: Work with module shape 'export { Component }'
+
 // 2. With Custom Loading Component
-const DynamicComponentWithCustomLoading = dynamic(asyncComponent, {
+const DynamicComponentWithCustomLoading = dynamic(import('./imports/with-default'), {
+    loading: LoadingComponent
+});
+const dynamicComponentWithCustomLoadingJSX = <DynamicComponentWithCustomLoading foo />;
+
+// 2.1. With Custom Loading Component (() => import('') syntax)
```
Comment (joaovieira) [inline types/next/test/next-dynamic-tests.tsx]: if we do https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33163/files/02ba783ed3c98ecc0c625474d3d186fa810e367c#r258041360 this is already tested? Group 2. is testing the options. If we want to be really complete than we should have `2.1`, `2.2`, `3.1`, `3.2`, `4.1` and `4.2` for all the possibilities.

File: types/next/test/next-dynamic-tests.tsx [hunk 5]
```diff
@@ -17,26 +17,42 @@ const LoadingComponent: React.StatelessComponent<LoadingComponentProps> = ({
...
+const DynamicComponentWithCustomLoading2 = dynamic(() => import('./imports/with-default'), {
     loading: LoadingComponent
 });
-const dynamicComponentWithCustomLoadingJSX = <DynamicComponentWithCustomLoading foo="bar" />;
+const dynamicComponentWithCustomLoading2JSX = <DynamicComponentWithCustomLoading2 foo />;
 
 // 3. With No SSR
-const DynamicComponentWithNoSSR = dynamic(asyncComponent, {
+const DynamicComponentWithNoSSR = dynamic(() => import('./imports/with-default'), {
```
Comment (joaovieira) [inline types/next/test/next-dynamic-tests.tsx]: same as https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33163/files/02ba783ed3c98ecc0c625474d3d186fa810e367c#r258056892

File: types/next-server/test/next-server-dynamic-tests.tsx (hunk 2 above)
Comment (joaovieira) [reply types/next-server/test/next-server-dynamic-tests.tsx]: Interesting, I guess we have to export `Component` from the module instead of `MyComponent` then?

File: types/next/test/next-dynamic-tests.tsx (hunk 3 above)
Comment (joaovieira) [reply types/next/test/next-dynamic-tests.tsx]: Yes, I already got confused 😬

**Comment by resir014** [comment]
Alright, I'll try and remember to clean up all of these tests tomorrow.

**Review by amcasey — CHANGES_REQUESTED** [review]
Changing status to indicate that we are waiting for PR feedback to be addressed.

File: types/next-server/test/next-server-dynamic-tests.tsx [hunk 6]
```diff
@@ -18,29 +13,34 @@ const LoadingComponent: React.StatelessComponent<LoadingComponentProps> = ({
...
 
 // 3. With No SSR
-const DynamicComponentWithNoSSR = dynamic(asyncComponent, {
+const DynamicComponentWithNoSSR = dynamic(() => asyncComponent, {
     ssr: false
 });
 
 // 4. With Multiple Modules At Once
-const HelloBundle = dynamic<MyComponentProps>({
+// TODO: Mapped components still doesn't infer their props.
```
Comment (resir014) [inline types/next-server/test/next-server-dynamic-tests.tsx]: This is a difficult one. We can still pass `BundleComponentProps` into the root component, however the internally mapped components (in the `modules` property) doesn't map in the props from the dynamically-imported component.

So in the `render` property we can do:
```tsx
{
    render: (props, { Hello1, Hello2 }) => (
        <div>
            <h1>{props.foo}</h1>
            <Hello1 />
            <Hello2 />
        </div>
    )
}
```

but we can't use the props from `asyncComponent` since it's mapped as `React.ComponentType<{}>`

Comment (resir014) [reply types/next-server/test/next-server-dynamic-tests.tsx]: That being said, the scope of this PR was only to fix the dynamic imports type error. I can try and solve this on a separate PR after this is merged.

File: types/next-server/test/next-server-dynamic-tests.tsx (hunk 2 above)
Comment (resir014) [reply types/next-server/test/next-server-dynamic-tests.tsx]: @joaovieira Yeah, that's the use for `./imports/no-default.tsx`.

**Comment by resir014** [comment]
Alright, I've cleaned up the test. @joaovieira @amcasey please have another look.

Also, the tests seem to be broken again. 😓

File: types/next-server/test/next-server-dynamic-tests.tsx (hunk 6 above)
Comment (joaovieira) [reply types/next-server/test/next-server-dynamic-tests.tsx]: Yeah, I see the problem. But the modules map is dynamically generated.. not sure if that's possible at all, unless with some TS wizardry 😩

**Review by joaovieira — APPROVED** [review]

**Comment by joaovieira** [comment]
@resir014 LGTM. Thanks for the cleanup. 

The error doesn't seem related? @amcasey

**Comment by amcasey** [comment]
@joaovieira sorry, we were having some problems last night.  Looks like it's green now.  Please let me know when this is ready to go.

**Review by joaovieira — APPROVED** [review]

**Comment by joaovieira** [comment]
@amcasey it's good to go for me 👍

**Review by amcasey — APPROVED** [review]
