### PR TITLE
fix(bootstrap): correct global export and `string` in constructor

### LINKED ISSUE #52334: Bootstrap@5 uses incorrect global
- [X] I tried using the `@types/bootstrap@5` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [X] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [X] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @denisname, @peterblazejewicz, @martin-badin

It appears that in Bootstrap 5, the correct syntax is `new bootstrap...()`, however, the global that is exported in these types is `Bootstrap`. This mismatch causes `tsc` to fail when I use `boostrap`, but the code to run. When I use `Bootstrap`, which makes `tsc` happy, the codes doesn't run. I'm using Bootstrap@5-beta3. See some sample syntax here: https://getbootstrap.com/docs/5.0/migration/#javascript

Also, it seems that your types are set up like the Bootstrap@4 types, just jQuery. However, it appears that Bootstrap@5 has gone in a different direction.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
Invalid export for usage in global script (non-ESM).

https://getbootstrap.com/docs/5.0/migration/#javascript

Invalid (missing) parameter for constructors:
https://github.com/twbs/bootstrap/blob/main/js/src/base-component.js#L21

Thanks!

/cc @cjbarth

Fixes #52334

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

### CODE REVIEW

**Review by martin-badin — APPROVED** [review]
@peterblazejewicz Thanks.

File: types/bootstrap/test/global-script.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// test global script usage
+
+const modal = new bootstrap.Modal("#myModal");
```
Comment (cjbarth) [inline types/bootstrap/test/global-script.ts:3]: You might want to add a test for a global constructor that takes an `Element` as the first argument. That would add completeness.

Comment (peterblazejewicz) [reply types/bootstrap/test/global-script.ts:3]: done, amended, thx!

**Review by cjbarth — APPROVED** [review]

**Comment by initplatform** [comment]
This looks good to go...  @denisname, @martin-badin ?

**Review by martin-badin — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge 💘
