### PR TITLE
[@types/jsdom] - Fix #21235: add global types to DOMWindow interface

### LINKED ISSUE #21235: @types/jsdom missing Event definitions
@leonard-thieu 

[jsdom](https://github.com/tmpvar/jsdom) has Event constructors on the window object (e.g. [MouseEvent](https://github.com/tmpvar/jsdom/issues/1546)), but there are no type definitions for these in `@types/jsdom`.

For example, the following is possible with jsdom, but missing the type definition for `window.Event`, causing the build to fail:

```typescript
import { JSDOM } from 'jsdom';
let dom = new JSDOM();
let event = new dom.window.Event('someTypeArg');
```

In your current implementation the type definition for window is:

```typescript
export interface DOMWindow extends Window { eval(script: string): void; }
```

Digging deeper, the Window interface as defined by [TypeScript](https://github.com/microsoft/typescript) itself does not contain definitions for the Event types. However, they do have definitions for these types, just not on the Window interface.

This should be an easy fix, simply include these Event type definitions on the DOMWindow interface for `@types/jsdom`. They could also be added to the Window interface by the TypeScript team. I would also suggest the possibility of the jsdom team making the Event types global, but they are not interested in doing this as indicated in the MouseEvent link above.

### PR DESCRIPTION
**Pull request by KevinSnyderCodes**
TypeScript team is figuring out how to expose these types on their `Window` interface, which `DOMWindow` extends (discussion [here](https://github.com/Microsoft/TypeScript/issues/19816)). In the meantime, this workaround will ensure that jsdom code compiles.

Some types are not defined even globally by TypeScript. These have been commented out in the `DOMWindow` interface, but are still valid properties in jsdom. If someone tries to use these properties, their code will still not compile.

This should be an exhaustive list of all properties on the DOM window object implemented by jsdom.

------------------

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [jsdom/lib/jsdom/living/index.js](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/index.js) (other files included in changes as comments)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by leonard-thieu — APPROVED** [review]

**Comment by RyanCavanaugh** [comment]
Approved by a listed owner. PR ready to merge pending express review by a maintainer.

File: types/jsdom/index.d.ts [hunk 1]
```diff
@@ -103,7 +103,153 @@ export type ConstructorOptions = Options & {
...
+    HTMLAreaElement: typeof HTMLAreaElement;
+    HTMLAudioElement: typeof HTMLAudioElement;
+    HTMLBaseElement: typeof HTMLBaseElement;
+    HTMLBodyElement: typeof HTMLBodyElement;
+    HTMLBRElement: typeof HTMLBRElement;
+    HTMLButtonElement: typeof HTMLButtonElement;
+    HTMLCanvasElement: typeof HTMLCanvasElement;
+    HTMLDataElement: typeof HTMLDataElement;
+    HTMLDataListElement: typeof HTMLDataListElement;
+    // HTMLDetailsElement: typeof HTMLDetailsElement;
```
Comment (DanielRosenwasser) [inline types/jsdom/index.d.ts]: Is there any reason why these are commented out?

Comment (kevipapo1) [reply types/jsdom/index.d.ts]: From the OP:

> Some types are not defined even globally by TypeScript. These have been commented out in the DOMWindow interface, but are still valid properties in jsdom. If someone tries to use these properties, their code will still not compile.

I kept the properties listed but commented out so we wouldn't need to dig up these properties in the future.

Comment (DanielRosenwasser) [reply types/jsdom/index.d.ts]: Sorry I missed that; thanks!
