### PR TITLE
[react-dom] render has wrong signature

### LINKED ISSUE #23527: `ReactDOM.render` has a wrong method signature
Hi @MartynasZilinskas @theruther4d

- [x] I tried using the `@types/react-dom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).

------------

`ReactDOM.render` has a wrong method signature, [react-dom/index.d.ts#L94-L99](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-dom/index.d.ts#L94-L99)

```ts
(
    parentComponent: Component<any> | Array<Component<any>>,
    element: SFCElement<any>,
    container: Element,
    callback?: () => void
): void;
```
This has been in d.ts file for a long time.

In the source code of react.js, the `render` function only accepts 3parameters: `element`, `container`, `callback`.

-----------------

I wrote a demo:

**Foo.tsx** (ComponentClass)

```ts
import * as React from "react";

export interface FooProps {
  name: string;
}

export class Foo extends React.Component<FooProps> {
  render() {
    return <div>Hello {this.props.name}!</div>;
  }
}
```

**Bar.tsx** (StatelessComponent)

```ts
import * as React from "react";

export interface BarProps {
  name: string;
}

export const Bar = (props: BarProps) => <div>Hello {props.name}</div>;
```

**index.tsx**

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

import { Foo } from "./Foo";
import { Bar } from "./Bar";

const hello = new Foo({
    name: "Foo",
});

const bar = React.createElement(Bar, { name: "Bar" });

ReactDOM.render(hello, bar, document.getElementById("root"));
```

**webpack.config.js**

```js
module.exports = {
  entry: "./src/index.tsx",
  output: {
    filename: "bundle.js",
    path: __dirname + "/dist"
  },

  devtool: "source-map",

  resolve: {
    extensions: [".ts", ".tsx", ".js", ".json"]
  },

  module: {
    rules: [
      { test: /\.tsx?$/, loader: "awesome-typescript-loader" },
      { enforce: "pre", test: /\.js$/, loader: "source-map-loader" }
    ]
  },

  externals: {
    "react": "React",
    "react-dom": "ReactDOM"
  }
};
```

When I run `webpack`, it can successfully compile, without any error.

output:

```
[at-loader] Using typescript@2.7.1 from typescript and "tsconfig.json" from ~/react_ts/tsconfig.json.
[at-loader] Checking started in a separate process...
[at-loader] Ok, 0.569 sec.

Hash: 1824d6946f211a66d0f0
Version: webpack 3.10.0
Time: 2016ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  4.51 kB       0  [emitted]  main
bundle.js.map  4.35 kB       0  [emitted]  main
   [1] ./src/index.tsx 388 bytes {0} [built]
   [3] ./src/Foo.tsx 1.02 kB {0} [built]
   [4] ./src/Bar.tsx 220 bytes {0} [built]
    + 2 hidden modules
Done in 2.82s.
```

But when I run the app, I got nothing but the error message

> Target container is not a DOM element.

### PR DESCRIPTION
**Pull request by justjavac**
fixes #23527

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23527
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

### CODE REVIEW

File: types/react-dom/index.d.ts [hunk 1]
```diff
@@ -91,11 +91,4 @@ export interface Renderer {
         container: Element | null,
         callback?: () => void
     ): Component<any, ComponentState> | Element | void;
-
-    (
-        parentComponent: Component<any> | Array<Component<any>>,
-        element: SFCElement<any>,
-        container: Element,
-        callback?: () => void
-    ): void;
```
Comment (Jessidhia) [inline types/react-dom/index.d.ts]: It looks as if this was intended to be an overload of `unstable_renderSubtreeIntoContainer`? 🤔

**Review by Jessidhia — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!
