### PR TITLE
[react-redux] Correctly infer prop types from wrapped component

### LINKED ISSUE #27959: [@types/react-redux] defaultProps and Typescript 3.0
- [x] I tried using the `@types/react-redux` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @nicholasboll @mdibyo @pdeva @kallikrein @val1984 @jrakotoharisoa

### Package versions

- `typescript@3.0.1`
- `react@16.4.2`
- `react-redux@5.0.7`
- `@types/react@16.4.8`
- `@types/react-redux@6.0.6`

### Code
```tsx
import React from "react";
import { connect } from "react-redux";

interface Props {
  propWithDefault: string;
}

class TestComponent extends React.Component<Props> {
  static defaultProps = {
    propWithDefault: "Hello",
  };
}

const ConnectedTestComponent = connect()(TestComponent);

const el1 = <TestComponent />;
const el2 = <ConnectedTestComponent />;
```

### Issue
The line `const el1 = <TestComponent />;` works as intended with [Typescript 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx) defaultProps support.
However, the last line throws this error:

    Type '{}' is not assignable to type 'Readonly<Pick<Props, "propWithDefault">>'.
      Property 'propWithDefault' is missing in type '{}'.

I guess `@types/react-redux` has not yet been updated to support this new feature so I opened this issue. I've no idea how hard it is to make this work but I hope it will be supported eventually.

### PR DESCRIPTION
**Pull request by apapirovski**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html

---

This makes sure the inferred props include the `defaultProps` and `propTypes` resolutions by using `JSX.LibraryManagedAttributes`. I don't know how people feel about using `JSX.LibraryManagedAttributes` here directly but it feels better than rewriting the same thing from scratch...

This fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27959

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
🔔 @tkqubo @thasner @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @pdeva @Kallikrein @val1984 @jrakotoharisoa can you take a look please

File: types/react-redux/react-redux-tests.tsx [hunk 1]
```diff
@@ -1155,3 +1155,36 @@ namespace TestFailsMoreSpecificInjectedProps {
...
+		return {
+			foo: 'foo',
+		};
+	}
+
+	const ConnectedComponent = connect(mapStateToProps)(Component);
+	<ConnectedComponent fn={() => {}} />
+
+	const ConnectedComponent2 = connect<MapStateProps, void, OwnProps>(mapStateToProps)(Component);
+	<ConnectedComponent fn={() => {}} />
```
Comment (fa-askin) [inline types/react-redux/react-redux-tests.tsx]: Shouldn't that be 	`<ConnectedComponent2 fn={() => {}} />`?

Comment (apapirovski) [reply types/react-redux/react-redux-tests.tsx]: Yes! Will fix that.

**Comment by apapirovski** [comment]
@DanielRosenwasser Looks like the bot removed the `Merge: YSYL` label accidentally. Any chance it could be re-added and/or this PR reviewed? Thanks in advance!

File: types/react-redux/index.d.ts [hunk 2]
```diff
@@ -52,6 +53,20 @@ interface AdvancedComponentDecorator<TProps, TOwnProps> {
...
 }
 
+/**
+ * a property P will be present if:
+ * - it is present in DecorationTargetProps
+ * - it is present in InjectedProps[P] and can satisfy DecorationTargetProps[P]
+ *   or it is not present in InjectedProps[P]
+ */
+type Matching<InjectedProps, DecorationTargetProps> = {
+	[P in keyof DecorationTargetProps]: P extends keyof InjectedProps
```
Comment (eps1lon) [inline types/react-redux/index.d.ts]: This will accept the following test case that fails on master:
```patch
index 67c21bf3d2..ff06cf338e 100644
--- a/types/react-redux/react-redux-tests.tsx
+++ b/types/react-redux/react-redux-tests.tsx
@@ -1154,6 +1154,10 @@ namespace TestFailsMoreSpecificInjectedProps {
   // Since it is possible the injected props could fail to satisfy the decoration props,
   // the following line should fail to compile.
   connect(mapStateToProps, mapDispatchToProps)(Component) // $ExpectError
+
+  const FunctionalComponent = (props: MoreSpecificDecorationProps) => null;
+  // found error on master but not in #28189
+  connect(mapStateToProps, mapDispatchToProps)(FunctionalComponent); // $ExpectError
 }
```

I narrowed the issue down to [this playground](https://bit.ly/2NhVNs0). Typescript accepts assigning a function that takes `never` to a function that takes `T`.

Comment (apapirovski) [reply types/react-redux/index.d.ts]: Thanks @eps1lon. I've adjusted the definition to also pass that test case.

Comment (alvis) [reply types/react-redux/index.d.ts]: @eps1lon: do you approve the change? We all hope it can be merged. :)

File: types/react-redux/index.d.ts [hunk 3]
```diff
@@ -52,6 +53,20 @@ interface AdvancedComponentDecorator<TProps, TOwnProps> {
...
+		? InjectedProps[P] extends DecorationTargetProps[P]
+			? DecorationTargetProps[P]
+			: InjectedProps[P]
+		: DecorationTargetProps[P];
```
Comment (kenzierocks) [inline types/react-redux/index.d.ts]: This code looks like it is effectively doing `Pick<keyof DecorationTargetProps, InjectedProps & DecorationTargetProps>`. Is this right? If so, perhaps it should be simplified to that. If not, I would appreciate a clarification in comments on why the code does this, and how it maps to what `connect` actually does.

**Review by octylFractal — CHANGES_REQUESTED** [review]
Looks good, except for the comment on `Matching`.

File: types/react-redux/index.d.ts (hunk 3 above)
Comment (apapirovski) [reply types/react-redux/index.d.ts]: That's not quite correct. The Pick version would represent something like `InjectedProps[P] & DecorationTargetProps[P]` rather than `InjectedProps[P]`. The latter is important because it's what ensures the types are matching.

File: types/react-redux/index.d.ts [hunk 4]
```diff
@@ -52,6 +53,20 @@ interface AdvancedComponentDecorator<TProps, TOwnProps> {
     (component: ComponentType<TProps>): ComponentClass<TOwnProps>;
 }
 
+/**
+ * a property P will be present if:
+ * - it is present in DecorationTargetProps
+ * - it is present in InjectedProps[P] and can satisfy DecorationTargetProps[P]
+ *   or it is not present in InjectedProps[P]
```
[the remark this answers is not in the document]
Comment (apapirovski) [reply types/react-redux/index.d.ts]: The comment is not quite correct anymore for the recently updated version. Updating right now.

**Comment by apapirovski** [comment]
@kenzierocks I've updated the comment.

File: types/react-redux/index.d.ts (hunk 3 above)
Comment (apapirovski) [reply types/react-redux/index.d.ts]: You can also modify the definition and confirm that the tests will fail with those changes.

**Comment by apapirovski** [comment]
I don't think the test is related to this PR :|

File: types/react-redux/index.d.ts (hunk 3 above)
Comment (kenzierocks) [reply types/react-redux/index.d.ts]: Okay, makes sense.

**Review by octylFractal — APPROVED** [review]

**Comment by apapirovski** [comment]
@kenzierocks Any chance you have the ability to add/remove labels? This has the "revision needed" which makes it impossible to merge.

Otherwise, @DanielRosenwasser? Any chance you can remove the label?

**Comment by kenzierocks** [comment]
I can't remove labels as a Contributor. You might try pushing again to re-run Travis, or if the failure is related to that PR, rebase off of master to incorporate the fix for it.

**Comment by apapirovski** [comment]
@kenzierocks Already reran Travis. I think the bot just has a bug around the "revision needed" label. Happened to me in another PR here a while ago.

**Comment by OliverJAsh** [comment]
This PR has caused a [few new bugs](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31363). Please can someone advise? We're not sure what the intention of `Matching` is: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31363#issuecomment-448013978
