### PR TITLE
fix(@types/chroma-js): allow LRGB interpolation mode

### LINKED ISSUE #48518: @types/chroma-js: can’t use 'lrgb' in 'average' method
**Issue**
The following `keyof ColorSpaces` prevents the use of `lrgb` in the `average` method:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e35c4f9525d98e40865db20ac878e5b51703721a/types/chroma-js/index.d.ts#L106

**Why**
[The docs suggests](https://vis4.net/chromajs/#chroma-average) this is the default mode, so I reckon it should be allowed.

**Workaround**
For now I’m using `undefined` because this is allowed

### PR DESCRIPTION
**Pull request by RetroCraft**
The current typings do not allow for `mode='lrgb'` in `mix`, `average`, and `luminance`. Ordinarily, this isn't a problem since `lrgb` is the default value since version 2.0 but there are cases when it's needed.

Closes #48518. See that issue for context.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://vis4.net/chromajs/#chroma-average>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

**Comment by danger-public** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## chroma-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/chroma-js@latest/))
was missing the following properties:
1. Color
1. version
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d3f20dd4e3b2682f40fbdb08288174939a6e654d
</p>

File: types/chroma-js/index.d.ts [hunk 1]
```diff
@@ -88,22 +88,22 @@ declare namespace chroma {
 
         /**
          * Mixes two colors. The mix ratio is a value between 0 and 1.
-         * The color mixing produces different results based the color space used for interpolation.
+         * The color mixing produces different results based the color space used for interpolation. Defaults to LRGB.
          * @example chroma.mix('red', 'blue', 0.25) // => #bf0040
          * @example chroma.mix('red', 'blue', 0.5, 'hsl') // => #ff00ff
          */
-        mix(color1: string | Color, color2: string | Color, f?: number, colorSpace?: keyof ColorSpaces): Color;
+        mix(color1: string | Color, color2: string | Color, f?: number, colorSpace?: InterpolationMode): Color;
```
Comment (andrewbranch) [inline types/chroma-js/index.d.ts:95]: The docs call the `f` parameter `ratio` and the `colorSpace` parameter `mode`. Those seem like better names given this change. Approving, but suggesting that change if it makes sense to you.

**Review by andrewbranch — APPROVED** [review]

**Comment by RetroCraft** [comment]
Ready to merge
