### PR TITLE
[jsdom] [parse5] - fix @types/jsdom import errors

### LINKED ISSUE #26338: @types/jsdom 11.0.5 causes an error
- [x] I tried using the `@types/jsdom` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript (2.9.1)
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @leonard-thieu

`@types/jsdom` 11.0.5 causes an following error, 11.0.4 is OK:

```
node_modules/@types/jsdom/index.d.ts:10:10 - error TS2305: Module '"C:/Users/xxxx/Documents/yyyy/node_modules/@types/jsdom/node_modules/parse5/lib/index"' has no exported member 'ElementLocation'.

10 import { ElementLocation } from 'parse5';
            ~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by andnp**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

---

This change adds `v4` of the parse5 types. The types are copy/paste from [here](https://github.com/inikulin/parse5/commit/3bfa7d9f3297f96772a8eb26d9cfc4d79314af8b#diff-0e3ac3694919aca1db302bc3ebe669f2) which is a link to the commit where the types were removed for parse5@5

I copied and modified the unit tests from parse5@5 for the parse5@4 unit tests. These probably aren't as complete as they could be, but I'm not overly familiar with parse5 so wasn't able to write idiomatic tests.

---

The motivation here is actually that `@types/jsdom@11.0.5` is broken (failed import) because it is now pulling in the incompatible `@types/parse5@5` where previously it was pulling the types from `parse5@3`. From [here](https://github.com/jsdom/jsdom/blob/master/package.json#L34) I see that jsdom uses `parse5@4` hence my decision to move those types and bump the `@types/jsdom` dependency on parse5.

I have never added a major version subfolder for a DT package before, so extra eyes to make sure I did that correctly would be much appreciated!

This should fix #26338

### CODE REVIEW

File: types/jsdom/index.d.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@
 /// <reference types="node" />
 
 import { EventEmitter } from 'events';
-import { ElementLocation } from 'parse5';
```
Comment (andnp) [inline types/jsdom/index.d.ts]: This is the error that this PR aims to fix.

File: types/parse5/v4/tslint.json [hunk 2]
```diff
@@ -0,0 +1,17 @@
+{
```
Comment (andnp) [inline types/parse5/v4/tslint.json]: I chose to disable failing lint rules instead of trying to fix the problem spots. This was done in favor of keeping the v4 types _exactly_ as they were when I copied and pasted them from their originating repo.

File: types/parse5/v4/index.d.ts [hunk 3]
```diff
@@ -0,0 +1,1081 @@
+// Type definitions for parse5 4.0
+// Project: https://github.com/inikulin/parse5
+// Definitions by:  Ivan Nikulin <https://github.com/inikulin>
```
Comment (andnp) [inline types/parse5/v4/index.d.ts]: @inikulin I've added you here as a maintainer because I _believe_ you were the original author of these types?

There's no pressure to be a maintainer for them now, so I can remove your name here if you'd like.

Comment (inikulin) [reply types/parse5/v4/index.d.ts]: Thanks, I'm fine maintaining it.

**Review by inikulin — APPROVED** [review]

**Comment by leonard-thieu** [comment]
The type declarations for jsdom are for version 11.0 which [depend on parse5 v3.0.2](https://github.com/jsdom/jsdom/blob/0f4128dabbf155160eceae50a2217572439a631e/package.json#L30). While v4 type declarations may work, I'd recommend verifying that that's the case.

**Comment by andnp** [comment]
Ah, interesting point. It looks like the types for parse5 haven't changed in a way that affects jsdom between v3 and v4.

I wonder how difficult it would be to change the jsdom types version to 11.11

**Comment by leonard-thieu** [comment]
Will also fix #26338.
