### PR TITLE
fix(express-serve-static-core): fix#10910 fixed application use argument does not match parameters

### LINKED ISSUE #12266: Express app.use argument does not match parameters
- [x] I tried using the latest `express-serve-static-core/express-serve-static-core.d.ts` file in this repo and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] I want to talk about `express-serve-static-core/express-serve-static-core.d.ts`.
  - The authors of that type definition are cc/ @borisyankov 

**Problem:** app.use() with normal Express arguments in it throws the IDE error "argument does not match parameters".

Example: 

``` typescript
class Server {
  public app: express.Application;

  public static bootstrap(): Server {
    return new Server();
  }

  constructor() {
    this.app = express();

    this.config();

    this.routes();
  }

  private config() {
    //configure hbs
    this.app.set("views", path.join(__dirname, "views"));
    this.app.set("view engine", "hbs");

    //mount json form parser
    this.app.use(bodyParser.json()); //IDE error

    //mount query string parser
    this.app.use(bodyParser.urlencoded({ extended: true })); //IDE error

    //add static paths
    this.app.use(express.static(path.join(__dirname, "public"))); // IDE error

    // catch 404 and forward to error handler
    this.app.use(function(err: any, req: express.Request, res: express.Response, next: express.NextFunction) {
      var error = new Error("Not Found");
      err.status = 404;
      next(err);
    }); // IDE error
  }

  private routes() {
    //get router
    let router: express.Router;
    router = express.Router();

    //create routes
    var index: indexRoute.Index = new indexRoute.Index();

    //home page
    router.get("/", index.index.bind(index.index));

    //use router middleware
    this.app.use(router); //IDE error
  }
}
```

A workaround is to pass `this.app` to `this.config()` and `this.routers()`

My packages:

``` json
"dependencies": {
    "@types/body-parser": "0.0.33",
    "@types/express": "^4.0.33",
    "@types/express-serve-static-core": "^4.0.37",
    "@types/mime": "0.0.29",
    "@types/node": "^6.0.45",
    "@types/serve-static": "^1.7.31",
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "express-serve-static-core": "^0.1.1",
    "handlebars": "^4.0.5",
    "hbs": "^4.0.1",
    "ts-node": "^1.6.0",
    "tslint": "^3.15.1",
    "typescript": "^2.0.3"
  }
```

I'm using IntelliJ IDEA ultimate 2016.2.5 with the Typescript interpreter from my node_modules folder.

**Update:**
When running it with ts-node, it will work
When compiling it using tsc, it will throw an error: "node_modules/@types/express-serve-static-core/index.d.ts(6,1): error TS6053: File '<truncated>/node_modules/@types/node/node.d.ts' not found.", however changing this to node/index.d.ts did not fix the issue.

### PR DESCRIPTION
**Pull request by serhiisol**
This PR fixes #12266

In few words, application.use causing IDE error

```
Argument types do not match parameters
```

screen shot 2016-12-21 at 11 47 04 am

With fix
screen shot 2016-12-21 at 11 50 01 am

Complete ```tsc``` process executed successfully without errors

### CODE REVIEW

File: express-serve-static-core/index.d.ts [hunk 1]
```diff
@@ -1096,10 +1096,12 @@ interface Application extends IRouter, Express.Application {
      * Used to get all registered routes in Express Application
      */
     _router: any;
+
+    use(RequestHandler): this;
```
Comment (andy-ms) [inline express-serve-static-core/index.d.ts]: Needs an argument name (`foo: RequestHandler`).

Comment (serhiisol) [inline express-serve-static-core/index.d.ts]: yes, I'll update it

Comment (serhiisol) [inline express-serve-static-core/index.d.ts]: I had to change types in IRouter.use to 
```
use: IRouterHandler<this> | IRouterMatcher<this>;
```
instead of 
```
use: IRouterHandler<this> & IRouterMatcher<this>;
```
to have ability to extend it using interfaces, e.g.:
```
use(...handlers: RequestHandlerParams[]): any;
```
