### PR TITLE
[angular] Add Document to JQueryStatic()

### LINKED ISSUE #17529: angular.element() should accept 'document'
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - /cc @borisyankov @leonard-thieu 

Currently code like: `angular.element(document)` throws a compiler error: 

```
Argument of type 'Document' is not assignable to parameter of type 'string | Element'.
  Type 'Document' is not assignable to type 'Element'.
    Property 'classList' is missing in type 'Document'.
```

But this is allowable by AngularJS: https://github.com/angular/angular.js/blob/master/src/jqLite.js#L49

```
> angular.element(document)
Object [ HTMLDocument → forms ]
```

I think the `JQueryStatic` interface needs `| Document` added to its types, but someone else might need to verify.

### PR DESCRIPTION
**Pull request by leonard-thieu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/angular/angular.js/blob/master/src/jqLite.js#L49
- ~~Increase the version number in the header if appropriate.~~
- ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

Fixes #17529

### CODE REVIEW

File: types/angular/jqlite.d.ts [hunk 1]
```diff
@@ -19,6 +20,20 @@
 //                 Dick van den Brink <https://github.com/DickvdBrink>
 //                 Thomas Schulz <https://github.com/King2500>
 //                 Leonard Thieu <https://github.com/leonard-thieu>
+// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
+
+/* *****************************************************************************
```
Comment (paulvanbrenk) [inline types/angular/jqlite.d.ts]: Please remove the copyright header
