### PR TITLE
@types/node: update dns.resolve* declarations

### LINKED ISSUE #11151: dns.resolveSrv callback incorrectly typed
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/03f3ca4333161dea8c5fa0ba47d55b02da92d40d/node/node-0.12.d.ts#L950

``` ts
export function resolveSrv(domain: string, callback: (err: Error, addresses: string[]) =>void ): string[];
```

The callback is typed as `addresses: string[]`, but it's really an array of objects:

```
interface Address {
  priority: number;
  weight: number;
  port: number;
  name: string;
}
```

See https://nodejs.org/api/dns.html#dns_dns_resolvesrv_hostname_callback

cc @danieljy
- [x] I tried using the latest `xxxx/xxxx.d.ts` file in this repo and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ ] I want to talk about `xxxx/xxxx.d.ts`.
  - The authors of that type definition are cc/ @....

### PR DESCRIPTION
**Pull request by ikokostya**
Fixes: #11151

### List of changes

* Change return type of `dns.resolve*` functions: instead of `string[]` return `void`.
* Add signature for `dns.resovle()` with second object parameter.
* Add signatures for `dns.resolve()` with concrete `rrtype` values.
* Add interfaces for records for `resolveSoa(), resolveSrv(), resolveMx(), resolveNaptr()` functions.
* Change type of `error` parameter to `NodeJS.ErrnoException` for all `resolve*` functions.
* Rename parameter `domain` to `hostname` according to documentation.

DNS module documentation: https://nodejs.org/api/dns.html

### Notes

I made changes only for node.js 7 for minimal diff. I will backport changes to node.js 6 and 4 after review.

*** 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/dns.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

### CODE REVIEW

**Comment by ikokostya** [comment]
Looks like CI fail is unrelated.

**Comment by ikokostya** [comment]
Looks like CI fail is unrelated.

File: types/node/index.d.ts [hunk 1]
```diff
@@ -1914,22 +1909,87 @@ declare module "dns" {
...
+    export interface SrvRecord {
+        priority: number;
+        weight: number;
+        port: number;
+        name: string;
+    }
+
+    export function resolve(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolve(hostname: string, rrtype: "A", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolve(hostname: string, rrtype: "AAA", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
```
Comment (Flarna) [inline types/node/index.d.ts]: I think this should be "AAAA" instead of "AAA".

File: types/node/index.d.ts [hunk 2]
```diff
@@ -1914,22 +1909,87 @@ declare module "dns" {
...
+        ttl: boolean;
+    }
+
+    export interface ResolveWithTtlOptions extends ResolveOptions {
+        ttl: true;
+    }
+
+    export interface RecordWithTtl {
+        address: string;
+        ttl: boolean;
```
Comment (Flarna) [inline types/node/index.d.ts]: ttl is of type number in result record

File: types/node/index.d.ts [hunk 3]
```diff
@@ -1914,22 +1909,87 @@ declare module "dns" {
...
+    export function resolve(hostname: string, rrtype: "CNAME", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolve(hostname: string, rrtype: "MX", callback: (err: NodeJS.ErrnoException, addresses: MxRecord[]) => void): void;
+    export function resolve(hostname: string, rrtype: "NAPTR", callback: (err: NodeJS.ErrnoException, addresses: NaptrRecord[]) => void): void;
+    export function resolve(hostname: string, rrtype: "NS", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolve(hostname: string, rrtype: "PTR", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolve(hostname: string, rrtype: "SOA", callback: (err: NodeJS.ErrnoException, addresses: SoaRecord) => void): void;
+    export function resolve(hostname: string, rrtype: "SRV", callback: (err: NodeJS.ErrnoException, addresses: SrvRecord[]) => void): void;
+    export function resolve(hostname: string, rrtype: "TXT", callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
```
Comment (Flarna) [inline types/node/index.d.ts]: addresses should be string[][]

File: types/node/index.d.ts [hunk 4]
```diff
@@ -1914,22 +1909,87 @@ declare module "dns" {
...
+    export function resolveCname(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolveMx(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: MxRecord[]) => void): void;
+    export function resolveNaptr(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: NaptrRecord[]) => void): void;
+    export function resolveNs(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolvePtr(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: string[]) => void): void;
+    export function resolveSoa(hostname: string, callback: (err: NodeJS.ErrnoException, address: SoaRecord) => void): void;
+    export function resolveSrv(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: SrvRecord[]) => void): void;
+    export function resolveTxt(hostname: string, callback: (err: NodeJS.ErrnoException, addresses: string[][]) => void): void;
+
+    export function reverse(ip: string, callback: (err: NodeJS.ErrnoException, domains: string[]) => void): void;
```
Comment (Flarna) [inline types/node/index.d.ts]: from consistency point of view domains should be also renamed to hostnames here.

**Review by Flarna — CHANGES_REQUESTED** [review]
Consider to add some tests for the remaining APIs also.

**Comment by ikokostya** [comment]
> Consider to add some tests for the remaining APIs also.

I think that such tests just repeat declarations. That's why I added only common cases.

File: types/node/index.d.ts (hunk 2 above)
Comment (ikokostya) [inline types/node/index.d.ts]: fixed

File: types/node/index.d.ts (hunk 1 above)
Comment (ikokostya) [inline types/node/index.d.ts]: fixed

File: types/node/index.d.ts (hunk 3 above)
Comment (ikokostya) [inline types/node/index.d.ts]: fixed

File: types/node/index.d.ts (hunk 4 above)
Comment (ikokostya) [inline types/node/index.d.ts]: fixed

**Comment by Flarna** [comment]
Looks fine, thanks!
One more thing you could consider is to define dedicated types for callbacks used at several places (e.a. callback of `resolveMx()` and `resolve(hostname, "MX")` are the same) to avoid copy paste. But this is more a matter of taste, copy paste is also ok.

**Review by Flarna — APPROVED** [review]
