### PR TITLE
[jasmine] Fix return type of `arrayContaining()` and add method for 2.8

### LINKED ISSUE #21305: [@types/jasmine] arrayContaining & arrayWithExactContents wrongly/not typed
## Meta
- Jasmine version: 2.8
- Jasmine Typings version: 2.6.3
- Authors: @borisyankov, @theodorejb, @davidparsson, @gmoothart, @lukas-zech-software 

## `arrayContaining`

`jasmine.arrayContaining` is available, but appears to return a type incompatible to the `equals` method.
```typescript
const a = [1, 2, 3];
expect(a).toEqual(jasmine.arrayContaining([2, 3, 1]));
```
```
Argument of type 'ArrayContaining' is not assignable to parameter of type 'Expected<ArrayLike<number[]>>'. Type 'ArrayContaining' is not assignable to type 'ObjectContaining<ArrayLike<number[]>>'. Property 'jasmineMatches' is missing in type 'ArrayContaining'.
```
Working workaround:
```typescript
const a = [1, 2, 3];
expect(a).toEqual(<any> jasmine.arrayContaining([2, 3, 1]));
```

## `arrayWithExactContents`

`jasmine.arrayWithExactContents` is not available at all according to the typings.

```typescript
const a = [1, 2, 3];
expect(a).toEqual(jasmine.arrayWithExactContents([2, 3, 1]));
```
```
Property 'arrayWithExactContents' does not exist on type 'typeof jasmine'.
```
However, this workaround runs without any problems:
```typescript
const a = [1, 2, 3];
expect(a).toEqual((<any> jasmine).arrayWithExactContents([2, 3, 1]));
```

## Conclusion
Both methods are also documented on [the official Jasmine documentation page](https://jasmine.github.io/api/2.8/jasmine.html). I didn't test the other methods described there, but if they all were added in one batch recently, some of them might be missing or erroneous as well.

The intended way to use these matcher creating functions is not described further or by example, but I assume they are intended to be used as shown above, because the code runs fine (and reports if the array contents don't match) and the first example I found googling it was [this answer on StackOverflow](https://stackoverflow.com/a/39411588/2477364), where `arrayContaining` is used alike.

### PR DESCRIPTION
**Pull request by lukas-zech-software**
Fix return type of `arrayContaining()`

New methods for jasmine 2.8

Add `arrayWithExactContents()`
Add `nothing()`

Fixes #21305

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jasmine/jasmine/releases/tag/v2.8.0
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Comment by lukas-zech-software** [comment]
@borisyankov @theodorejb @davidparsson @gmoothart 

anyone up for a quick review?

File: types/jasmine/index.d.ts [hunk 1]
```diff
@@ -440,14 +441,16 @@ declare namespace jasmine {
...
+
         not: Matchers<T>;
 
         Any: Any;
     }
 
     interface ArrayLikeMatchers<T> extends Matchers<ArrayLike<T>> {
-        toBe(expected: Expected<ArrayLike<T>>, expectationFailOutput?: any): boolean;
-        toEqual(expected: Expected<ArrayLike<T>>, expectationFailOutput?: any): boolean;
+        toBe(expected: Expected<ArrayLike<T>> | ArrayContaining<T>, expectationFailOutput?: any): boolean;
```
Comment (gmoothart) [inline types/jasmine/index.d.ts]: `Expected<ArrayLike<T> | ArrayContaining<T>>` ?

File: types/jasmine/jasmine-tests.ts [hunk 2]
```diff
@@ -777,6 +783,30 @@ describe("jasmine.arrayContaining", () => {
...
+describe("jasmine.arrayWithExactContents", () => {
+    var foo: Array<number>;
+
+    beforeEach(() => {
+        foo = [1, 2, 3, 4];
+    });
+
+    it("matches arrays with exactly the same values", () => {
+        expect(foo).toEqual(jasmine.arrayWithExactContents([1, 2, 3, 4]));
+        expect(foo).not.toEqual(jasmine.arrayWithExactContents([6]));
```
Comment (gmoothart) [inline types/jasmine/jasmine-tests.ts]: Add lines for `.toBe` too.

**Review by gmoothart — APPROVED** [review]

File: types/jasmine/index.d.ts (hunk 1 above)
Comment (lukas-zech-software) [reply types/jasmine/index.d.ts]: as mentioned in the linked issue #21305 the `ArrayLikeMatchers` did not accept the type returned by `jasmine. arrayContaining()`

because of that I added the `ArrayContaining<T>` type

File: types/jasmine/jasmine-tests.ts (hunk 2 above)
Comment (lukas-zech-software) [reply types/jasmine/jasmine-tests.ts]: added `.toBe` to `jasmine.arrayWithExactContents` and `jasmine. arrayContaining `
