### PR TITLE
[bootstrap-select] Add BootstrapVersion property

### LINKED ISSUE #55074: [@types/bootstrap-select] BootstrapVersion property is not available
### Discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55073

<div type='discussions-op-text'>

<sup>Originally posted by **dehy** August 11, 2021</sup>
Hello there 👋 (oh, hello Github Discussions)

I'm using a special version of Bootstrap v4 that makes the bootstrap-select's BootstrapVersion auto-discovery non available. [Official Docs](https://developer.snapappointments.com/bootstrap-select/options/) says that we can manually override the version used by setting `$.fn.selectpicker.Constructor.BootstrapVersion`.

Unfortunately, tsc complains about `Constructor`:

My line:
```javascript
$.fn.selectpicker.Constructor.BootstrapVersion = '4';
```

The error:
```
[tsl] ERROR in /path/to/app/assets/js/app.ts(20,19)
      TS2339: Property 'Constructor' does not exist on type '{ (opts?: BootstrapSelectOptions | undefined):JQuery<HTMLElement>; (method: MethodType, ...args: (string | string[])[]): JQuery<...>; }'.
```

I'm not expert enough to understand what to update in the definition file.

Versions:
- tsc: 3.9.5
- webpack: 4.43.0

Ping Authors: @LKay @AlexTruba 

Thank you for your work!</div>

### PR DESCRIPTION
**Pull request by martin-badin**
Closes: #55074

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developer.snapappointments.com/bootstrap-select/options/>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

File: types/bootstrap-select/index.d.ts [hunk 1]
```diff
@@ -8,42 +8,90 @@
...
-    sanitizeFn?: ((unsafeElements: Array<HTMLElement | ChildNode | Node>) => void) | undefined;
-    size?: 'auto' | number | boolean | undefined;
-    style?: string | undefined;
-    styleBase?: string | undefined;
-    tickIcon?: string | undefined;
-    title?: string | undefined;
-    virtualScroll?: boolean | number | undefined;
-    width?: string | boolean | undefined;
-    windowPadding?: number | number[] | undefined;
+    actionsBox: boolean;
```
Comment (AlexTruba) [inline types/bootstrap-select/index.d.ts:11]: These interfaces have almost the same structure. It would be better to extract properties, which exists in `BootstrapSelectOptions` and `BootstrapSelectDefaults`, into base type/interface.

**Review by AlexTruba — CHANGES_REQUESTED** [review]
Please look at this proposition https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55075#discussion_r686677419

**Review by AlexTruba — APPROVED** [review]

**Comment by AlexTruba** [comment]
Ready to merge
