### PR TITLE
[redux-actions] fix incorrect return type for combineActions()

### LINKED ISSUE #18148: [redux-actions] Bad return type for combineActions
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jaysoo, @alexgorbatchev

`combineActions` returns a string, not an array. The current typing prevents it from being used as a computed property for `handleActions`.

### PR DESCRIPTION
**Pull request by BendingBender**
Fixes #18148.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://redux-actions.js.org/docs/api/combineActions.html
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/redux-actions/redux-actions-tests.ts [hunk 1]
```diff
@@ -136,6 +136,10 @@ ReduxActions.handleAction(act3, (state, action) => {
 
 ReduxActions.handleAction(ReduxActions.combineActions(act1, act3, act2), (state, action) => {}, 0);
 
+ReduxActions.handleActions({
+    [<string> ReduxActions.combineActions(act1, act3, act2)](state, action) {}
```
Comment (andy-ms) [inline types/redux-actions/redux-actions-tests.ts]: It shouldn't need a cast then, right?

**Comment by andy-ms** [comment]
Thanks!
