### PR TITLE
Fix a number of gaps in Ember's types

### LINKED ISSUE #36809: @types/ember__utils typeOf missing 'object'
`typeOf` checks that valid return types are keys of this interface: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ae6aa49a5f62ee00ced651389e7941ea19881af4/types/ember__utils/-private/types.d.ts#L5

However this is missing `'object'` as allowed here: http://api.emberjs.com/ember/3.10/functions/@ember%2Futils/typeOf

### LINKED ISSUE #38681: @types/ember incorrectly disallows null/undefined being passed to assign
The polyfill for assign incorrectly errors when assigning a non-object:

```ts
import { assign } from '@ember/polyfills';

const a = {};
const b = null;
const c = undefined;

assign(a, b); // should be valid, throws TS error
assign(a, c); // should be valid, throws TS error
```

Note that Ember's assign polyfill works correctly and Object.assign has the same behavior:

> Note that Object.assign() does not throw on null or undefined source values.
[Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

### LINKED ISSUE #38682: @types/ember missing import deprecate in @ember/debug
Expected the following to work:

```ts
import { deprecate } from '@ember/debug';
```

but this import location is missing and only the deprecated import below is available:

```ts
import { deprecate } from '@ember/application/deprecations';
```

### PR DESCRIPTION
**Pull request by chriskrycho**
- Fixes #38681
- Fixes #36809 (and typed-ember/ember-cli-typescript#799)
- Fixes #38682

An important note for reviewers: the formatting changes here were unavoidable—DT's precommit hooks now enforce formatting.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
    - <http://api.emberjs.com/ember/3.10/functions/@ember%2Futils/typeOf>
    - <https://api.emberjs.com/ember/3.12/functions/@ember%2Fpolyfills/assign> (polyfill for [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign))
    - <https://api.emberjs.com/ember/3.12/functions/@ember%2Fdebug/deprecate>

### CODE REVIEW

File: types/ember__utils/-private/types.d.ts [hunk 1]
```diff
@@ -2,6 +2,13 @@ export type KeysOfType<Base, Condition> = keyof Pick<Base, {
     [Key in keyof Base]: Base[Key] extends Condition ? Key : never
 }[keyof Base]>;
 
+// Since `TypeLookup` resolves all *other* types, including `null` and
+// `undefined`, we can assume that if the type does *not* resolve from
+// `KeysOfType`, it is safe to treat it as 'object'.
+export type TypeOf<Base, Condition> = KeysOfType<Base, Condition> extends never
```
Comment (chriskrycho) [inline types/ember__utils/-private/types.d.ts]: Note that this may have a small performance impact. The performance tests indicate it's small (as I would expect), but it's something to keep an eye on.

Comment (chriskrycho) [reply types/ember__utils/-private/types.d.ts]: This *should* be compatible with the extension in `@ember/object`, since that works by extending the `TypeLookup` interface.

**Comment by chriskrycho** [comment]
Test infra seems to be confused – it's reporting git changes to files this PR *definitely* does not affect. @uniqueiniquity, any idea what's up here?

**Comment by uniqueiniquity** [comment]
@chriskrycho don't worry about travis - we're in the process of removing it, so as long as the Azure Pipelines check passes, you should be good to go.

**Comment by chriskrycho** [comment]
Very good—thanks!

**Comment by igbopie** [comment]
Thanks @RyanCavanaugh & @chriskrycho !!
