### PR TITLE
[lodash] add array destructure overload for _.zipWith fixes #21884

### LINKED ISSUE #21884: _.zipWith in `@types/lodash@4.14.86` not work
I tried using the `@types/lodash` package and had problems.

It's not work in `@types/lodash@4.14.86`:
```
const fakeValueArray = [
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
  ];
const totalValueArray = _.zipWith(...fakeValueArray, (...args: number[]): number => _.sum(args));
// totalValueArray =>  [6, 15, 24]
```
> TS2345:Argument of type '(...args: number[]) => number' is not assignable to parameter of type 'ArrayLike<number>'.
  Index signature is missing in type '(...args: number[]) => number'.

But it's work in older `@types/lodash@4.14.77`.

I saw the definition of `_.zipWith` but still confused.

### PR DESCRIPTION
**Pull request by andnp**
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [source code](https://github.com/lodash/lodash/blob/master/zipWith.js)
- [x] Increase the version number in the header if appropriate.

This fixes #21884 by having a base case for the overloaded method. It seems the base case was added to the 5 argument overload, but that meant specifying 5 arrays before being able to use the array destructuring. Added a relevant test case as well.

Side note: how do I "increase the version number in the header"? This should just be a patch bump (which is automatically done for me, I believe), but in the case that I wanted to make this a minor bump how would I go about it?

### CODE REVIEW

**Review by aj-r — APPROVED** [review]
Don't worry about increasing the version number in the header. DT will automatically increase the revision number, and you shouldn't change the major/minor version because they need to match lodash.

File: types/lodash/index.d.ts [hunk 1]
```diff
@@ -3954,6 +3954,10 @@ declare namespace _ {
             arrays3: List<T> | null | undefined,
             arrays4: List<T> | null | undefined,
             arrays5: List<T> | null | undefined,
+            iteratee: (value1: T, value2: T, value3: T, value4: T, value5: T) => TResult
+        ): TResult[];
+
+        zipWith<T, TResult>(
```
Comment (minestarks) [inline types/lodash/index.d.ts]: This last overload weakens all the type checking provided by the specific overloads above. For example, things like this become legal, when they would have been errors before.

```ts
zipWith(null)
zipWith((something) => {}, undefined, (randomfunction) => 3)
zipWith(list1, list2) // no iteratee parameter
zipWith(list1, list2, (a,b,c) => 3) // wrong number of parameters on iteratee
```

Unfortunately I can't think of a better solution to your problem, but I don't think this is a good change.

**Review by minestarks — CHANGES_REQUESTED** [review]

File: types/lodash/index.d.ts (hunk 1 above)
Comment (andnp) [reply types/lodash/index.d.ts]: Unfortunately, without a change we break a significant number of use cases within lodash. With typescript not having a proper way to provide strong typings for variadic tuples, I would rather err on the side of weak types that do not limit the usability specified within lodash's documentation. If the user does not know the number of arrays at compile time but wants to use an iteratee, they currently cannot without using `as any` everywhere.

Additionally, all of your examples are actually valid uses of `zipWith` except for the second where there are two iteratee functions. 

Common usages that aren't currently possible via these typings:
```ts
zipWith([1, 2], null, ['a', 'b'])
zipWith(...arrayOfArrays)
```

I guess a lot of this comes down to: I don't want to tell the user they can't use lodash a certain way because I want to lock down every aspect of the type safety.

Comment (minestarks) [reply types/lodash/index.d.ts]: I see what you're saying. (BTW is my last example also valid? I thought there might be an issue with having the wrong number of parameters on iteratee).

I'm sympathetic to this change, but I'd like to give it some time in case the authors / other users of lodash want to review.

Comment (andnp) [reply types/lodash/index.d.ts]: Technically it would be valid, you can always provide a lambda with extra parameters, the extras will just be `undefined`. Though clearly if we can find a way to enforce that the first `n - 1` parameters are of type `Array<{} | null | undefined>` and the `n`th parameter is a function with the correct number of arguments, that would be preferable. Unfortunately, lodash wasn't really written with type safety in mind, it was written to be as permissive as possible. Our typings within DefinitelyTyped should support that decision, and leave it up to lodash (hopefully v5) to enforce some type safe practices.

**Review by minestarks — APPROVED** [review]
