### PR TITLE
[http-errors] don't return never from HttpError constructor

### LINKED ISSUE #19458: [http-errors] instanceof HttpError non-functional
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkrotoff, @BendingBender 

In TypeScript, `instanceof HttpError` fails since `HttpError` is declared as an interface and not a class. I want to do something similar to this:

```js
app.use((err, req, res, next) => {
  if (err instanceof HttpError) {
    // give user nice error
  } else {
    // send generic 500 error
  }
})
```

The javascript in itself is working, but TypeScript is casting the `err` inside of the first conditional branch as `never`.

I tried correcting this by changing `interface HttpError extends Error` to `class HttpError extends Error`, but that caused a few other error to pop up and I think that I'll need some guidance on how to best fix this.

Thank you!

### PR DESCRIPTION
**Pull request by BendingBender**
Fixes #19458.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jshttp/http-errors
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

**Review by tkrotoff — APPROVED** [review]

File: types/http-errors/http-errors-tests.ts [hunk 1]
```diff
@@ -91,9 +87,16 @@ err = new create[404]('This might be a problem');
 err = new create.MisdirectedRequest();
 err = new create.MisdirectedRequest('Where should this go?');
 
+// $ExpectType HttpError
+new create.HttpError();
+
 // $ExpectType boolean
 new Error() instanceof create.HttpError;
```
Comment (LinusU) [inline types/http-errors/http-errors-tests.ts]: `err` is already a `HttpError` here, I'm not sure if it matters but we could potentially do something like:

```typescript
const genericError = new Error('test')

if (genericError instanceof create.HttpError) {
  genericError.statusCode
}
```

**Comment by LinusU** [comment]
Thank you ❤️
