### PR TITLE
fix(webpack): correct Stats class details

### LINKED ISSUE #43952: [@types/webpack] TS error when importing Stats class from Webpack package.
If you know how to fix the issue, make a pull request instead.

- [✅] I tried using the `@types/webpack` package and had problems.
- [✅] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [❌] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [✅] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @tkqubo, @bumbleblym, @bcherny, @tommytroylin, @mohsen1, @jcreamer898, @alan-agius4, @elliottsj, @jason0x43, @dennispg, @christophehurpeau, @ZSkycat, @johnnyreilly, @rwaskiewicz, @kuehlein, @grgur, @rubenspgcavalcante, @andersk, @ofhouse, @danielthank, @sasurau4, @dionshihk 

If you do not mention the authors the issue will be ignored. ***(<- sorry guys... I am seeking no troubles, I promise! Nice to meet you all.)***

([Original Issue](https://github.com/webpack/webpack/issues/10711))

**What is the current behavior?**

```js
import {Stats} from 'webpack';

/* [...] */

const stats = new Stats(compilation);
```

TypeScript throws: ***"TS2511: Cannot create an instance of an abstract class."***

Could it be a problem with Webpack's `index.d.ts` file? Stats class is marked as abstract.

***NOTE:*** I only use TypeScript for type checking and declaration files generation for JS files with JSDoc annotations. So I am really not very familiar with TypeScript syntax. Maybe there is something that I'm missing.

**Other relevant information:**
webpack version: 4.42.1
Node.js version: 13.12.0
Operating System: macOS Catalina 10.15.3
Additional tools: N/A

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- remove abstract keyword for Stats class
- add constructor with options
- add class and instance methods
- update tests

https://github.com/webpack/webpack/blob/71eb5931dbd7db125109a95692065333cea936a9/lib/Stats.js

/cc @ernestostifano

Thanks!

Fixes #43952

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

File: types/webpack/index.d.ts [hunk 1]
```diff
@@ -1409,20 +1410,30 @@ declare namespace webpack {
...
     }
 
-    abstract class Stats {
+    class Stats {
         compilation: compilation.Compilation;
         hash?: string;
         startTime?: number;
         endTime?: number;
+
+        static filterWarnings(warnings: string[], warningsFilter?: (warning: string) => boolean): string[];
```
Comment (ofhouse) [inline types/webpack/index.d.ts:1419]: I think the type of `warningsFilter` is more complex.
Looking at the code it seems that the filter is always an array which can be a string, RegEx or a custom function: https://github.com/webpack/webpack/blob/v4.42.1/lib/Stats.js#L37
This also aligns with the types from the v5 docs: https://webpack.js.org/configuration/stats/#statswarningsfilter

```suggestion
        static filterWarnings(
          warnings: string[],
          warningsFilter?: Array<string | RegExp | ((warning: string) => boolean)>
        ): string[];
```

File: types/webpack/test/index.ts [hunk 2]
```diff
@@ -1166,3 +1166,14 @@ class LoggingPlugin extends webpack.Plugin {
         });
     }
 }
+
+// Stats Microsoft/DefinitelyTyped#43952
+import { Stats } from 'webpack';
```
Comment (ofhouse) [inline types/webpack/test/index.ts:1171]: IMHO not a big fan of imports in the middle of the file, because we already have a general import of the whole module at the top:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/abe7571daf1b1b864cd6d1790670f1c910d1ea34/types/webpack/test/index.ts#L1

I think it would be better to destruct the `webpack` import here which has the same effect:

```suggestion
const { Stats } = webpack;
```

**Review by ofhouse — CHANGES_REQUESTED** [review]
Thanks for taking the time for fixing the issue :+1: 
I have two comments which should be adressed before we can merge it.

**Comment by peterblazejewicz** [comment]
@ofhouse thx! Amended with your suggested changes!

**Review by ofhouse — APPROVED** [review]
Thanks for fixing the issues 💪 

We are good to go now 🚀
