### PR TITLE
Zip different types

### LINKED ISSUE #23221: [lodash] `zip` and `zipWith` do not allow arrays of different types
- [X] I tried using the `@types/lodash@4.14.96` package and had problems.
- [X] I tried using the `2.6.2` version of tsc.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @bczengel, @chrootsu, @stepancar, @ericanderson, @aj-r, @ailrun, @e-cloud, @thorn0, @jtmthf, @DomiR

`_.zip` and `_.zipWith` do not allow arrays of different types.

Example:
```ts
_.zip(['a', 'b'], [1, 2], [true, false]);
_.zipWith(['a', 'b'], [1, 2], [true, false], (a, b, c) => ({ a, b, c }))
```

Error:
```
[ts]
Argument of type 'string[]' is not assignable to parameter of type 'ArrayLike<number> | ((...group: number[]) => {}) | null | undefined'.
  Type 'string[]' is not assignable to type '(...group: number[]) => {}'.
    Type 'string[]' provides no match for the signature '(...group: number[]): {}'.
```

Reference:
- [zip](https://lodash.com/docs/4.17.4#zip)
- [zipWith](https://lodash.com/docs/4.17.4#zipWith)

### PR DESCRIPTION
**Pull request by aj-r**
Fixes #23221.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.4#zip, https://lodash.com/docs/4.17.4#zipWith
- [ ] Increase the version number in the header if appropriate. N/A
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/lodash/array/zipWith.d.ts [hunk 1]
```diff
@@ -10,60 +10,56 @@ declare module "../index" {
          * @param [thisArg] The `this` binding of `iteratee`.
          * @return Returns the new array of grouped elements.
          */
-        zipWith<T>(
```
Comment (aj-r) [inline types/lodash/array/zipWith.d.ts]: This overload is redundant with the last one, so I remove it. Plus there's no point in calling `zipWith` without an iteratee - in that case you should call `zip` instead.

File: types/lodash/lodash-tests.ts [hunk 2]
```diff
@@ -3359,18 +3367,9 @@ namespace TestZipObject {
 }
 
 // _.zipWith
-namespace TestZipWith {
+{
     type TestZipWithFn = (a1: number, a2: number) => number;
 
-    {
-        let result: number[][];
-        result = _.zipWith([1, 2]);
```
Comment (aj-r) [inline types/lodash/lodash-tests.ts]: Some of these tests fail due to my changes. However, as stated earlier, there's no point in calling `zipWith` without an iteratee - in that case you should call `zip` instead.

**Review by andnp — APPROVED** [review]
