### PR TITLE
[plotly.js] Config.setBackground function needs parentheses (fix #60184)

### LINKED ISSUE #60184: [@types/plotly.js] Config.setBackground type definition appears to be missing parentheses
I'm not sure how these were generated (automatically, I presume) or to whom I should mention this (@Domino987 @chrisgervang ?), but I noticed that there seems to be missing parentheses around the function form in the union type for `Config.setBackground` :
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed7f7400fea8c9f286c24318dc615c523e5c4045/types/plotly.js/index.d.ts#L1587

```ts
//const broken: Pick<Config, 'setBackground'> = {
const broken: { setBackground: () => string | 'opaque' | 'transparent' } = {
  // Note () => string | 'opaque' | 'transparent' reduces to '() => string'
  setBackground: 'transparent', // TS2322: Type 'string' is not assignable to type '() => string'.
};
const fixed: { setBackground: (() => string) | 'opaque' | 'transparent' } = {
  setBackground: 'transparent', // OK!
};
// Flipping the order of these things gives a good clue:
// TS1385: Function type notation must be parenthesized when used in a union type.
type warning = { setBackground: 'opaque' | 'transparent' | () => string }; 
```

Given that the default value for this option is a (pre-defined/enum) string rather than a function that returns a string I think this type definition is a mistake. Am I wrong?
https://github.com/plotly/plotly.js/blob/3f6c0eba637dc5829a96d6bb768d1f78e61e30e0/src/plot_api/plot_config.js#L353-L363
(even in [v1.58](https://github.com/plotly/plotly.js/blob/v1.58.5/src/plot_api/plot_config.js#L346-L356))
(Related to https://github.com/plotly/plotly.js/issues/28)

### PR DESCRIPTION
**Pull request by jacobq**
See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60184

`() => string | 'transparent' | 'opaque'` reduces to `() => string` unless parentheses are used
(note that moving `() => string` to the end of the union type leads to "TS1385: Function type notation must be parenthesized when used in a union type.")

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60184
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Comment by DangerBotOSS** [comment]
Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## plotly.js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/plotly.js@latest/))
was missing the following properties:
1. version
1. register
1. Icons
1. Fx
1. Snapshot

<details>
<summary>as well as these 2 other properties...</summary>
<p>PlotSchema, Queue</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eb0613325ff51303e206d5dc17311c40e91b54db
</p>

**Review by brammitch — APPROVED** [review]
LGTM.

**Comment by brammitch** [comment]
Thanks for the write up of your through process behind this PR and for the example you provided on [CodePen](https://codepen.io/jacobq_/pen/VwQLdWZ?editors=0010).

File: types/plotly.js/index.d.ts [hunk 1]
```diff
@@ -1584,7 +1584,7 @@ export interface Config {
      * function to add the background color to a different container
      * or 'opaque' to ensure there's white behind it
      */
-    setBackground: () => string | 'opaque' | 'transparent';
+    setBackground: ((gd: PlotlyHTMLElement, bgColor: string) => any) | 'opaque' | 'transparent';
```
Comment (peterblazejewicz) [inline types/plotly.js/index.d.ts:1587]:
```suggestion
    setBackground: ((gd: PlotlyHTMLElement, bgColor: string) => void) | 'opaque' | 'transparent';
```
any particular reason to have this working differently compared to underlying functions?
https://github.com/plotly/plotly.js/blob/12069023b46b4583259a7cfba295e1e653c15266/src/plot_api/plot_api.js#L412-L423

Comment (jacobq) [reply types/plotly.js/index.d.ts:1587]: Nope, nothing except my own ignorance & fear of causing breakage. The previous type def made it look to me like the function was expected to return a string, but in fact it doesn't have to (and looks like the return value isn't used at all) so I was broadening to `any`, but on second thought that could be misleading. If someone can easily change then feel free. Otherwise I will update this PR later when I'm at home (where I have the full repo cloned and don't have to justify the time to my employer :D)

**Review by peterblazejewicz — APPROVED** [review]

**Comment by jacobq** [comment]
> Ready to merge

Ready to merge
