### PR TITLE
[npmlog] Fix incorrect exports

### LINKED ISSUE #27296: @types/npmlog does not work
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/npmlog` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @DanielMSchmidt

If you do not mention the authors the issue will be ignored.

According [`npmlog`'s doc](https://github.com/npm/npmlog#readme), `npmlog` is not using ES6-style export, so #25291 is invalid.

This should be the actual one:
```typescript
import * as npmlog from "npmlog";
```

But `@types/npmlog` exports things for this:
```typescript
import npmlog from "npmlog";
```

### PR DESCRIPTION
**Pull request by ghost**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/npm/npmlog/blob/master/README.md#basic-usage>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

> ~~Add or edit tests to reflect the change. (Run with `npm test`.)~~

~~I've runned `npm test` serveral time, but I always get one of these error messges.~~

- ~~`Error: ENOENT: no such file or directory, stat 'xxx'`~~
- ~~`Error: ENOENT: no such file or directory, open 'xxx'`~~
- ~~`Error: Cannot find module 'xxx'`~~

~~Is there any way to address them?~~

**Edit:** CI check passed. It's just a problem on my computer.

---

Fixes #27296

### CODE REVIEW

**Review by DanielMSchmidt — APPROVED** [review]

File: types/npmlog/npmlog-tests.ts [hunk 1]
```diff
@@ -12,7 +12,8 @@ npmlog.http(prefix, message);
 npmlog.warn(prefix, message);
 npmlog.error(prefix, message);
 
-npmlog.level = "silly";
+// ES6 module does't support changing variable exported by `export let`
```
Comment (weswigham) [inline types/npmlog/npmlog-tests.ts]: You can write an import of the style `import npmlog = require("npmlog")` if you want to test this in the future.
