### PR TITLE
using official @hapi/podium typings

### LINKED ISSUE #52135: [@types/hapi__hapi] Needs to be updated bc of Podium breaking changes
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [ x ] I tried using the `@types/xxxx` package and had problems.
- [ x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ x ] I understand that `@types` package versions [do not follow SemVer](https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library).
- [ x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [ x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @rafaelsouzaf , @jhsimms , @SimonSchick , @saboya , @lenovouser

If you do not mention the authors the issue will be ignored.

### The problem
Podium release [4.1.2](https://www.npmjs.com/package/@hapi/podium) breaks this module:

```sh

node_modules/@types/hapi__hapi/index.d.ts:260:18 - error TS2430: Interface 'RequestEvents' incorrectly extends interface 'Podium'.
  Types of property 'on' are incompatible.
    Type '{ (criteria: "peek", listener: PeekListener): void; (criteria: "finish" | "disconnect", listener: (data: undefined) => void): void; }' is not assignable to type '<Tcontext extends object = this>(criteria: string | CriteriaObject, listener: Listener<Tcontext>, context?: Tcontext | undefined) => this'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Types of parameters 'tags' and 'encoding' are incompatible.
          Type 'string' is not assignable to type '{ [tag: string]: true | undefined; } | undefined'.

260 export interface RequestEvents extends Podium {
                     ~~~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:633:18 - error TS2430: Interface 'ResponseEvents' incorrectly extends interface 'Podium'.
  Types of property 'on' are incompatible.
    Type '{ (criteria: "peek", listener: PeekListener): void; (criteria: "finish", listener: (data: undefined) => void): void; }' is not assignable to type '<Tcontext extends object = this>(criteria: string | CriteriaObject, listener: Listener<Tcontext>, context?: Tcontext | undefined) => this'.
      Types of parameters 'listener' and 'listener' are incompatible.
        Types of parameters 'tags' and 'encoding' are incompatible.
          Type 'string' is not assignable to type '{ [tag: string]: true | undefined; } | undefined'.

633 export interface ResponseEvents extends Podium {
                     ~~~~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:2363:43 - error TS2314: Generic type 'Listener' requires 1 type argument(s).

2363     removeListener(criteria: K, listener: Podium.Listener): this;
                                               ~~~~~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:2381:18 - error TS2430: Interface 'ServerEvents' incorrectly extends interface 'Podium'.
  The types returned by 'on(...)' are incompatible between these types.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

2381 export interface ServerEvents extends Podium {
                      ~~~~~~~~~~~~

node_modules/@types/hapi__hapi/index.d.ts:2447:44 - error TS2314: Generic type 'Listener' requires 1 type argument(s).

2447     removeListener(name: string, listener: Podium.Listener): Podium;
           
```

### PR DESCRIPTION
**Pull request by saboya**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hapijs/podium/blob/master/lib/index.d.ts
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

Depends on https://github.com/microsoft/DefinitelyTyped-tools/pull/236

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52135#issuecomment-819547279

### CODE REVIEW

File: types/hapi__hapi/index.d.ts [hunk 1]
```diff
@@ -257,7 +257,7 @@ export type RequestEventType = 'peek' | 'finish' | 'disconnect';
  * * 'disconnect' - emitted when a request errors or aborts unexpectedly.
  * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-requestevents)
  */
-export interface RequestEvents extends Podium {
+export class RequestEvents extends Podium {
```
Comment (SimonSchick) [inline types/hapi__hapi/index.d.ts:260]: This seems incorrect, this being a class implies it would be instantiable eg. be a real type vs. a virtual one, this is not the case, this should stay an interface.

File: types/hapi__hapi/index.d.ts [hunk 2]
```diff
@@ -2380,7 +2382,7 @@ export interface PodiumEvent<K extends string, T> {
  * Other methods include: server.events.removeListener(name, listener), server.events.removeAllListeners(name), and server.events.hasListeners(name).
  * [See docs](https://github.com/hapijs/hapi/blob/master/API.md#-serverevents)
  */
-export interface ServerEvents extends Podium {
+export class ServerEvents extends Podium {
```
Comment (SimonSchick) [inline types/hapi__hapi/index.d.ts:2385]: See above.

File: types/hapi__hapi/index.d.ts [hunk 3]
```diff
@@ -630,22 +631,23 @@ export interface Request extends Podium {
  * * 'finish' - emitted when the response finished writing but before the client response connection is ended. The event method signature is function ().
  * [See docs](https://hapijs.com/api/17.0.1#-responseevents)
  */
-export interface ResponseEvents extends Podium {
+export class ResponseEvents extends Podium {
```
Comment (SimonSchick) [inline types/hapi__hapi/index.d.ts:634]: See above.

**Review by SimonSchick — CHANGES_REQUESTED** [review]

File: types/hapi__hapi/index.d.ts (hunk 1 above)
Comment (saboya) [reply types/hapi__hapi/index.d.ts]: You´re right, I corrected it.

**Comment by ipatton-variant** [comment]
+1 LGTM

**Review by SimonSchick — APPROVED** [review]

**Comment by orta** [comment]
Thanks 👍🏻
