### PR TITLE
fix(node): improve typing of `assert.strict`

### LINKED ISSUE #48253: `@types/node`: `assert.strict.equal` should not be deprecated
- [ ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Flarna, @SimonSchick, @Semigradsky, @rbuckton, @mjbvz, @G-Rath, @sandersn 

* `assert.strict.equal` should not be deprecated: https://nodejs.org/dist/latest-v14.x/docs/api/assert.html#assert_assert_equal_actual_expected_message
* The problem is that `assert.strict` uses `typeof assert` here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/assert.d.ts

definitely typed assert bug

### PR DESCRIPTION
**Pull request by G-Rath**
Fixes #48253
Supersedes #48351

/cc @Semigradsky @Flarna

### CODE REVIEW

**Comment by G-Rath** [comment]
Wow, ok I don't know how I managed to mess that one up: `strict.strict` is a valid thing at runtime 🤔

Will have a further playaround, and keep this PR open for now.

File: types/node/assert.d.ts [hunk 1]
```diff
@@ -77,7 +77,28 @@ declare module "assert" {
         function match(value: string, regExp: RegExp, message?: string | Error): void;
         function doesNotMatch(value: string, regExp: RegExp, message?: string | Error): void;
 
-        const strict: typeof assert;
+        const strict: Omit<
```
Comment (ExE-Boss) [inline types/node/assert.d.ts:80]: `Omit` doesn’t preserve callability.

File: types/node/assert.d.ts [hunk 2]
```diff
@@ -77,7 +77,28 @@ declare module "assert" {
...
+            typeof assert,
+            | 'strict'
+            | 'deepEqual'
+            | 'notDeepEqual'
+            | 'equal'
+            | 'notEqual'
+            | 'ok'
+            | 'strictEqual'
+            | 'deepStrictEqual'
+            | 'ifError'
```
Comment (ExE-Boss) [inline types/node/assert.d.ts:90]: Only `deepEqual`, `notDeepEqual`, `equal` and `notEqual` are replaced: <https://github.com/nodejs/node/blob/e9639ee7e8705516e3b4b9ba7ee19d8e210afa9a/lib/assert.js#L934-L944>

```suggestion
            | 'deepEqual'
            | 'notDeepEqual'
            | 'equal'
            | 'notEqual'
```

File: types/node/assert.d.ts [hunk 3]
```diff
@@ -77,7 +77,28 @@ declare module "assert" {
...
+        > & {
+            strict: typeof strict;
+            deepEqual: typeof deepStrictEqual;
+            notDeepEqual: typeof notDeepStrictEqual;
+            equal: typeof strictEqual;
+            notEqual: typeof notStrictEqual;
+            ok(value: any, message?: string | Error): asserts value;
+            strictEqual<T>(actual: any, expected: T, message?: string | Error): asserts actual is T;
+            deepStrictEqual<T>(actual: any, expected: T, message?: string | Error): asserts actual is T;
+            ifError(value: any): asserts value is null | undefined;
```
Comment (ExE-Boss) [inline types/node/assert.d.ts:100]:
```suggestion
            deepEqual: typeof deepStrictEqual;
            notDeepEqual: typeof notDeepStrictEqual;
            equal: typeof strictEqual;
            notEqual: typeof notStrictEqual;
```

**Review by ExE-Boss — CHANGES_REQUESTED** [review]

File: types/node/assert.d.ts (hunk 2 above)
Comment (G-Rath) [reply types/node/assert.d.ts:90]: You have to do this to preserve the `asserts`, otherwise you'll get `Assertions require every name in the call target to be declared with an explicit type annotation`

File: types/node/assert.d.ts (hunk 3 above)
Comment (G-Rath) [reply types/node/assert.d.ts:100]: You have to do this to preserve the `asserts`, otherwise you'll get `Assertions require every name in the call target to be declared with an explicit type annotation`

File: types/node/assert.d.ts (hunk 1 above)
Comment (G-Rath) [reply types/node/assert.d.ts:80]: Good catch - need to add `(value: any, message?: string | Error): asserts value`; I'll do that plus add a test to catch it in the future.

**Comment by G-Rath** [comment]
@ExE-Boss I've added the missing callable signature to the type, but not removed the omitting/redefining of the `asserts` functions as their there for the same reason the callable signature has to be: mapped types don’t preserve assertability :)

**Review by rbuckton — APPROVED** [review]

**Comment by G-Rath** [comment]
Ready to merge
