### PR TITLE
[webpack-env] make __WebpackModuleApi.Module compatible with NodeJS.Module

### LINKED ISSUE #47602: [@types/node] error TS2430: Interface 'NodeJS.Module' incorrectly extends interface '__WebpackModuleApi.Module'.
- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for Gitter.
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @jkomyno @a-tarasyuk @alvis @r3nya @btoueg @brunoscheufler @smac89 @touffy @DeividasBakanas @eyqs @Flarna

```bash
node_modules/@types/node/ts3.1/globals.d.ts:573:15 - error TS2430: Interface 'NodeJS.Module' incorrectly extends interface '__WebpackModuleApi.Module'.
  Types of property 'parent' are incompatible.
    Type 'Module | null | undefined' is not assignable to type 'NodeModule | null'.
      Type 'undefined' is not assignable to type 'NodeModule | null'.

573     interface Module {
                  ~~~~~~
```

### PR DESCRIPTION
**Pull request by jamescdavis**
A [recent update](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47485) to `node` types made `__WebpackModuleApi.Module` incompatible with `NodeJS.Module`. Importing the node types in the test reveals this issue and ensures compatibility.

- Fixes #47602
- Closes #47607

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47485
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

### CODE REVIEW

File: types/webpack-env/index.d.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ declare namespace __WebpackModuleApi {
         id: string;
         filename: string;
         loaded: boolean;
-        parent: NodeModule | null;
+        parent: NodeModule | null | undefined;
```
Comment (jamescdavis) [inline types/webpack-env/index.d.ts:71]: I could have used
```suggestion
        parent?: NodeModule | null;
```
of course, but I was going for exact parity with the node types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1c2240f6cecbe84f5a5e257bdcef76709a57257b/types/node/ts3.1/globals.d.ts#L580

**Comment by jamescdavis** [comment]
I'm assuming the perf change is due to the import of the node types.

File: types/webpack-env/webpack-env-tests.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-
+import 'node';
```
Comment (ExE-Boss) [inline types/webpack-env/webpack-env-tests.ts:1]:
```suggestion
/// <reference types="node"/>
```

**Review by ExE-Boss — APPROVED** [review]

**Comment by dep-dt** [comment]
How can I get these `@typescript-bot` magical updates in my own project?

**Comment by ExE-Boss** [comment]
@dep-dt Ask in <https://github.com/DefinitelyTyped/dt-mergebot>

**Comment by jamescdavis** [comment]
@use-strict @rhonsby looks like DT maintainers would like you to review. 🙏

**Comment by ExE-Boss** [comment]
This fixes issue <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47602> and closes PR <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47607>, so [this should be placed in the PR description](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword):

```
- Fixes <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47602>
- Closes <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47607>
```

**Comment by ulrikstrid** [comment]
Is it possible to use this without a release to npm?

**Comment by olyop** [comment]
> Is it possible to use this without a release to npm?

Since its just a typescript issue, you can manually edit file and add the `undefined` option in the node_modules folder.

**Comment by ulrikstrid** [comment]
@olyop Not really feasible in CI 😂 hopefully this lands soon, or is there some workaround I can do with a flag in tsconfig.json?

**Comment by andrevmatos** [comment]
@ulrikstrid pin `@types/node@14.10.0` devDependency until this gets merged. The offending change was published as `14.10.1`.

**Comment by mmso** [comment]
Will this still get merged in case a maintainer review never happens?

**Comment by jamescdavis** [comment]
> Will this still get merged in case a maintainer review never happens?
 
@sandersn?

**Comment by jamescdavis** [comment]
❤️  @sandersn

**Comment by jamescdavis** [comment]
This was released as [@types/webpack-env@1.15.3](https://www.npmjs.com/package/@types/webpack-env/v/1.15.3).
