### PR TITLE
types/node: Remove function `AsyncLocalStorage.runSyncAndReturn()` not available in Node v12

### LINKED ISSUE #48688: @types/node for v12 - async_hooks#AsyncLocalStorage.run return type is incorrect
[AsyncLocalStorage#run](https://nodejs.org/dist/latest-v12.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage) returns the result of passed function instead of `void`

- [+ ] I tried using the `@types/xxxx` package and had problems.
- [+] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
  - Authors: @peterblazejewicz 

also there're no `runSyncAndReturn` in node 12

### PR DESCRIPTION
**Pull request by josteink**
Remove function `AsyncLocalStorage.runSyncAndReturn()` not available in Node v12:

- https://nodejs.org/dist/latest-v12.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage

This partially resolves https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48688.

### CODE REVIEW

File: types/node/async_hooks.d.ts [hunk 1]
```diff
@@ -199,7 +199,7 @@ declare module "async_hooks" {
          * stacktrace will not be impacted by this call and the context will be exited.
          */
         // TODO: Apply generic vararg once available
-        run<R>(store: T, callback: (...args: any[]) => R, ...args: any[]): R;
+        run(store: T, callback: (...args: any[]) => void, ...args: any[]): Promise<void>;
```
Comment (Flarna) [inline types/node/async_hooks.d.ts:202]: I don't think this is correct. `run` calls `callback` and returns the result from the callback. Therefore I think the current definition is correct.

Comment (josteink) [reply types/node/async_hooks.d.ts:202]: Are you sure about that? The documentation seems to disagree.

Also: If `callback` is invoked asynchronously, how can `run()` return the result of that callback when it hasn't been invoked yet?

Comment (Flarna) [reply types/node/async_hooks.d.ts:202]: Yes, the callback is called sync, see https://github.com/nodejs/node/blob/354b6a93bd1d66f1833489d6fe01a2b0e8f6aff9/lib/async_hooks.js#L292-L305

Comment (josteink) [reply types/node/async_hooks.d.ts:202]: Looking at the actual *implementation* I would have to agree. The return value *is* of type `R`, but that means that the documentation for this function is clearly wrong, because it says the result should be awaited:

image

I'll revert this change.

Comment (Flarna) [reply types/node/async_hooks.d.ts:202]: Sample:
```
const { AsyncLocalStorage} = require("async_hooks");
const als = new AsyncLocalStorage();
console.log(typeof als.run({}, () => 15));
console.log(typeof als.run({}, () => "15"));
```
prints
```
number
string
```

**Comment by josteink** [comment]
PR updated and I've discarded the commits altering function signature of `AsyncLocalStorage.run()` completely since the actual error is not in the type-definitions, but seemingly in the NodeJS documentation for this function.

File: types/node/async_hooks.d.ts (hunk 1 above)
Comment (Flarna) [reply types/node/async_hooks.d.ts]: Updated sample:
```
async function foo() {
    console.log(typeof als.run({}, () => 15));
    console.log(typeof als.run({}, () => "15"));
    console.log(typeof await als.run({}, () => 15));
    console.log(typeof await als.run({}, () => "15"));
}
foo();

prints
```
number
string
number
string
```
`await` magically converts the sync return value into a `Promise` and awaits it.
Usually you want do it that way instead the called function is a function returning a `Promise`.

I think the node docs are a little bit misleading as they may be interpreted that users have to `await` the `als.run` call. But that is not true.
The intention of this doc is to explain that you have to take care with using `AsyncLocalStorage` within async functions. Maybe I will file a PR against node docs if I have a good idea how to describe this better.

**Review by Flarna — APPROVED** [review]
