### PR TITLE
analytics-node export Analytics class as described in the docs

### LINKED ISSUE #12706: analytics-node on the types-2.0 branch is broken
The version on the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/analytics-node/index.d.ts (which currently looks like this) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/48c95a4bb4c59c9601f54bfb8e5625ba35be12dc/analytics-node/index.d.ts is broken, because it is not possible to create a 

According to the [documentation](https://segment.com/docs/sources/server/node/), an instance is supposed to be created like this:

```js
var Analytics = require('analytics-node');
var analytics = new Analytics('YOUR_WRITE_KEY');
```

But the typings definition suggests to create it like this:

```typescript
import AnalyticsNode = require("analytics-node");
new AnalyticsNode.Analytics('YOUR_WRITE_KEY');
```
But that does not work!

There is an old definition of the module that works: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/analytics-node/analytics-node.d.ts

The key here is

```typescript
declare module "analytics-node" {
  export = AnalyticsNode.Analytics;
}
```

I am not sure how this should look like with typescript-2.0, but the current definition is definitely broken.

### PR DESCRIPTION
**Pull request by scharf**
Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: https://segment.com/docs/sources/server/node/
- [ ] Increase the version number in the header if appropriate.

This fixes #12706.

According to the [documentation](https://segment.com/docs/sources/server/node/), an instance is supposed to be created like this:

```js
var Analytics = require('analytics-node');
var analytics = new Analytics('YOUR_WRITE_KEY');
```

### CODE REVIEW

**Review by fongandrew — APPROVED** [review]

File: analytics-node/index.d.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
 // Definitions by: Andrew Fong <https://github.com/fongandrew>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 
-export = AnalyticsNode;
+export = AnalyticsNode.Analytics;
```
Comment (mhegazy) [inline analytics-node/index.d.ts]: you do not need the namespace declaration. just keep the class in the top scope and `export = Analytics`
