### PR TITLE
fix(mongodb): correct GridFSBucketWriteStream.abort callback

### LINKED ISSUE #44549: [@types/mongodb] Missing error parameter in abort() callback for GridFSBucketWriteStream
- [x] I tried using the `@types/mongodb` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @CaselIT @alanmarcell @Dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @Denys-Bushulyak @sindbach @geraldinelemeur @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @peterblazejewicz @LinusU @taxilian @xamgore @avaly

Hi, this is a follow up issue for #44360. The callback definition for `abort` is missing an error parameter, which may be present if there was an error removing chunks.

https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucketWriteStream.html#abort
https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback
https://mongodb.github.io/node-mongodb-native/3.6/api/lib_gridfs-stream_upload.js.html#line112

```typescript
const stream = bucket.openUploadStreamWithId(...);
stream.abort((error) => {});
```

```
Argument of type '(error: any) => void' is not assignable to parameter of type '() => void'.
```

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This fixes callback method definition to match documentation:
https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback

Also this error callback now has the same shape as default
MongoCallback, hence the extend.

/cc @alexy4744

Fixes #44549

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by sandersn** [comment]
This looks like an improvement to me, but I don't like merging changes to such a widely used package without some authors signing off.

@CaselIT @alanmarcell @Dante-101 @mcortesi @EnricoPicci @AJCStriker @julien-c @daprahamian @Denys-Bushulyak @BastienAr @sindbach @geraldinelemeur @various89 @angela-1 @lirbank @hector7 @floric @erikc5000 @Manc @jloveridge @Ranguna @HosseinAgha @albertossilva @LinusU @taxilian @xamgore @avaly @HitkoDev
Can you take a look?

**Comment by xamgore** [comment]
I believe you should bump the package version, as it looks like a _minor_ breaking change.

**Review by CaselIT — APPROVED** [review]
Looks ok.

**Comment by CaselIT** [comment]
> I believe you should bump the package version, as it looks like a minor breaking change.

From the added test it seems to not break the older callback

File: types/mongodb/index.d.ts [hunk 1]
```diff
@@ -2433,9 +2433,9 @@ export interface GridFSBucketOptions {
     readPreference?: ReadPreferenceOrMode;
 }
 
-/** http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html#~errorCallback */
-export interface GridFSBucketErrorCallback {
-    (err?: MongoError): void;
+/** http://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback */
+export interface GridFSBucketErrorCallback<T = any> extends MongoCallback<T> {
+    (error: MongoError, result: T): void;
```
Comment (LinusU) [inline types/mongodb/index.d.ts:2438]: Since you removed `?` I think that you should make this `| undefined`. The same goes for `T` since it won't be available when error is.

```suggestion
    (error: MongoError | undefined, result: T | undefined): void;
```

Maybe even, if it works:

```suggestion
    (error: undefined, result: T): void;
    (error: MongoError, result: undefined): void;
```

File: types/mongodb/index.d.ts [hunk 2]
```diff
@@ -2481,7 +2481,7 @@ export class GridFSBucketWriteStream extends Writable {
      * @param [callback] called when chunks are successfully removed or error occurred
      * @see {@link https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucketWriteStream.html#abort}
      */
-    abort(callback?: () => void): void;
+    abort(callback?: GridFSBucketErrorCallback): void;
```
Comment (LinusU) [inline types/mongodb/index.d.ts:2484]: The callback here will not receive any data:

```suggestion
    abort(callback?: GridFSBucketErrorCallback<void>): void;
```

File: types/mongodb/index.d.ts (hunk 1 above)
Comment (LinusU) [reply types/mongodb/index.d.ts:2438]: Actually, since this is only used in one place (right?), I think it would be better to just:

```suggestion
    (error?: MongoError | null): void;
```

also here, I think that `null` is actually the value received, not undefined. I might be wrong though

File: types/mongodb/index.d.ts [hunk 3]
```diff
@@ -2433,9 +2433,9 @@ export interface GridFSBucketOptions {
     readPreference?: ReadPreferenceOrMode;
 }
 
-/** http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html#~errorCallback */
-export interface GridFSBucketErrorCallback {
-    (err?: MongoError): void;
+/** http://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback */
+export interface GridFSBucketErrorCallback<T = any> extends MongoCallback<T> {
+    (error: MongoError, result: T): void;
 }
```
Comment (LinusU) [inline types/mongodb/index.d.ts:2439]: Oh, I just saw the `extends` part.

You don't need to declare the function interface in this body, it will be inherited from `MongoCallback`.

Since this is called `GridFSBucketErrorCallback` I think that it should not take a `T` parameter.

```suggestion
export interface GridFSBucketErrorCallback extends MongoCallback<void> {}
```

**Comment by LinusU** [comment]
Sorry for the late review, added som comments now.

Basically I think that the best approach would be:

```ts
export interface GridFSBucketErrorCallback extends MongoCallback<void> {}
```

together with a modification of `MongoCallback` to indicate the proper nullability:

```ts
export interface MongoCallback<T> {
    (error: MongoError | null, result?: T | null): void;
}
```

**Comment by peterblazejewicz** [comment]
Let me see, be back with feedback/changes

> Sorry for the late review, added som comments now.

absolutely not a problem nowadays

**Comment by peterblazejewicz** [comment]
@LinusU 

> ```ts
> export interface MongoCallback<T> {
>     (error: MongoError | null, result?: T | null): void;
> }
> ```

It seems it would be impacting a lot of existing code, e.g.:
```ts
(err: mongodb.MongoError, client: mongodb.MongoClient) => {
```

This patch passses all tests (inluding referenced libs)
```diff
diff --git a/types/mongodb/index.d.ts b/types/mongodb/index.d.ts
index 1ca7230faa..b609a248a5 100644
--- a/types/mongodb/index.d.ts
+++ b/types/mongodb/index.d.ts
@@ -2439,10 +2439,8 @@ export interface GridFSBucketOptions {
     readPreference?: ReadPreferenceOrMode;
 }
 
-/** http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html#~errorCallback */
-export interface GridFSBucketErrorCallback {
-    (err?: MongoError): void;
-}
+/** http://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucket.html#~errorCallback */
+export interface GridFSBucketErrorCallback extends MongoCallback<void> {}
 
 /** http://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucket.html#find */
 export interface GridFSBucketFindOptions {
@@ -2487,7 +2485,7 @@ export class GridFSBucketWriteStream extends Writable {
      * @param [callback] called when chunks are successfully removed or error occurred
      * @see {@link https://mongodb.github.io/node-mongodb-native/3.6/api/GridFSBucketWriteStream.html#abort}
      */
-    abort(callback?: () => void): void;
+    abort(callback?: GridFSBucketErrorCallback): void;
 }
 
 /** https://mongodb.github.io/node-mongodb-native/3.1/api/GridFSBucketWriteStream.html */
diff --git a/types/mongodb/test/index.ts b/types/mongodb/test/index.ts
index a8b0645d31..93576621d0 100644
--- a/types/mongodb/test/index.ts
+++ b/types/mongodb/test/index.ts
@@ -89,10 +89,14 @@ const gridFSBucketTests = (bucket: mongodb.GridFSBucket) => {
     const openUploadStream  = bucket.openUploadStream('file.dat');
     openUploadStream.on('close', () => {});
     openUploadStream.on('end', () => {});
+    openUploadStream.abort(); // $ExpectType void
     openUploadStream.abort(() => {
         openUploadStream.removeAllListeners();
     });
-    openUploadStream.abort();
+    openUploadStream.abort((error) => {
+        error; // $ExpectType MongoError
+    });
+    openUploadStream.abort((error, result) => {});
 };
 
 // Compression
```
so, as you can see, only small, focused change to the callback interface for this specific stream type.

**Comment by LinusU** [comment]
> It seems it would be impacting a lot of existing code

Yes, but I think that that would be good. Currently the typings here are basically turning off `strictNullChecks` for anyone that uses it, which I think is a big no-no.

That being said, if you just want this PR to focus on changing the specific callback for `abort` that is of course okay. The patch you posted above looks good

**Comment by peterblazejewicz** [comment]
> That being said, if you just want this PR to focus on changing the specific callback for `abort` that is of course okay. The patch you posted above looks good

Yes, my exact intent. I'll amend with the patch described. 
Again, thx for valuable input!

**Comment by peterblazejewicz** [comment]
rebased, with minor changes (as per @LinusU feedback)

**Review by CaselIT — APPROVED** [review]

**Comment by peterblazejewicz** [comment]
Ready to merge
