### PR TITLE
[d3-scale] Default scales to not returning unknown values

### LINKED ISSUE #48299: [d3-scale] Scales return `T | undefined` ?
Is something wrong with CI or publishing infrastructure?

- Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.
- Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).

If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Methuselah96 

I just pulled the latest definitions for d3-scale that includes this merged PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48095

I'm curious why all of the scale functions now have this signature:

```ts
    // ordinal:
    (x: Domain): Range | undefined;
   // continuous
   (value: NumberValue): Output | undefined;
```

Is this because its possible that the Range array could be empty? Reading the d3-scale docs I don't see `undefined` being described as a possible output value, and I've never had `undefined` returned in practice as far as I'm aware.

### PR DESCRIPTION
**Pull request by Methuselah96**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Resolves https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48299.

### CODE REVIEW

File: types/d3-scale/d3-scale-tests.ts [hunk 1]
```diff
@@ -78,9 +78,11 @@ tickFormatNumberFn = d3Scale.tickFormat(0, 10, 5, '+%');
 
 // scaleLinear() -----------------------------------------------------------------
 
-let linearScaleNumber: d3Scale.ScaleLinear<number, number>;
-let linearScaleString: d3Scale.ScaleLinear<string, string>;
-let linearScaleNumString: d3Scale.ScaleLinear<number, string>;
+let linearScaleNumber: d3Scale.ScaleLinear<number, number, never>;
```
Comment (danvk) [inline types/d3-scale/d3-scale-tests.ts:81]: I wonder if this is going to break things for existing users, too, since `ScaleLinear<number, number>` is now an error.

Since you can't specify some generic parameters but not others, a workaround would be to introduce a new type and replace the existing one with something like:

```ts
type ScaleLinear<Domain, Range> = ScaleLinearUnknown<Domain, Range, never>;
```

File: types/d3-scale/d3-scale-tests.ts [hunk 2]
```diff
@@ -133,7 +135,9 @@ clampFlag = linearScaleNumber.clamp();
 
 // unknown(...) -----------------------------------------------------------------
 
-linearScaleNumber = linearScaleNumber.unknown(5);
+linearScaleNumberUnknownNumber = linearScaleNumber.unknown(5);
+linearScaleNumberUnknownString = linearScaleNumber.unknown('test');
+const numOrString: number | string = linearScaleNumberUnknownString(3);
 const linearScaleNumberUnknownValue = linearScaleNumber.unknown();
```
Comment (danvk) [inline types/d3-scale/d3-scale-tests.ts:141]: do you want to assert a type on this (`: number`)?

File: types/d3-scale/index.d.ts [hunk 3]
```diff
@@ -714,8 +779,10 @@ export function scaleSymlog<Range, Output = Range>(
 /**
  * Identity scales are a special case of linear scales where the domain and range are identical; the scale and its invert method are thus the identity function.
  * These scales are occasionally useful when working with pixel coordinates, say in conjunction with an axis.
+ *
+ * The generic corresponds to the data type of the unknown value.
  */
-export interface ScaleIdentity {
+export interface ScaleIdentity<Unknown> {
```
Comment (danvk) [inline types/d3-scale/index.d.ts:785]: I think you want to default this to `never`. Otherwise it defaults to `unknown` (lowercase `u`, the TS builtin) and `number | unknown` is `unknown`, which will make this interface unusable.

**Review by danvk — APPROVED** [review]
Thanks @Methuselah96, overall this looks great.

My main concern is that introducing a new generic parameter to types like `ScaleLinear` will also break many existing users. It would be nice if the 99% of users who don't know/care about `scale.unknown()` could continue to be blissfully ignorant of it.

File: types/d3-scale/d3-scale-tests.ts (hunk 1 above)
Comment (Methuselah96) [reply types/d3-scale/d3-scale-tests.ts:81]: How often do users of the types reference the interfaces directly? My understanding is that most people use the top-level methods (which have friendly generic defaults) and do most things inline., so there's not usually a need to write out the interface type. Also, as a general pattern for `d3-*` types we don't specify defaults for the interface generics and instead provide generic defaults for the functions to make them easy-to-use.

File: types/d3-scale/index.d.ts (hunk 3 above)
Comment (Methuselah96) [reply types/d3-scale/index.d.ts:785]: I don't think it will default to `never`, it will just complain that you didn't provide a generic.

File: types/d3-scale/d3-scale-tests.ts (hunk 2 above)
Comment (Methuselah96) [reply types/d3-scale/d3-scale-tests.ts:141]: Sure.

Comment (Methuselah96) [reply types/d3-scale/d3-scale-tests.ts:141]: Except it will be `undefined`.

Comment (danvk) [reply types/d3-scale/d3-scale-tests.ts]: Right! 👍

File: types/d3-scale/d3-scale-tests.ts (hunk 1 above)
Comment (danvk) [reply types/d3-scale/d3-scale-tests.ts:81]: Anecdotally, all of the TS files in my project that use d3-scale reference `ScaleLinear` and will break with this.

If you define a class and store the scale in a member variable, or if you're working in React and want to store it in state, you need to write out the type. See https://github.com/microsoft/TypeScript/issues/33272 for previous problems that changing generic behavior caused with d3 (those were TS changes, not @types/d3 changes, but it shows that these types are very much in use).

File: types/d3-scale/index.d.ts (hunk 3 above)
Comment (danvk) [reply types/d3-scale/index.d.ts:785]: Yes, you're right about `unknown`. I was thinking of cases where TS can't infer a type.

But in this case adding a default of `never` would avoid breaking changes for anyone currently using this type. What's the downside?

Comment (Methuselah96) [reply types/d3-scale/index.d.ts]: It can make it easier to forget to provide it in places that it should be specified. Either way, I went ahead and made the change.

File: types/d3-scale/d3-scale-tests.ts (hunk 1 above)
Comment (Methuselah96) [reply types/d3-scale/d3-scale-tests.ts:81]: I went ahead and made the change.

**Review by danvk — APPROVED** [review]
Looks great, @Methuselah96. Thanks for making the changes, I really appreciate it! And hopefully @types/d3-scale users who never see this PR will, too :)

**Review by andrewbranch — APPROVED** [review]

**Comment by Methuselah96** [comment]
Ready to merge

**Comment by ermik** [comment]
@Methuselah96 hey Nathan, why is this only effective on `d3-scale@3`? Can this be replicated for earlier versions?

**Comment by Methuselah96** [comment]
@ermik Yeah, this can be replicated for earlier versions, feel free to make a PR.
