### PR TITLE
mongoose.d.ts Document interface should define _id as any

### LINKED ISSUE #7499: mongoose.d.ts Document interface should define _id as any
In the `Document` interface definition of mongoose.d.ts (line 426), the `_id` field definition of `_id: Types.ObjectId` is wrong, as it can be any type. Instead, it should be defined as `_id: any` to allow interfaces that extend `Document` to refine the definition of `_id` as appropriate to match the schema of the model/collection.

The current definition prevents the creation of models that use common `_id`  types like `string` and `number`.

Unit test code:

    interface IZip extends mongoose.Document {
        _id: string;
    }
    interface IPerson extends mongoose.Document {
        _id: mongoose.Types.ObjectId;
    }
    interface IThing extends mongoose.Document {
        _id: number;
    }

Let me know if you want me to submit a pull request that fixes this.

### PR DESCRIPTION
**Pull request by jhasselkus**
In the Document interface definition of mongoose.d.ts, the _id field
definition of `_id: Types.ObjectId` was wrong, as it can be any type. This
PR changes the definition to `_id: any` to allow interfaces that
extend Document to refine the definition of _id as appropriate to match
the schema of the model/collection.

Closes #7499

### CODE REVIEW

File: mongoose/mongoose.d.ts [hunk 1]
```diff
@@ -423,7 +423,7 @@ declare module "mongoose" {
 
   export interface Document {
     id?: string;
-    _id: Types.ObjectId;
+    _id: any;
```
Comment (horiuchi) [inline mongoose/mongoose.d.ts]: I prefer not `any` type.
In this case, we may use `number | string | mongoose.Types.ObjectId` instead of `any`.

**Comment by horiuchi** [comment]
@jhasselkus Thanks mate!

---
via. https://docs.mongodb.org/manual/core/document/#the-id-field
