### PR TITLE
[chart.js] Added export, tests and type corrections to chart.js

### LINKED ISSUE #12525: [chart.js] not working using types-2.0 and webpack
- [x] I want to talk about `chart.js/index.d.ts`.
  - The authors of that type definition are cc/ @anuti 

Using chart.js definition from types-2.0 in webpack results in `File '.../node_modules/@types/chart.js/index.d.ts' is not a module.`

Shouldn't there be a `export { Chart };`, `export class Chart {...}` or at least `export = Chart;` within that file?

### PR DESCRIPTION
**Pull request by stephtr**
fixes #12525 (@vvakame)
I hope that change doesn't break backward compatibility.

### CODE REVIEW

File: chart.js/index.d.ts [hunk 1]
```diff
@@ -3,15 +3,15 @@
 // Definitions by: Alberto Nuti <https://github.com/anuti>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 
-declare enum ChartType {
+export enum ChartType {
```
Comment (stephtr) [inline chart.js/index.d.ts]: But even then `new window.Chart()` is not working, only `new window.Chart.Chart()`.
Is it better to wrap all in a namespace and export just the namespace and by default the Chart class?

Comment (rbuckton) [inline chart.js/index.d.ts]: Probably, given that Chart _is_ the exported module. Something like:

```ts
declare class Chart {
    public static readonly Chart: typeof Chart;
    ...
}

declare namespace Chart {
    ...
}

export = Chart;
export as namespace Chart;
```

Comment (rbuckton) [inline chart.js/index.d.ts]: This may be prior to your changes, but it doesn't look like Chart.js exports or even uses a `ChartType` enum. This may either need to be a `const enum` or be removed.

File: chart.js/index.d.ts [hunk 2]
```diff
@@ -3,15 +3,15 @@
...
     line, bar, radar, doughnut, polarArea, bubble
 }
-declare enum TimeUnit {
+export enum TimeUnit {
```
Comment (rbuckton) [inline chart.js/index.d.ts]: Also possibly prior to your changes, but Chart.js also does not export a value named `TimeUnit`, and `TimeScale` (the only case where `TimeUnit` is used) only allows strings per the documentation ([here](https://github.com/chartjs/Chart.js/blob/7c8998f96adeece76000406ca06ec8bb178392d7/docs/02-Scales.md#time-scale) and [here](https://github.com/chartjs/Chart.js/blob/7c8998f96adeece76000406ca06ec8bb178392d7/docs/02-Scales.md#time-units)). Perhaps this should be a type alias:

```ts
export declare type TimeUnit = "millisecond" | "second" | "minute" | "hour" | "day" | "week" | "month" | "quarter" | "year";
```

**Review by rbuckton — CHANGES_REQUESTED** [review]

File: chart.js/index.d.ts (hunk 1 above)
Comment (stephtr) [inline chart.js/index.d.ts]: I am changing it to `declare type ChartType = 'line' | 'bar' | ...`.
The problem is that chart.js can be extended by additional ChartTypes. Therefore in ChartConfiguration I define `type?: ChartType | string;` leaving space for future enhancements.

Comment (stephtr) [inline chart.js/index.d.ts]: Now that works perfect.

File: chart.js/index.d.ts (hunk 2 above)
Comment (stephtr) [inline chart.js/index.d.ts]: Fixed.

**Comment by stephtr** [comment]
Additionally I noticed that `TimeScale.displayFormats` was defined as string, even though according to [documentation](http://www.chartjs.org/docs/#scales-time-scale) -> Display Formats it should be an object of strings.

**Comment by stephtr** [comment]
One improvement opportunity would be to automatically select the correct `ChartData` (`LinearChartData`, ...) according to `ChartConfiguration.type`. That could be possible using generics, but probably I will leave that for a future PR.

**Comment by andy-ms** [comment]
Hi @stephtr, could you fix the merge conflict?

**Comment by stephtr** [comment]
Sorry, somehow I forgot to finish the merge.
Thank you!
