### PR TITLE
[lodash] fix _.has not to be inferred to never on or operator

### LINKED ISSUE #69528: version 4.17.1，the type of the data variable is inferred to never by _.has
**issue：**
on 4.17.1 version，the type of the data variable is inferred to never by _.has。
image

**source of problem：**
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69291
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1c01676bd56522b1eb13f7e4e0a2415773c535a6#diff-0740e38db2dd38b18fb8612ceef08349585a3d898fb6ad21522819b8677804f7

### PR DESCRIPTION
**Pull request by Ha-limLee**
fixed #69528

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://lodash.com/docs/4.17.15#has>

### CODE REVIEW

File: types/lodash/common/object.d.ts [hunk 1]
```diff
@@ -1327,7 +1328,7 @@ declare module "../index" {
          * _.has(other, 'a');
          * // => false
          */
-        has<T, K extends PropertyName>(object: T, path: K): object is T & { [P in K]: P extends keyof T ? T[P] : Record<string, unknown> extends T ? T[keyof T] : unknown};
+        has<T, K extends PropertyName>(object: T, path: K): object is T & {[uniqueSymbol]: unknown} & { [P in K]: P extends keyof T ? T[P] : Record<string, unknown> extends T ? T[keyof T] : unknown};
```
Comment (aj-r) [inline types/lodash/common/object.d.ts:1331]: nit: move `& {[uniqueSymbol]: unknown}` to the end of the line since it's the least important part.

**Review by aj-r — APPROVED** [review]

**Review by aj-r — APPROVED** [review]

**Review by sandersn — APPROVED** [review]

**Comment by Ha-limLee** [comment]
Ready to merge
