### PR TITLE
fix(carbon-components-react): `title` prop of the AccordionItem. Closes #41811

### LINKED ISSUE #41811: [Accordian][AccordianItem] - AccordionItem does not accepts 'title' as node element in props.
AccordionItem only accepts title as string.
does not accepting title as react node elememt.

If You see in below url- 
title accepts string as default, need to add title as -

`export interface AccordionItemProps extends InheritedProps {
    onHeadingClick?(data: HeadingClickData): void,
    open?: boolean,
    renderExpando?: React.ReactNode,
    title?: React.ReactNode,
}`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- redeclare `title` property to supports React.Node

Thanks!

FYI: omit for:
> type 'ReactNode' is not assignable to type 'string'

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/AccordionItem/AccordionItem.js#L36

### CODE REVIEW

File: types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts [hunk 1]
```diff
@@ -8,10 +8,12 @@ export interface HeadingClickData {
     isOpen: boolean;
 }
 
-export interface AccordionItemProps extends InheritedProps {
+export interface AccordionItemProps extends Omit<React.HTMLProps<InheritedProps>, "title"> {
```
Comment (kalbert312) [inline types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts]:
```suggestion
export interface AccordionItemProps extends Omit<InheritedProps, "title"> {
```
Any HTML props and common carbon props are already on the `InheritedProps` interface. There's no constraint on that type parameter of `HTMLProps`  but it is used as the type for the event handlers and ref so we're no longer extending from `InheritedProps`.

**Review by kalbert312 — CHANGES_REQUESTED** [review]

**Review by kalbert312 — APPROVED** [review]

File: types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts (hunk 1 above)
Comment (peterblazejewicz) [reply types/carbon-components-react/lib/components/Accordion/AccordionItem.d.ts]: Done! Appreciated, thanks!
