### PR TITLE
[styled-components] Fix children bug; Add `styled-component/native` typings

### LINKED ISSUE #31491: [styled-components] Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes...
If you know how to fix the issue, make a pull request instead.

- [x ] I tried using the `@types/styled-components` package and had problems.
- [x ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x ] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @Igorbek @Igmat @Lavoaster @Kovensky 

I have the following code snippet of a component which should be correct according to the styled-components documentation.

```
const Wrapper = styled(Box)`
  border: 1px solid grey;
`;

const App = () => (
  <Wrapper>
    <Hello name="CodeSandbox" />
  </Wrapper>
);
```

Typescript though returns the following error:

> Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Pick<Pick<BoxProps | (BoxProps & RefAttributes<Component<BoxProps, any, any>>), "a11yTitle" | "alignSelf" | "gridArea" | "margin" | "align" | ... 19 more ... | "wrap"> & Partial<...>, "a11yTitle" | ... 23 more ... | "wrap"> & { ...; } & { ...; }'.ts(2559)

I tried to find a solution but the only thing I found was this question on [StackOverflow].(https://stackoverflow.com/q/53724583/6882608)

Do you have some ideas how to solve this? 

I created a CodeSandbox where it can be reproduced: https://codesandbox.io/s/10z3qz9jp4
(In the beginning the error doesn't show in the sandbox. As soon as you add `<Wrapper someProp="">` and then remove it again, the error shows up.)

Dependencies:
- Typescript 3.2.2
- styled-components 4.1.3
- @types/styled-components 4.1.4
- @types/react 16.7.17

### PR DESCRIPTION
**Pull request by jkillian**
This PR does two main things: It adds typings for `styled-component/native` as [the most recent versions of the typings don't yet support it](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29795). It also fixes [a bug where some styled components were unable to accept children](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31491). I had to add the children-fix to this PR in order to get my react-native test cases to pass.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). (I was getting errors about `typescript@next` and external dependencies, need to figure out what was going on before I can run these tests locally. Hoping to lean on CI in the meantime.)

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

  * For the react-native changes, the tests are based off of these docs: 
  https://www.styled-components.com/docs/basics#react-native
  * For the bug related to children of components:
  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31491#issuecomment-459353227

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

### CODE REVIEW

File: types/styled-components/index.d.ts [hunk 1]
```diff
@@ -65,7 +66,7 @@ export type StyledComponentProps<
         A
     > & Partial<Pick<React.ComponentPropsWithRef<C> & O, A>>,
     T
->;
+> & { children?: React.ReactNode };
```
Comment (JKillian) [inline types/styled-components/index.d.ts]: this is the fix for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31491. Essentially, we just always tack on `children` to whatever props are provided (since this is what React does as well in its typings).

**Comment by JKillian** [comment]
* Removed `"dom"` form the library typings as per https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26218
* Removed references to node types as they seemed unnecessary

**Comment by JKillian** [comment]
Hooray, tests passing! I also tried out the new typings in a project of mine and they worked well. To recap, in order to get tests to pass, I had to:

* Removed `"dom"` form the library typings as per https://github.com/DefinitelyTyped/DefinitelyTyped/issues/26218
* Removed references to node types and replace with a stub for `NodeJS.ReadableStream`
* Comment out one line of tests which was now mysteriously failing

File: types/styled-components/index.d.ts (hunk 1 above)
Comment (Lavoaster) [reply types/styled-components/index.d.ts]: You can specifically type a component to not accept children if you avoid the react types, or you can specify _exactly_ the kind of child that you want such as for render callbacks.

```jsx
<Component>
  {({ text }) => (
    <p>{text}</p>
  )}
</Component>
```

For more information see #31945.

Comment (Jessidhia) [reply types/styled-components/index.d.ts]: The problem is that that works by accident. "since this is what React does as well in its typings" is a bad example (not your fault, it's just a terrible precedent that's still standing because of backwards compatibility).

Comment (Jessidhia) [reply types/styled-components/index.d.ts]: The fix I was going to suggest is to update `React.ComponentType` to be based off `JSXElementConstructor` instead of `ComponentType` but that has already been done on that side. The change to use `JSXElementConstructor` probably just needs to be propagated to `ReactType`.

Comment (JKillian) [reply types/styled-components/index.d.ts]: Thanks for the insightful feedback both @Lavoaster and @Jessidhia! I had missed seeing #31945 previously and didn't understand the full context of the problem.

I'm hoping my new commit I just pushed is a reasonable solution to the issue.

@Jessidhia as you mentioned, `type React.ComponentProps` was recently changed to use `extends ((props: infer P) => ReactNode) | (new (props: infer P) => Component<any>))`, which means things are already working well for functional components. However, `React.Component` only declares `children` as part of its `props` type and not in its constructor:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0b417416fe69ce507a5224f32924da296667b1fe/types/react/index.d.ts#L425

I believe this means that we won't be able to make `(new (props: infer P) => Component<any>)` useful to us. So instead, my new changes add `{ children?: React.ReactNode }` to `StyledComponentProps` only if our base component type is a `React.ComponentClass`. I _think_ this'll give us `children` where appropriate without being overly permissive where we shouldn't be.

---

Just to give context on why I'm working on this fix as part of this PR, this fix ends up being really important for react-native workflows (since all elements you use are components). Without the fix, you can't even do really common and basic workflows, like the following:

```ts
const element = <StyledView>
  <StyledText>Hello World!</StyledText>
</StyledView>;
```

**Comment by JKillian** [comment]
Updated PR to more judiciously handle adding `children` to props, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843#discussion_r254762366 for more context

**Comment by ScreamZ** [comment]
Seems like god is with me, this is done 2 days before I need it.

Hope merge is coming

**Comment by JKillian** [comment]
Glad to hear this helps you @ScreamZ 😄  Feel free to copy my changes to your project locally and use them in the meantime until this gets merged. I've been doing that in my projects and already caught a few bugs because of these typings!

**Comment by ScreamZ** [comment]
@JKillian Hey,

I'll try that, but do you have any idea how can we support syntax like `tint-color: blue` I get 
`Unknown property: 'tint-color'ts-styled-plugin(9999)`

I can use the object syntax like https://www.styled-components.com/docs/advanced#style-objects this but could be nice.

??

**Comment by JKillian** [comment]
Hey @ScreamZ, please see this ticket: https://github.com/Microsoft/typescript-styled-plugin/issues/58. I believe that's what you're asking about. It's actually not related to the `styled-components/native` typings if I understand correctly

**Comment by stephenotalora** [comment]
@minestarks when will this be getting released?

**Comment by ScreamZ** [comment]
Awesome thanks

File: types/styled-components/index.d.ts [hunk 2]
```diff
@@ -4,10 +4,17 @@
...
+//                 Jason Killian <https://github.com/jkillian>
 // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
 // TypeScript Version: 2.9
 
-/// <reference types="node" />
+// forward declarations
+declare global {
+    namespace NodeJS {
+        // tslint:disable-next-line:no-empty-interface
+        interface ReadableStream {}
```
Comment (Igorbek) [inline types/styled-components/index.d.ts]: out of curiosity, why this type was added here? I don't see it is used anywhere here.
(sorry for commenting merged pr)

Comment (Jessidhia) [reply types/styled-components/index.d.ts]: This was probably mistakenly added here to fix what's actually a `@types/react-native` problem instead 😔

Comment (minestarks) [reply types/styled-components/index.d.ts]: I see `ReadableStream` used further down in this file. It was presumably added to replace the the `/// <reference types="node" />` syntax that pulls in a dependency to the entire `node` typings.

Comment (JKillian) [reply types/styled-components/index.d.ts]: Thanks @minestarks, that was exactly my reasoning. The full node typings conflict with the react-native typings (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15960). To resolve that, I removed the reference to the node types and just stubbed out the one interface that we actually needed.

Comment (Igorbek) [reply types/styled-components/index.d.ts]: Sorry, 🤦‍♂️

**Comment by ScreamZ** [comment]
Can you provide an example how to provide theme completion ? I use to follow the official doc with the following but it seems to not match : 

```js
import * as styledComponents from 'styled-components/native'

// Theming styled components for typescript with RN.

import ThemeInterface, { themeValues } from './theme'

const {
  default: styled,
  css,
  createGlobalStyle,
  keyframes,
  withTheme,
  ThemeProvider
} = styledComponents as styledComponents.ThemedStyledComponentsModule<
  ThemeInterface
>

export {
  css,
  createGlobalStyle,
  keyframes,
  ThemeProvider,
  themeValues,
  withTheme
}
export default styled
```

Regards

**Comment by JKillian** [comment]
@ScreamZ, as far as types, please see https://github.com/styled-components/styled-components/issues/630.  I typically do [something like this](https://github.com/styled-components/styled-components/issues/630#issuecomment-457598864).

I'm not to sure on the themes issue, I haven't looked in to it deeply. It's possible it may work as is or it's possible there may be additional typings needed - I just haven't tried things out yet.

**Comment by flavordaaave** [comment]
@ScreamZ & @JKillian I've created a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33341) that adds a `ReactNativeThemedStyledComponentsModule` interface to support re-exporting with a custom theme interface a mentioned in the [docs](https://www.styled-components.com/docs/api#typescript)

**Comment by benlime** [comment]
Just saw the PR has been merges. @flavordaaave Thank you so much. 👍

**Comment by ScreamZ** [comment]
@flavordaaave I was doing this and it worked fine before your PR 

```ts
import { Platform } from 'react-native'
import * as styledComponents from 'styled-components/native'

/**
 * This define the shape of the Cleo theme.
 * If you want to add some properties please use this before and complete the implementation below.
 *
 * @interface CleoTheme
 */
interface CleoTheme {
  fontFamily: 'Roboto' | 'AvenirNext-Regular'
  colors: CleoThemeColors
}

interface CleoThemeColors {
  primary: string
  primaryText: string
  blueDark: string
  blueDark10: string
  blueLight: string
  green: string
  orange: string
  pink: string
  purple: string
  red: string
  yellow: string
  yellow10: string
  white: string
  black: string
  black60: string
  grayDark: string
  grayDark30: string
  grayDark10: string
  grayLight: string
}

export type CleoThemeColor = keyof CleoThemeColors

// Implementation of the Cleo theme.
// For opacity calculation from HEX : http://hex2rgba.devoth.com/
const cleoTheme: CleoTheme = {
  fontFamily: Platform.OS === 'ios' ? 'AvenirNext-Regular' : 'Roboto',
  colors: {
    black: '#000000',
    black60: 'rgba(0, 0, 0, 0.6)',
    grayDark: '#676F89',
    grayDark30: 'rgba(103, 111, 137, 0.3)',
    grayDark10: 'rgba(103, 111, 137, 0.1)',
    grayLight: '#F2F4F7',
    white: '#FFFFFF',
    primary: '#FF5E4A',
    primaryText: '#E02500',
    blueDark: '#0B5EDB',
    blueDark10: 'rgba(11, 94, 219, 0.1)',
    blueLight: '#0090C7',
    green: '#009954',
    orange: '#EE4C00',
    pink: '#FA1E97',
    purple: '#AA29E6',
    red: '#FF160A',
    yellow: '#F09400',
    yellow10: 'rgba(240, 148, 0, 0.1)'
  }
}

// Extract the properties we need for styled component.
const { default: styled, withTheme, ThemeProvider } = styledComponents

// Export those properties + theme values
export { ThemeProvider, cleoTheme, withTheme }

// Type the export to allow completion from React Native and Typescript
export default styled as styledComponents.ReactNativeStyledInterface<CleoTheme>
```

**Comment by ScreamZ** [comment]
Looks like using `FunctionComponent` with `withTheme` is not working

```ts
import * as React from 'react'
import styled, { withTheme } from '@styled-components'
import Text from '@modules/ui/components/Text'
import { Media } from '@modules/daily-timeline/components/cards/standard-card'
import { Switch } from 'react-native'

interface Props {
  label: string
  icon: number
  onPress?: () => void
  switch?: { value: boolean; onToogle: () => void }
  badgeCount: number
}

const SectionInlineItem: React.FunctionComponent<Props> = props => (
  <TouchableWrapper disabled={Boolean(props.switch)} onPress={props.onPress}>
    <Media fromFS={props.icon} mediaStyles={{ height: 40, width: 40 }} />
    <Title>{props.label}</Title>
    {props.switch ? (
      <Switch
        value={props.switch.value}
        onValueChange={props.switch.onToogle}
      />
    ) : (
      <Counter>
        <Text.Caption color="blueDark">{props.badgeCount}</Text.Caption>
      </Counter>
    )}
  </TouchableWrapper>
)

const TouchableWrapper = styled.TouchableOpacity`
  flex-direction: row;
  align-items: center;
  padding: 16px;
  background-color: ${props => props.theme.colors.white};
`

const Title = styled(Text.Text)`
  flex: 1;
  margin-horizontal: 16px;
  color: ${props => props.theme.colors.black};
`

const Counter = styled.View`
  padding-horizontal: 8px;
  border-radius: 12px;
  background-color: ${props => props.theme.colors.blueDark10};
  color: ${props => props.theme.colors.blueDark};
`

export default withTheme(SectionInlineItem)
```

I'm getting `Argument of type 'FunctionComponent<Props>' is not assignable to parameter of type 'never'.ts(2345)`

**Comment by flavordaaave** [comment]
@ScreamZ the react-native typings are just a copy of the already existing typings for react. I just checked and `withTheme` still requires you to specify your `CleoThemeColor` type in your `Props` manually (it's the same with "regular" react).
So in your case you should import your theme type first

```
import CleoTheme from '<path to your theme type>'
```

And than add it to your Props like this:

```
interface Props {
  label: string
  icon: number
  onPress?: () => void
  switch?: { value: boolean; onToogle: () => void }
  badgeCount: number
  theme: CleoTheme
}
```

If you have an idea how to improve this feel free to add another pull request.

**Comment by ScreamZ** [comment]
@flavordaaave Thanks, I guess there is a way yes, I'll think about it :) Thank you

**Comment by ScreamZ** [comment]
@flavordaaave Do you have any idea why I don't get any props completion using this syntax ?

```ts
const Background = styled(Animated.View)`
  position: absolute; /* Allows to do superposition */
  background-color: ${props => props.theme.colors.primary};
  padding: 16px;
  border-radius: 28px;
`
```

With this one everything is fine 👍 

```ts
const Background = styled.View`
  position: absolute; /* Allows to do superposition */
  background-color: ${props => props.theme.colors.primary};
  padding: 16px;
  border-radius: 28px;
`
```

Any way to type custom components ?

**Comment by paulmelnikow** [comment]
As far as I have been able to tell, this change caused the typings no longer to work with React DOM. The issue was reported at #33311 which includes a full reproduction.

The issue is affecting a lot of people.

Do any of the people involved with this PR know how to fix the problem? Is is possible to separate the typings so React Native-specific globals aren't shipped to a React DOM project?

**Comment by RobertB4** [comment]
It has been a year and this problem hasn't been addressed yet. I believe the easiest fix would be to create a separate styled-components-native package for the react native styles. 
This way, web users can use `@types/styled-components` as they always have, while native users will have to add `@types/styled-components-native` in addition. I'm not sure if there are any rules for package names, but I realize this goes against the general rule of prefixing a package with @types.

Either way, I think fixing this should be actively discussed as it affects a lot of people.

**Comment by ee0pdt** [comment]
@Jessidhia Any thoughts on @RobertB4's proposal above?

This is preventing me from upgrading to styled-components v5 and has widely affects users as you can see here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33311

**Comment by Jessidhia** [comment]
The workaround is to have a `compilerOptions.types` array in your `tsconfig.json` that stops typescript from automatically reading every single `@types/*` package when typechecking. Typescript will only automatically import the packages named in the `types` array; for example, `"types": ["node"]` (if you use builtin modules like `buffer` or `path`); or even just `"types": []` to prevent typescript from auto-loading any package that is not directly imported from your code.

I can't really say whether having a `@types/styled-components-native` would be better; it would be unusual at the very least, and maybe remove the need for the `compilerOptions.types` "workaround", but IMO setting `compilerOptions.types` to only the packages whose types you need to be autoloaded (without `import`s) is a best practice.

**Comment by pak11273** [comment]
// tsconfig.json

```javascript
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}
```
