### PR TITLE
More fixes for 2.4. Not all for weak types.

### LINKED ISSUE #17257: Typescript 2.4.0 and @types/angular are incompatible due to "Weak Types"
See https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/ under section "Weak Types" for context. I searched issues but not seeing it yet. Looks like per https://github.com/DefinitelyTyped/DefinitelyTyped/commit/1c3565933cc792ebb642477d5eed174d6d2ccd9a you are already aware of the issue though.

Basically many things in the angular types are "Weak Types" and therefore have stopped working if you don't share properties. Specifically `IController` and `IControllerConstructor` are issues with us currently since many of our controllers don't need any of those event callbacks.

This means many(most?) angular apps won't compile with these types and typescript 2.4.0

### PR DESCRIPTION
**Pull request by sandersn**
2.4 also has been inference for generics, which finds more errors as well.

1. Angular's IController is frequently implemented *without* any of its optional methods, so it needs a string indexer.
2. Browserify is similar, but with added refactoring that adds a CustomOptions type that explicitly holds user options plus `basedir`.
3. Bunyan-config's type were wrong. They used Bunyan's Stream type when its reason for existing is to allow string-only JSON configuration of Streams *without* referring to Bunyan streams.
4. hapi v8 from mid 2014, when compiled with Typescript 2.4, does not support contextual typing of `resolve` callbacks. I don't think this combination is likely, so I removed the test that showed this working. However, it still works on the old versions of Typescript that are likely to be used with v8.
5. Old versions of sequelize and js-data needed to be updated to match their newer versions (which I already fixed, in the case of sequelize).

Fixes #17257

### CODE REVIEW

**Review by cyrilschumacher — APPROVED** [review]

File: types/browserify/index.d.ts [hunk 1]
```diff
@@ -37,12 +37,21 @@ interface FileOptions {
...
-  // Custom properties can be defined on Options.
-  // These options are forwarded along to module-deps and browser-pack directly.
+interface CustomOptions {
+  /**
+   * Custom properties can be defined on Options.
+   * These options are forwarded along to module-deps and browser-pack directly.
+   */
   [propName: string]: any;
+  /** the directory that Browserify starts bundling from for filenames that start with .. */
+  basedir?: string;
```
Comment (leonard-thieu) [inline types/browserify/index.d.ts]: Options still has `basedir` declared.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17303/files#diff-6c09b620943cef5bf4bf6e0f64c7719dR64
(Couldn't figure out how to annotate it directly.)

Comment (sandersn) [inline types/browserify/index.d.ts]: Removed.

**Review by leonard-thieu — APPROVED** [review]
