### PR TITLE
react: Improve type checking of component static properties.

### LINKED ISSUE #16967: React Component static properties
React’s `Component` class supports static properties such as `displayName`, `defaultProps`, `propTypes`, and others.

When creating a component class, the common practice seems to be to extend the [`Component` class type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d60eb99644e018e760524e5789838a140269b1b/types/react/index.d.ts#L183). However, the `Component` class type does not include these static properties. This means you don't get errors for these static properties:

``` tsx
import React, { Component, ComponentClass } from 'react';

type Props = { name: string };

{
  class ReactComponent extends Component<Props, any> {
    // expected error, but got none: displayName should be a string
    static displayName = 1
    // expected error, but got none: defaultProps.name should be a string
    static defaultProps = { name: 1 }
  };
}
```

These static properties have instead been defined on a separate type, the [`ComponentClass` interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d60eb99644e018e760524e5789838a140269b1b/types/react/index.d.ts#L228). In order to get type checking for these static properties, one has to annotate the class using this interface:

``` tsx
{
  // error: displayName should be a string
  // error: defaultProps.name should be a string
  const ReactComponent: ComponentClass<Props> = class extends Component<Props, any> {
    static displayName = 1
    static defaultProps = { name: 1 }
  };
}
```

Is there any way we can consolidate these two types, so we get free type checking of static properties simply by extending `Component`?

/cc React type definition authors: @johnnyreilly @bbenezech @pzavolinsky @digiguru @ericanderson

### LINKED ISSUE #28515: [@types/react] Type-checking for defaultProps
If you know how to fix the issue, make a pull request instead.

- [x] I tried using the `@types/react` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @ferdaber @Hotell 

If you do not mention the authors the issue will be ignored.

---

Hello! Thank you in advance for your help.

I ran into an issue where `defaultProps` is not type-checked against the props generic for React components.

Here is a simple example component that illustrates the issue.
```tsx
import React from 'react';

type Props = { foo: string };

class Foo extends React.Component<Props> {
  static defaultProps = {
    foo: 123,
  };

  render() {
    return <div />;
  }
}
```

Here, we can see the type expected from the consumer (`string | undefined`)
image 17

Would have expected an error to come up because the `number` `foo` from `defaultProps` is not assignable to `string` from `Props`. Instead, I see no error. The default prop is picked up to make the `foo` prop optional, but appears that the type information is ignored.

Looks like this is where the defaultizing happens
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a95857f87476f9a30085c3728530ad10586ae1e4/types/react/index.d.ts#L2316

Which only looks at the keys of the defaultProps
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a95857f87476f9a30085c3728530ad10586ae1e4/types/react/index.d.ts#L2290-L2299

Would have expected `Partial<P>` to have resulted in some checking
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a95857f87476f9a30085c3728530ad10586ae1e4/types/react/index.d.ts#L363

```ts
const dp: typeof Foo['defaultProps'] = { foo: 1 };
const pp: Partial<Props> = dp;
```
image

Why is there no error when the `static defaultProps` for a React component is not assignable to `Partial<P>`?

### PR DESCRIPTION
**Pull request by mattmccutchen**
- Copy properties from ComponentClass to the Component class.

- Recommend the react-typescript-helpers package for checking the
  defaultProps and propTypes at a component definition.

- As a fallback, have JSX.LibraryManagedAttributes check the
  defaultProps and propTypes every time a component is used.

- Fix test failures in dependent packages.

Fixes #28515.
Fixes #16967.

Please review the fixes to the dependent packages!  I took my best guess at how to fix them because if I waited for the owners to answer a question, I suspect I would be waiting forever.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: N/A, improving type checking for already known runtime features
- [X] Increase the version number in the header if appropriate. (Not necessary)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (Already there)

### CODE REVIEW

File: types/react-select/test/examples/CustomNoOptionsMessage.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ const NoOptionsMessage = (props: any) => {
 export default class CustomNoOptionsMessage extends React.Component {
   render() {
     return (
-      <Select
+      <Select<{ label: string; value: string }>
```
Comment (jonfreedman) [inline types/react-select/test/examples/CustomNoOptionsMessage.tsx]: I'm not sure why you have changed this but none of the other places where Select is used without its type parameter - is there a reason?

File: types/react-select/lib/components/Menu.d.ts [hunk 2]
```diff
@@ -67,9 +67,6 @@ export type MenuProps<OptionType> = CommonProps<OptionType> & {
 export function menuCSS(state: MenuState): React.CSSProperties;
 
 export class Menu<OptionType> extends Component<MenuProps<OptionType>, MenuState> {
-  static contextTypes: {
```
Comment (jonfreedman) [inline types/react-select/lib/components/Menu.d.ts]: Is this removed because it's the wrong type, or because it's no-longer possible to define this static method?  This is based on the source @ https://github.com/JedWatson/react-select/blob/master/src/components/Menu.js#L267

File: types/theming/index.d.ts [hunk 3]
```diff
@@ -40,7 +40,7 @@ export interface ThemeListener<C extends string> {
     callback: (theme: Theme) => void
   ): SubscriptionId;
   unsubscribe(context: ContextWithTheme<C>, id: SubscriptionId): void;
-  contextTypes: React.ValidationMap<C>;
+  contextTypes: React.ValidationMap<ContextWithTheme<C>>;
```
Comment (eps1lon) [inline types/theming/index.d.ts]: Nice. Thanks for fixing that!

**Comment by Hotell** [comment]
Thanks for submitting PR @mattmccutchen !

Few thoughts from my POV:

- I don't think that recommending some 3rd party library is a good choice/pattern overall ( especially with runtime overhead and non idiomatic code for particular library )
- "fixing" statics by "copying" ComponentClass interface props to Component class doesn't fix anything as that is a limitation of TypeScript AFAIK/R
- TS 3.2 correctly handles/resolves defaultProps on both class and function components ( with limitation that if you annotate function component via generic `FunctionComponent` you're out of luck as it overrides inferred `defaultProps` - for that I've proposed solution by extending `FunctionComponent` which could be applicable to `ClassComponent` as well 👉 https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30695#issuecomment-440933780
- I like constraining children, although that goes against how particular library works. React always implements children no matter if they are used/"typeChecked" via propTypes. This constraint ( as that's a pattern that I highly recommend and use [tip no.8](https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680) ) should be handled by linter not by library types
- all in all the simplest solution ( which could be recommended ) is to define props via implementation inference, which covers issues described in your issue and so on:

```tsx
type Props = { version: number } & typeof defaultProps;

// only source of truth + idiomatic JS
const defaultProps = {
  who: 'Johny Five',
};

const Greeter = (props: Props) => {
  /*...*/
};
Greeter.defaultProps = defaultProps;

class GreeterCls extends Component<Props> {
  static defaultProps = defaultProps;
}

const Test = () => {
  return (
    <>
      <Greeter version={1} />
      <GreeterCls version={1} />
    </>
  );
};
```

So overall I don't feel like this should be merged, although you invested a lot of effort in this, which we all highly appreciate! And of course I may be wrong in my statements, so please correct me folks. thank you ❤️

Would love to see others feedback here as well. cc @Kovensky  @weswigham

**Comment by Kovensky** [comment]
The problem with having defaultProps in Component's definition is that assigning defaultProps yourself doesn't stop it from being Partial<P>. Declaring it does, and this happens to work for classes (only if you directly write static defaultProps = ...), but not at all for FunctionComponent.

File: types/react-select/test/examples/CustomNoOptionsMessage.tsx (hunk 1 above)
Comment (mattmccutchen) [reply types/react-select/test/examples/CustomNoOptionsMessage.tsx]: Documented.

File: types/react-select/lib/components/Menu.d.ts (hunk 2 above)
Comment (mattmccutchen) [reply types/react-select/lib/components/Menu.d.ts]: It's the wrong type.  Each member of `contextTypes` should be a validator for the type of the context entry, not an actual value of the type.  It would probably work to write `getPortalPlacement: typeof PropTypes.func`, but I didn't see the benefit of keeping this declaration at all.

File: types/react-select/test/examples/CustomNoOptionsMessage.tsx (hunk 1 above)
Comment (jonfreedman) [reply types/react-select/test/examples/CustomNoOptionsMessage.tsx]: Maybe it's obvious but not sure where you documented this? (on my phone so maybe missing something...)

Comment (mattmccutchen) [reply types/react-select/test/examples/CustomNoOptionsMessage.tsx]: I added a comment in the source code above this line.  The "Conversation" tab seems to show the revision of the file you originally commented on, but the "Files" tab shows the latest revision [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30730/files#diff-89b26201789aeff667fae9d3c31d3e75R21).

File: types/react/index.d.ts [hunk 4]
```diff
@@ -418,6 +418,31 @@ declare namespace React {
         refs: {
             [key: string]: ReactInstance
         };
+
+        // Static properties copied from ComponentClass interface.
+        /**
+         * The validity of the type of `propTypes` cannot be checked
+         * automatically at the definition of a component class because the
+         * required type depends on `P`.  We recommend checking it using
+         * `asPropTypes` from the `react-typescript-helpers` package.  If you
```
Comment (Kovensky) [inline types/react/index.d.ts]: What is this package 🤔 

https://www.npmjs.com/package/react-typerscript-helpers 404s

File: types/react/index.d.ts [hunk 5]
```diff
@@ -418,6 +418,31 @@ declare namespace React {
...
+         * don't do that, then the type will still be checked by
+         * JSX.LibraryManagedAttributes every time the component is used,
+         * assuming you use TypeScript 3.0 or newer.
+         */
+        static propTypes?: any;
```
Comment (Kovensky) [inline types/react/index.d.ts]: Would `object` be better?

File: types/react/index.d.ts [hunk 6]
```diff
@@ -418,6 +418,31 @@ declare namespace React {
...
+        /**
+         * The validity of the type of `defaultProps` cannot be checked
+         * automatically at the definition of a component class because the
+         * required type depends on `P`.  We recommend checking it using
+         * `asDefaultProps` from the `react-typescript-helpers` package.  If you
+         * don't do that, then the type will still be checked by
+         * JSX.LibraryManagedAttributes every time the component is used,
+         * assuming you use TypeScript 3.0 or newer.
+         */
+        static defaultProps?: any;
```
Comment (Kovensky) [inline types/react/index.d.ts]: Same here

File: types/react/index.d.ts [hunk 7]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+     * Dummy interface that is intersected into the props type of a component on
+     * use to generate an error if the component's `propTypes` static property
+     * is invalid.  In most cases, you can get more information about the
+     * problem with the `propTypes` by trying to assign the component to a
+     * variable of type `React.ComponentType<P>` where `P` is the appropriate
+     * props type.  You can bypass the type checking of `propTypes` by defining
+     * a static property named `bypassPropTypesTypecheck`.
+     */
+    interface Invalid_propTypes<P, T> {
+        [Invalid_propTypes]: undefined;
```
Comment (Kovensky) [inline types/react/index.d.ts]: `never` probably better

File: types/react/index.d.ts [hunk 8]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+     * Dummy interface that is intersected into the props type of a component on
+     * use to generate an error if the component's `defaultProps` static
+     * property is invalid.  In most cases, you can get more information about
+     * the problem with the `defaultProps` by trying to assign the component to
+     * a variable of type `React.ComponentType<P>` where `P` is the appropriate
+     * props type.  You can bypass the type checking of `defaultProps` by
+     * defining a static property named `bypassDefaultPropsTypecheck`.
+     */
+    interface Invalid_defaultProps<P, D> {
+        [Invalid_defaultProps]: undefined;
```
Comment (Kovensky) [inline types/react/index.d.ts]: Same here

File: types/react/index.d.ts [hunk 9]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+    }
+
+    // For a component class, the P passed to JSX.LibraryManagedAttributes is
+    // based on the `props` property and includes `children` regardless of
+    // whether the original props type (the `P` type argument to
+    // React.Component) does.  However, it's common for component classes not
+    // to list `children` in the `propTypes` if the original props type did not
+    // include `children`.  We accommodate that here by making the validator for
+    // `children` optional.
```
Comment (Kovensky) [inline types/react/index.d.ts]: The React types has an open problem (that `{}` in `ReactFragment` which makes `ReactNode` useless) that will have to change that, one way or another. I have an open PR that does it, but maybe there are better ideas on how to do it.

File: types/react/index.d.ts [hunk 10]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+        Partial<ValidationMap<Pick<P, Extract<keyof P, "children">>>>;
+
+    // Explicitly check for excess properties in CheckPropTypes and
+    // CheckDefaultProps because by the time we get to
+    // JSX.LibraryManagedAttributes, we have lost the opportunity to do an
+    // excess properties check on the original object literal.
+
+    type CheckPropTypes<P, T> =
+        // This condition attempts to single out `T = any`, which needs to bypass the rest of the check
+        // because `keyof T` would come out as not extending `keyof P`.
```
Comment (Kovensky) [inline types/react/index.d.ts]: I still haven't found any good way to "detect any" as an input 😢

I guess extending a non-instantiable unique symbol is one way, but it's not actually possible to make one. The `Invalid_propTypes` does _really exist_ to typescript, you'll just get a runtime error if you try to use it.

File: types/react/index.d.ts [hunk 11]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+        T extends typeof Invalid_propTypes ? {} :
+        [keyof T, T] extends [keyof P, ValidationMapWithOptionalChildren<P>] ? {} : Invalid_propTypes<P, T>;
```
Comment (Kovensky) [inline types/react/index.d.ts]: Neat, I hadn't checked you could use tuple types as a sort of `&&` to avoid nesting

File: types/react/index.d.ts [hunk 12]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+
+    type CheckDefaultProps<P, D> =
+        D extends typeof Invalid_defaultProps ? {} :
+        [keyof D, D] extends [keyof P, Partial<P>] ? {} : Invalid_defaultProps<P, D>;
+
+    // Any prop that has a default prop becomes optional, but its type is unchanged
+    // If declared props have indexed properties, ignore default props entirely as keyof gets widened
+    // Wrap in an outer-level conditional type to allow distribution over props that are unions
+    type Defaultize<P, D> = P extends any
```
Comment (Kovensky) [inline types/react/index.d.ts]: This condition is always `true` (even `never` extends `any`)

File: types/react/index.d.ts [hunk 13]
```diff
@@ -2633,30 +2658,76 @@ declare namespace React {
...
+        ? string extends keyof P ? P :
+            & Pick<P, Exclude<keyof P, keyof D>>
+            & Partial<Pick<P, Extract<keyof P, keyof D>>>
+        : never;
+
+    type ReactManagedAttributes<C, P> =
+        (C extends { propTypes: infer T; }
+            ? (C extends { bypassPropTypesTypecheck: {}; } ? {} : CheckPropTypes<P, T>) : {}) &
```
Comment (Kovensky) [inline types/react/index.d.ts]: I'd use `unknown` but... types aren't bumped to 3.0 yet 😞

File: types/react/test/managedAttributes.tsx [hunk 14]
```diff
@@ -182,27 +115,28 @@ interface LeaveMeAloneDtslint { foo: string; }
...
 //     // $ExpectError
 //     <MemoFunctionalComponent />,
-//     // $ExpectError won't work as long as FunctionalComponent doesn't work either
+//     // Requires TypeScript >= 3.2; see comment re FunctionalComponent above
 //     <MemoFunctionalComponent str='abc' />,
 //     // $ExpectError
 //     <MemoAnnotatedDefaultProps />,
 //     <AnnotatedDefaultProps str='abc' />,
-//     // $ExpectError this doesn't work despite JSX.LibraryManagedAttributes returning the correct type
+//     // Requires TypeScript >= 3.2; see comment re FunctionalComponent above
```
Comment (Kovensky) [inline types/react/test/managedAttributes.tsx]: Oh, cool, they actually work :tada:

The only way I had to check when I was writing these was using `JSX.LibraryManagedAttributes` directly and seeing if the types looked right.

File: types/react/test/managedAttributes.tsx [hunk 15]
```diff
@@ -182,27 +115,28 @@ interface LeaveMeAloneDtslint { foo: string; }
...
 //     <LazyMemoAnnotatedDefaultProps />,
-//     // $ExpectError this doesn't work despite JSX.LibraryManagedAttributes returning the correct type
+//     // Requires TypeScript >= 3.2; see comment re FunctionalComponent above
 //     <LazyMemoAnnotatedDefaultProps str='abc' />
 // ];
 
+// // $ExpectType Pick<Props, "bool" | "node" | "num" | "str"> & Partial<Pick<Props, "fnc" | "reqNode">>
 // type AnnotatedDefaultPropsLibraryManagedAttributes = JSX.LibraryManagedAttributes<typeof AnnotatedDefaultProps, Props>;
-// // $ExpectType AnnotatedDefaultPropsLibraryManagedAttributes
+// // $ExpectType Pick<Props, "bool" | "node" | "num" | "str"> & Partial<Pick<Props, "fnc" | "reqNode">>
```
Comment (Kovensky) [inline types/react/test/managedAttributes.tsx]: The alias doesn't work? 😞

**Review by Jessidhia — APPROVED** [review]
Do you have any idea on what we could do about `FunctionComponent`?

**Comment by Kovensky** [comment]
Oops, can't actually approve it until https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30730#discussion_r236493847 is solved

File: types/react/index.d.ts (hunk 4 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: Check your spelling: https://www.npmjs.com/package/react-typescript-helpers

**Comment by mattmccutchen** [comment]
> The problem with having defaultProps in Component's definition is that assigning defaultProps yourself doesn't stop it from being `Partial<P>`. Declaring it does, and this happens to work for classes (only if you directly write static defaultProps = ...), but not at all for FunctionComponent.

Are you saying that `Component.defaultProps` shouldn't be declared because it gives users a false sense that assigning to it will work?

File: types/react/index.d.ts (hunk 4 above)
Comment (Kovensky) [reply types/react/index.d.ts]: Oops 🙈

Comment (Kovensky) [reply types/react/index.d.ts]: The example code in the README doesn't look valid 🤔

Comment (Kovensky) [reply types/react/index.d.ts]: The actual code doesn't look valid either, or at least with this PR, your constraint in the returned functions only work by accident because of the types in `FunctionComponent` (or worse, widen to `any`).

File: types/react/index.d.ts (hunk 10 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: IMO, if a user breaks this logic by passing `Invalid_propTypes`, they get to keep both pieces.  I could use [this approach](https://github.com/Microsoft/TypeScript/issues/27024#issuecomment-421529650) to do a type identity check, but I didn't think the benefit justified the extra code.

File: types/react/index.d.ts (hunk 12 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: The comment says, "Wrap in an outer-level conditional type to allow distribution over props that are unions".  I didn't change this part.

**Comment by Kovensky** [comment]
`FunctionComponent` already has a `Partial<P>` declaration of `defaultProps` which is impossible to override without `Omit` + `&`ing your own `defaultProps` type.

File: types/react/test/managedAttributes.tsx (hunk 15 above)
Comment (mattmccutchen) [reply types/react/test/managedAttributes.tsx]: dtslint does a [string comparison](https://github.com/Microsoft/dtslint/blob/73a196741d5b6ca9af7f6ef68ef4ee3e801ac4b5/src/rules/expectRule.ts#L302) of the expected type to the default string representation of the actual type, so I don't think this could ever have worked.  Feel free to file an enhancement request against dtslint.  In the meantime, if we really wanted to assert the equality of two types without writing out one of them in full, there are probably other ways, but in this case it didn't seem too bad.

File: types/react/index.d.ts (hunk 9 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: Are you suggesting a change to this pull request?

File: types/react/index.d.ts (hunk 4 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: > The example code in the README doesn't look valid (`ReferenceError`) :thinking:

I knew I was going to make some mistake.  I fixed the occurrences of `MyComponent` that should have been `MyComponentClass` (in master, not yet published to npm).  Did you find anything else wrong?

Comment (mattmccutchen) [reply types/react/index.d.ts]: > The actual code doesn't look valid either, or at least with this PR, your constraint in the returned functions only work by accident because of the types in `FunctionComponent` (or worse, widen to `any`).

Sorry, I don't understand what you mean.  When I modify `package.json` to point to `@types/react` with this PR, the test cases in `test.tsx` still compile successfully, and if I deliberately put the wrong type in `defaultProps`, I get the expected compile error.

Comment (Kovensky) [reply types/react/index.d.ts]:
```ts
export function asDefaultProps<P>(component: LooseComponentType<P>) {
    return <DP extends React.ComponentType<P>["defaultProps"]>
        (defaultProps: DP) => defaultProps;
}
```

`ComponentType<P>["defaultProps"]` is going to be `ComponentClass<P>["defaultProps"] | FunctionComponent<P>["defaultProps"]`, which will expand to `object | Partial<P>`. This will still work right now because we're not dealing with `FunctionComponent`'s problem, but it's more of a case of working by accident than working as intended.

Probably needs `<DP extends Partial<P>>`.

A similar problem is present with the `asPropTypes` function.

**Comment by mattmccutchen** [comment]
> `FunctionComponent` already has a `Partial<P>` declaration of `defaultProps` which is impossible to override without `Omit` + `&`ing your own `defaultProps` type. Just assigning to it will still keep its type `Partial<P>` which is useless to `JSX.LibraryManagedAttributes`.

Right, annotating a function component as `FunctionComponent` won't work, but just defining a `function` and assigning to the `defaultProps` [like this](https://github.com/mattmccutchen/react-typescript-helpers/blob/87fd06d3dee332709c7fe3bf7e90d41d3715e47f/test.tsx#L5-L13) should work.  I realize the latter approach doesn't check that the function is a valid component (correct return type, etc.).  One way to fix that would be to have a helper function in `react-typescript-helpers` that checks that the component is assignable to `FunctionComponent` but retains its original type.  But that seems unrelated to the current pull request.

File: types/react/index.d.ts (hunk 4 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: > `ComponentType<P>["defaultProps"]` is going to be `ComponentClass<P>["defaultProps"] | FunctionComponent<P>["defaultProps"]`, which will expand to `object | Partial<P>`.

No, this PR does not change `ComponentClass<P>["defaultProps"]`; it is still `Partial<P>`.  The `object` is only in `Component.defaultProps`.  Do you foresee changing the type of `ComponentClass.defaultProps` or `FunctionComponent.defaultProps`?

Comment (Kovensky) [reply types/react/index.d.ts]: Ah, I'm thinking of https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30791 and what it would take to fix it.

It's still probably better to be future-proof, either by exporting `type` aliases from `react` or by directly using `Partial` / `ValidationMap` in the `extends` clauses.

File: types/react/index.d.ts (hunk 5 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: `object` broke the tests because a component class that did not redeclare `propTypes` or `defaultProps` was not assignable to `ComponentClass<P>`.  I'm changing this back to `any`.

File: types/react/index.d.ts (hunk 4 above)
Comment (mattmccutchen) [reply types/react/index.d.ts]: Done in master of react-typescript-helpers.  (I'll wait to publish to npm until the review of this pull request is done.)

**Comment by eloleon** [comment]
Guys, this changes breaks app when code is written is this fashion:

https://github.com/GriddleGriddle/Griddle/issues/647#issuecomment-307581065

**Comment by JounQin** [comment]
I got a lot of errors like `TS2741: Property '[Invalid_propTypes]' is missing in type '{}' but required in type 'Invalid_propTypes<Readonly<{ children?: ReactNode; }> & Readonly<ITextProps>, { name: Requireable<string>; }>'.` after upgrade.

Simplest reproduction:

```tsx
import PropTypes from 'prop-types'
import React from 'react'

export interface ITextProps {
  name?: string
}

export class Text extends React.PureComponent<ITextProps> {
  static propTypes = {
    name: PropTypes.string,
  }
}

<Text />
```

**Comment by Kovensky** [comment]
I believe it is complaining about a missing `children` validator. [Can we finally kill `children`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30775)?

It also looks like this broke the one part of the tests we can't run in DefinitelyTypes until we bump everything to TS 3.0, the `LibraryManagedAttributes` tests. I haven't checked but, based on the error message in #30942, it looks like if a component that `extends Component` doesn't define their own `defaultProps`, `LibraryManagedAttributes` will just eradicate everything from their props.

**Comment by johnnyreilly** [comment]
> I believe it is complaining about a missing children validator. Can we finally kill children?

Get me a passing build and I will merge :wink:

**Comment by Kovensky** [comment]
@johnnyreilly I actually don't know how to do that because on my first push tests pass _but_ they time out on jenkins because so many packages are affected. There is no way for me to make the affected set smaller, it's possible the new types just make the compiler slower.

**Comment by mattmccutchen** [comment]
Re @JounQin's example: The new behavior is correct, though perhaps the breaking change could have been announced better.  `PropTypes.string` accepts the type `string | null | undefined`, so the type of the `name` property of `ITextProps` needs to be `string | null | undefined`.  The `undefined` is implicit because the property is optional, but `null` has to be added to the type manually.  When I do that, the error goes away.  With or without this pull request, attempting to assign `Text` to a variable of type `React.ComponentType<ITextProps>` gives an error about the `propTypes` for the same reason.

**Comment by mattmccutchen** [comment]
@eloleon Can you please provide a complete example code snippet that reproduces the problem and state what error you are getting?

**Comment by eloleon** [comment]
@mattmccutchen 

This is the error

`(22,18): Class static side 'typeof PreserveReactReduxContext' incorrectly extends base class static side 'typeof Component'.
Types of property 'contextTypes' are incompatible.
Type '{ [x: string]: () => void; }' is not assignable to type 'ValidationMap<any>'.
Index signatures are incompatible.
Type '() => void' is not assignable to type 'Validator<any>'.
Type 'void' is not assignable to type 'Error'.`

Code is similar to the one from my original link:
`
xport default function aliasReactReduxContext({ contextPrefix = 'aliased-', storeKey = 'store', subKey } = {})
{
  return (WrappedComponent) => {
    const subscriptionKey = subKey || `${storeKey}Subscription`;
    return class AliasReactReduxContext extends Component {
      static contextTypes = {
        [storeKey]: PropTypes.object,
        [subscriptionKey]: PropTypes.object
      };
      static childContextTypes = {
        [`${contextPrefix}${storeKey}`]: PropTypes.object,
        [`${contextPrefix}${subscriptionKey}`]: PropTypes.object
      };
      getChildContext() {
        return {
          [`${contextPrefix}${storeKey}`]: this.context[storeKey],
          [`${contextPrefix}${subscriptionKey}`]: this.context[subscriptionKey]
        };
      }

      render() {
        return (
          <WrappedComponent {...this.props} />
        );
      }
    };
  };
}`

**Comment by eloleon** [comment]
> @eloleon Please double check your code snippet... The error message mentions `PreserveReactReduxContext` but I don't see it anywhere in the code snippet.

I've renamed it to aliasReactReduxContext. That's all

**Comment by mattmccutchen** [comment]
@eloleon I still can't reproduce your error.  The only errors I get are:
- On the declaration of `subKey`: "Initializer provides no value for this binding element and the binding element has no default value."
- An implicit-any error on the declaration of `WrappedComponent`.

If I append a use of the higher-order component:
```ts
class MyComponent extends React.Component<{}, {}> {}
const test = aliasReactReduxContext()(MyComponent);
```
I don't get any additional errors.

**Comment by JounQin** [comment]
@mattmccutchen Then what's your suggestion to fix the problem? It seems not possible to mark all props to be nullable which should not be `null` actually. Or `@types/prop-types` package should be updated because of there changes.

**Comment by mattmccutchen** [comment]
@JounQin If you don't want `null` to be a valid value of the property, you could write your own validator that accepts `string | undefined`, for example:

```ts
const stringOrUndefinedValidator: PropTypes.Validator<string | undefined> = (props, propName, componentName) => {
  const propValue = (props as any)[propName];
  if (propValue === undefined || typeof propValue === "string") return null;
  return new Error(`${propName} must be string or undefined, got ${propValue}`);
};

export class Text extends React.PureComponent<ITextProps> {
  static propTypes = {
    name: stringOrUndefinedValidator,
  };
}
```

Or if you want to use the existing validator and ignore the fact that it is inconsistent with what your component code actually handles, you could cast `PropTypes.string as PropTypes.Validator<string | undefined>`.

**Comment by JounQin** [comment]
There are a lot of third-party components from npm which cannot be modified directly, and I don't think everyone wants to make such painful experience.

**Comment by Pajn** [comment]
Thanks to this I have the issue
```
TS2741: Property '[Invalid_propTypes]' is missing in type '{ children: Element; client: ApolloClient<{}>; }' but required in type 'Invalid_propTypes<Readonly<{ children?: ReactNode; }> & Readonly<ApolloProviderProps<{}>>, { client: Validator<object>; children: Validator<string | number | boolean | {} | ReactElementLike | ReactNodeArray>; }>'.
```
that I can't get rid of nor understand what it's complaining about.

I have never used propTypes in my whole life and I do not expect Typescript to error about some deprecated react property that I doesn't use

**Comment by Pajn** [comment]
@mattmccutchen 
>Re @JounQin's example: The new behavior is correct, though perhaps the breaking change could have been announced better. PropTypes.string accepts the type string | null | undefined, so the type of the name property of ITextProps needs to be string | null | undefined. The undefined is implicit because the property is optional, but null has to be added to the type manually. When I do that, the error goes away. With or without this pull request, attempting to assign Text to a variable of type React.ComponentType<ITextProps> gives an error about the propTypes for the same reason.

That is completely wrong, and insane. Every single user of this package uses Typescript to manage types, that is the sole reason this package exist.

**Comment by mattmccutchen** [comment]
I agree that getting errors in third-party code is a big hassle.  @Kovensky @johnnyreilly What do you think we should do?  If we revert the change (or at least the `propTypes` part), is there a practical way to get the most popular affected packages fixed before trying again?  Or should we just abandon the `propTypes` part of the change as not providing value that justifies the effort to migrate?

**Comment by Pajn** [comment]
Because of the above problems, because you are creating a massive problem for every single React+TypeScript user that maybe (and that's debatable) helps a very, very small percentage of them.
It's a huge pain even for users that care about `propTypes` as it (as you said yourself) does not provide a way to specify non null and requires implementing your own validators. It's even a huge slap in the face to users as they have to download even more code that takes even longer to parse, just to satisfy typings that very few people care about.

**Comment by johnnyreilly** [comment]
If someone would like to submit a PR to revert this change I'd be happy to merge. I think this change is probably making things harder to work with React rather than easier. Good motivation; this just hasn't worked out as well as hoped. 

@mattmccutchen thanks anyway. If there's a way to reattempt without such an abrasive outcome do feel free.

I'm a little disappointed that the tests we have in place aren't catching the problems that people are listing. I think everyone that has completed could contribute well by adding tests to DT that cover their own use cases.

I would rather tackle these problems in PRs rather than post release.

**Comment by weswigham** [comment]
For the record: From what we've seen, most people use `propTypes` and manually specified interfaces for props mutually exclusively. If you use both at the same time, good for you for checking types at both runtime and designtime, but you're likely in the minority. Because of this, it's usually best to think of `propTypes` as a _source_ of type information, rather than a thing to be checked.

**Comment by weswigham** [comment]
> That is completely wrong, and insane. Every single user of this package uses Typescript to manage types, that is the sole reason this package exist.

Probably also worth noting that every javascript user in vscode depends on these types to get good intellisense for react even if they're not writing any types at all - so any change that requires external helpers or explicit annotations probably needs to be looked at with heavy skepticism for the benefit of these users.

**Comment by Pajn** [comment]
I don't think this kinds of problems ever can be caught until it's too late, the DefinitelyTyped concept is fundamentally flawed.

Some examples of problems:
- Tests are always run against the latest version of every other package, but the published packages does not have version ranges to enforce that that happen in the reality. And with both Yarn and NPM using lock files now, that never happen in reality. Because of that, every change in more than one package will ALWAYS cause problems for all users.
- Unit tests will by definition not catch most of this problems. DefinitelyTyped would need to test changes by upgrading `@type/` packages in actual projects on NPM, similar to what Rust does with changes in the language or std lib.
- If your change requires changes in tests of other packages, no problem, just change them. Sure the CI passes but the only guarantee (and a very bad one at that) we ever had that this isn't super breaking is completely gone.
- Allowing bad, partial or in progress type definition for packages gives a very high probability of new changes requiring breaking changes or to be stuck with poor types forever
- Very few PRs are reviewed by someone actually experienced with the package and dependant packages, just making all the other problems even greater.

I had high hopes that TS would deprecate DefinitelyTyped in v3 for eventually dropped support for `@types/` in v4 and move type definitions to where they actually belong, in the package that they define. That would massively improve the quality of all types. Just look at packages that provide their own types today and how often they are problematic compared to types from DefinitelyTyped. Unfortunately, that did not happen.

**Comment by eloleon** [comment]
> If someone would like to submit a PR to revert this change I'd be happy to merge. I think this change is probably making things harder to work with React rather than easier. Good motivation; this just hasn't worked out as well as hoped.
> 
> @mattmccutchen thanks anyway. If there's a way to reattempt without such an abrasive outcome do feel free.
> 
> I'm a little disappointed that the tests we have in place aren't catching the problems that people are listing. I think everyone that has complained could contribute well by adding tests to DT that cover their own use cases.
> 
> I would rather tackle these problems in PRs. Having to amend something post release is not a good spend of time.

Please revert this change as per sugestion and write strong tests before commiting again. It is causing chaos

**Comment by pelotom** [comment]
@Pajn 

>I had high hopes that TS would deprecate DefinitelyTyped in v3 for eventually dropped support for @types/ in v4 and move type definitions to where they actually belong, in the package that they define. 

One of the main difficulties of this is that maintainers of JS packages usually don't want to modify their release cadence to accommodate a bunch of changes that only improve type definitions without modifying the runtime semantics of their library at all. A great example of this is Redux, which has long intervals between releases. The types for Redux are built-in, but it takes forever to make improvements to them (once a year maybe!). Since the types are always playing catchup with the implementation, by definition they need to change much more frequently. I agree with your list of problems with DT, but moving types into target libraries, without maintainers who are eager participants, is not necessarily a great improvement.

**Comment by Pajn** [comment]
But then users can decide to use another library without those problems. Typescript have a 40% market share now, it's more than capable of providing alternative libraries written in Typescript with perfect type definitions.

I can never recommend TypeScript to people not already using it because the amount of problem they will face are huge and if we do nothing to fix that, that will continue.

**Comment by pelotom** [comment]
>But then users can decide to use another library without those problems. Typescript have a 40% market share now, it's more than capable of providing alternative libraries written in Typescript with perfect type definitions.

And yet here you are, using React, not some alternative library written in TypeScript with perfect type definitions. It's important to remember that part of the reason _why_ TS has such a large market share is that it offers a reasonably easy way to use pure JS libraries with typings contributed by the community. There's no doubt a better solution possible, but at the moment DT is the best option out there for providing types for large JS projects with slow release cycles.

**Comment by Pajn** [comment]
>And yet here you are, using React, not some alternative library written in TypeScript with perfect type definitions

I'm pretty sure that if Typescript did remove support for @types, React would host their own. If I simply could ignore DefinitelyTyped, there wouldn't be a problem. However as DefinitelyTyped sold as a reasonable solution people rely on it. There are even packages like styled-components or the leveldown packages that once had selfhosted types but remove them in favour of DefinitelyTyped and in both cases the quality have sunken to the point where using those packages is either not possible or is more difficult than migrating to other packages with included types.

**Comment by johnnyreilly** [comment]
I don't think much more of use is being added in this conversation. A PR to improve the situation would be gratefully received.

For the record I'd like to say thank you to @mattmccutchen for submitting a PR to try and improve the React type definitions. This PR clearly had some issues but that's okay. We appreciate people pitching in and trying to contribute.

Please do not be discouraged - we welcome future PRs ♥️🌻

**Comment by johnnyreilly** [comment]
Now reverted: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30964
