### PR TITLE
fix(qr-image): support for `customize` PNG function

### LINKED ISSUE #45898: `customize` method missing in options of qr-image
missing method `customize` for PNG output https://github.com/alexeyten/qr-image#options

- [x] I tried using the `@types/qr-image` package and had problems.
- [x] I tried using the latest stable version of tsc `3.9.5`
- Authors: @taoqf

### PR DESCRIPTION
**Pull request by peterblazejewicz**
- `customize` option support added
https://github.com/alexeyten/qr-image#options
- `Bitmap` value type added

/cc @tiholic

Thanks!

Fixes #45898

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### CODE REVIEW

**Comment by tiholic** [comment]
@peterblazejewicz thanks for the super fast PR 😃😃

File: types/qr-image/index.d.ts [hunk 1]
```diff
@@ -13,12 +13,34 @@ export type ec_level = 'L' | 'M' | 'Q' | 'H';
 /** @default 'png' */
 export type image_type = 'png' | 'svg' | 'pdf' | 'eps';
 
+/**
+ * bitmap.size — width (and height) of resulting image in pixels
```
Comment (sandersn) [inline types/qr-image/index.d.ts:17]: Extremely minor quibble, but this would probably be more accessible if split up and put on `size` and `data` individually.

**Review by sandersn — APPROVED** [review]

File: types/qr-image/index.d.ts (hunk 1 above)
Comment (peterblazejewicz) [reply types/qr-image/index.d.ts]: not worries, this was taken 'as is' from author's sample code. So now I've just refined into proper JSDoc comments as requested in the update. Thx!

**Comment by peterblazejewicz** [comment]
Ready to merge :kiss:
