### PR TITLE
[chai] avoid polluting global `Object` types

### LINKED ISSUE #43744: Chai definitions break types with `should` property
Chai exports `interface Object { should: Chai.Assertion }` which [causes issues](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/9120) with TS, causing it to infer that any `{}` has an implicit `should` property when my type contains `should`, but then completely fails to reconcile Chai's `should` with my own type declaration.

When I update Cypress — which has a dependency on Chai — `tsc` throws tens of errors.

Contrived example:

```ts
interface QueryContainer {
  bool?: BoolQuery
  …
}

interface BoolQuery {
  must?: QueryContainer[]
  should?: QueryContainer[]
  must_not?: QueryContainer[]
  filter?: QueryContainer[]
}

const query: QueryContainer = { bool: {} }
```

Was fine before, but with `cypress@4.3.0`:

```
whatever.ts:109:5 - error TS2322: Type '{ must: ({ term: { 'metadata.key': { value: string; }; }; } | { term: { 'metadata.value.keyword': { value: string; }; }; })[]; }' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

109     bool: {
        ~~~~

  whatever_types.ts:6467:3
    6467   bool?: BoolQuery
           ~~~~
    The expected type comes from property 'bool' which is declared here on type 'QueryContainer'

```

We can refine it a bit and get a better error:

```ts
const boolQ: BoolQuery = {}
const query: QueryContainer = { bool: boolQ }
```

Now we get:

```
whatever.ts:81:9 - error TS2322: Type '{}' is not assignable to type 'BoolQuery'.
  Types of property 'should' are incompatible.
    Type 'Assertion' is not assignable to type 'QueryContainer[]'.

81   const boolQ: BoolQuery = {}
           ~~~~~
```

If my `BoolQuery` type doesn't have its own `should` property that's incompatible with `Chai.Assertion`, then there's no problem, it's only when I have my own `should` property that the clash happens

### PR DESCRIPTION
**Pull request by alecgibson**
Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/43744 Also related: https://github.com/vitest-dev/vitest/issues/2118

At the moment, the `chai` types pollute the global `Object` types. However, implementation-wise the global prototype pollution is [opt-in][1], which means that the global `Object` should not be polluted by default.

This is bad both for consumers who don't want this pollution, since it can cause type clashes; and also for consumers who *do* want this pollution, since they may rely on the pollution being present (since the types say the method is available), without correctly opting in.

This change proposes a change to the types that will make the type definitions more accurately reflect the implementation by splitting this pollution out into a separate type that matches the ES2015 syntax:

```ts
import 'chai/register-should';
```

Any consumers who are already opting in to this pollution should see no change with this update.

Any other consumers will not have pollution by default. This is better for consumers who do not want this behaviour, but a **breaking** change for any consumers who are opting in using the alternative syntax:

```ts
import {should} from 'chai';
should();
```

In this case, they will need to switch to the ES2015 syntax.

[1]: https://www.chaijs.com/guide/styles/#using-should-in-es2015

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

### CODE REVIEW

File: types/chai/chai-register-should-tests.ts [hunk 1]
```diff
@@ -0,0 +1,2610 @@
+/// <reference types="node" />
+import { assert, config, expect, Should, use, util } from "chai";
+import 'chai/register-should';
```
Comment (alecgibson) [inline types/chai/chai-register-should-tests.ts:3]: I'm not clear on how DefinitelyTyped tooling works: I would have expected this `import` to pollute the types for the other tests and cause them to fail, but they don't. Is that expected?

File: types/karma-sinon-chai/test/karma-sinon-chai-global-tests.ts [hunk 2]
```diff
@@ -1,5 +1,7 @@
 /// <reference types="chai" />
 /// <reference types="sinon-chai" />
+import "chai/register-should";
+import * as sinon from 'sinon';
```
Comment (alecgibson) [inline types/karma-sinon-chai/test/karma-sinon-chai-global-tests.ts:4]: I had to add this to greenify the build, but I don't think it really belongs to this change (or is even correct...? If I understand correctly, `sinon` types should be available ambiently, which is what this test is checking?)

**Comment by DangerBotOSS** [comment]
## Formatting

The following files are not formatted:
1. types/karma-sinon-chai/test/karma-sinon-chai-global-tests.ts
1. types/chai/chai-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a3709cd731b7e38a37da542dcc3747ccb1e9c5ca
</p>

File: types/chai-as-promised/chai-as-promised-tests.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import * as chai from "chai";
+import "chai/register-should.js";
```
Comment (jakebailey) [inline types/chai-as-promised/chai-as-promised-tests.ts:2]: This makes me wonder why `chai` hasn't used export maps to deal with this. chai v5 is ESM only, so, it's somewhat surprising. But, if this is how it is, so be it.

File: types/karma-sinon-chai/test/karma-sinon-chai-global-tests.ts (hunk 2 above)
Comment (jakebailey) [reply types/karma-sinon-chai/test/karma-sinon-chai-global-tests.ts]: By adding an import here, you're turning the file into a module when it was previously a global script. You should use a `reference` directive to `chai/register-should` here and in other places that are not modules. (and that would have to be the recommendation for other global users).

**Comment by sandersn** [comment]
This looks like it matches the technical suggestions by @jakebailey. However, I'd like signoff from one of the other chai maintainers to sign off on the semantics. Although it's more correct, it seems like it will be a breaking *type* change, forcing people to explicitly write `import "chai/register-should"` where they didn't before. However, presumably their tests wouldn't actually run without that line, so people with working tests will already have written that.

@clementprevot, @jt000, @Kuniwak, @leonard-thieu, @lazerwalker, @mattbishop, @worr, @dimitardanailov, @ulrichheiniger, @ChayimFriedman2, @kuzn-ilya, @harm-less, @jounisuo, @nmalaguti, @delta62, @AGBrown, @Bartvds, @olivr70, @mwistrand, @shaunluttin, @micksatana, @ErikSchierboom, @bparan, @CXuesong, @joeykilpatrick, @dex4er, @SevenOutman.)

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by alecgibson** [comment]
Ready to merge

**Comment by jimmy-zhening-luo** [comment]
Why was this breaking change shipped as a patch fix? Did any chai maintainer end up reviewing this? I followed all the instructions in the Chai documentation to "opt-in" to this "pollution". My tests run. They still run. However, now TypeScript transpiler refuses to transpile my code because of this patch change. I'm also perplexed reading this conversation and the rationale presented. I'm not a developer, but I do have a brain and the requirement of a line stating `import "chai/register-should";` that magically solves all my problems seems awfully "magic word"-y, when I'm already ESMing things correctly with `import { should } from "chai"` and `should();`, which I copy-pasted from the `chai` docs because I can ctrl-C ctrl-V.
