### PR TITLE
[@types/browser-sync] Fix type of bs: `object` -> `BrowserSyncInstance`

### LINKED ISSUE #35426: [@types/browser-sync] Property 'getOption' does not exist on type 'object'.
```js
  browserSync(
    {
      port: 8080,
      server: {
        baseDir: 'public'
      }
    },
    (err, bs) => {
      const LOCAL = bs.getOption('urls').get('local'); // Error
    }
  );
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a69026a85cb5ad148cbc9ba15b798d34bc99f425/types/browser-sync/index.d.ts#L457
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a69026a85cb5ad148cbc9ba15b798d34bc99f425/types/browser-sync/index.d.ts#L491

`bs` arg on callback needs to have type `BrowserSyncInstance` as:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a69026a85cb5ad148cbc9ba15b798d34bc99f425/types/browser-sync/index.d.ts#L541
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a69026a85cb5ad148cbc9ba15b798d34bc99f425/types/browser-sync/index.d.ts#L552

### PR DESCRIPTION
**Pull request by yuma84**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://browsersync.io/docs/api#api-init
- [x] Increase the version number in the header if appropriate.
- [ ] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

---

This PR closes #35426

### CODE REVIEW

**Review by aznnomness — APPROVED** [review]

File: types/browser-sync/index.d.ts [hunk 1]
```diff
@@ -1,9 +1,10 @@
-// Type definitions for browser-sync
+// Type definitions for browser-sync 2.26.5
```
Comment (sandersn) [inline types/browser-sync/index.d.ts]: Thanks for adding a version. Can you please remove `"dt-header": false` from tslint.json so that the header is actually checked? Perhaps `"npm-naming": false` too.

**Review by sandersn — CHANGES_REQUESTED** [review]
Version can only include major.minor

File: types/browser-sync/index.d.ts (hunk 1 above)
Comment (yuma84) [reply types/browser-sync/index.d.ts]: @sandersn Thank you for your advice. I fixed version to MAJOR.MINOR.
If I remove `"dt-header": false` and run test, `ERROR: 3:26  dt-header  Error parsing header. Expected: /\<https\:\/\/github\.com\/([a-zA-Z\d\-]+)\>/.` because some authors wrote personal web site.
[dt-header](https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md#dt-header) says:
> Bad:
> ```// Definitions by: My Name <http://geocities.com/myname>```
> Good:
> ```// Definitions by: My Name <https://github.com/myname>```
> Prefer a GitHub username, not a personal web site.

Comment (sandersn) [reply types/browser-sync/index.d.ts]: Hmm. I guess leave dt-header: false then? I don't want to erase an author. 
Thanks for making the fixes.

**Review by sandersn — APPROVED** [review]
