### PR TITLE
[@types/slate-react] Specify event types

### LINKED ISSUE #35063: [@types/slate-react] EventHook wrong event type
Using either plugins or defining eventhandlers on a custom component requires type assertion of event.
It seems like all the event handlers use the `EventHook` type, where the event argument simply is an `Event`. It seems to me like they really should be specific to the event, ie. the event in `onClick` should be `KeyboardEvent` and not `Event`. This way you dont have to use type assertion every time. They should also use reacts event objects, as specified in the docs.
https://docs.slatejs.org/slate-react/plugins#hooks

- [x] I tried using the `@types/xxxx` package and had problems.
- [x] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [x] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @andykent @majelbstoat @JanLoebel @patricksachs @YangusKhan @isubasti @sgreav @Kornil @jackall3n @benjiro

If you do not mention the authors the issue will be ignored.

### PR DESCRIPTION
**Pull request by guaneec**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Fixes #35063 [](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/35063), based on [react type defs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts)

### CODE REVIEW

File: types/slate-react/index.d.ts [hunk 1]
```diff
@@ -99,7 +99,8 @@ export interface RenderInlineProps extends RenderNodeProps {
     node: Inline;
 }
 
-export type EventHook = (event: Event, editor: CoreEditor, next: () => any) => any;
+export type EventHookT<T> = (event: T, editor: CoreEditor, next: () => any) => any;
+export type EventHook = EventHookT<Event>;
```
Comment (kaydelaney) [inline types/slate-react/index.d.ts]: Could avoid defining two types by just having
```ts
export type EventHook<T = Event> = (event: T, editor: CoreEditor, next: () => any) => any;
```

Comment (guaneec) [reply types/slate-react/index.d.ts]: Oops. I'm not familiar with the tooling and was trying to make it work with TS 1.x.
Updated.

**Review by benjiro — APPROVED** [review]
LGTM, Thanks
