### PR TITLE
fix: update body type, fix #62921

### LINKED ISSUE #62921: [@types/koa-bodyparser]：错误 TS2717 #62920
img_v2_a933c6b0-2a3c-4eb3-988b-00fe436c0bcg

I found this problem when I executed tsc

@petarzarkov  😭

### PR DESCRIPTION
**Pull request by declanchiu**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

### CODE REVIEW

**Review by 1pete — APPROVED** [review]

**Comment by amaschas** [comment]
Can we get some context for this change?

**Comment by 1pete** [comment]
> Can we get some context for this change?

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62237

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62920

**Review by jakebailey — APPROVED** [review]

**Comment by PlayGuitar-CoderQ** [comment]
Ready to merge&nbsp;


coder_zj
***@***.***

前端开发


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TypeScript ***@***.***&gt;; 
发送时间: 2022年10月28日(星期五) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DefinitelyTyped/DefinitelyTyped] fix: update body type, fix #62921 (PR #62922)





 
@PlayGuitar-CoderQ: Everything looks good here. I am ready to merge this PR (at 1086658) on your behalf whenever you think it's ready.
 
If you'd like that to happen, please post a comment saying:
  
Ready to merge
  
and I'll merge this PR almost instantly. Thanks for helping out! ❤️
 
***@***.***, @hirochachacha, @amaschas, @1pete: you can do this too.)

File: types/koa-bodyparser/index.d.ts [hunk 1]
```diff
@@ -21,8 +21,8 @@ import * as Koa from "koa";
 
 declare module "koa" {
     interface Request {
-        // any declaration breaks types intellisense and type safety, keep it at least Record<string, unknown>
-        body?: Record<string, unknown>;
+        // Fix #62921
+        body?: any;
```
Comment (jaydenseric) [inline types/koa-bodyparser/index.d.ts:25]: I think this should have been like this instead, using `unknown` in place of `any`:

```
body?: unknown;
```

Because, `any` doesn't allow us to use intersection to provide more specific types for `body` when needed:

Screenshot 2022-11-04 at 4 11 45 pm

Compared to:

Screenshot 2022-11-04 at 4 12 08 pm

Comment (PlayGuitar-CoderQ) [reply types/koa-bodyparser/index.d.ts:25]: > I think this should have been like this instead, using `unknown` in place of `any`:
> 
> ```
> body?: unknown;
> ```
> 
> Because, `any` doesn't allow us to use intersection to provide more specific types for `body` when needed:
> 
> Screenshot 2022-11-04 at 4 11 45 pm
> 
> Compared to:
> 
> Screenshot 2022-11-04 at 4 12 08 pm

Oh man I think you're right. 😱

Comment (jaydenseric) [reply types/koa-bodyparser/index.d.ts:25]: Here is a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63074 .

Comment (amaschas) [reply types/koa-bodyparser/index.d.ts:25]: Good work figuring this out. This problem with the typing of the body parameter has been ongoing for years at this point, so hopefully this will resolve it more or less permanently?
