### PR TITLE
[atom] setTextInBufferRange fix and missing definitions

### LINKED ISSUE #22212: [@types/atom] TextEditor.setTextInBufferRange returns Range, not void
If you know how to fix the issue, make a pull request instead.

- [X] I tried using the `@types/xxxx` package and had problems.
- [X] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [X] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @GlenCFL @smhxx

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8295e5c2330037f6fa4c1676530ae48d9cb2b738/types/atom/index.d.ts#L1458-L1459

likely should be
```ts
  setTextInBufferRange(range: RangeCompatible, text: string, options?:
      { normalizeLineEndings?: boolean, undo?: "skip" }): Range
```

As [per documentation](https://atom.io/docs/api/v1.23.1/TextEditor#instance-setTextInBufferRange),
> Returns the Range of the newly-inserted text.

P.S. I will make a pull request if nobody beats me to it, just don't have time for that atm

### PR DESCRIPTION
**Pull request by lierdakil**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://atom.io/docs/api/v1.22.1/TextEditor#instance-setTextInBufferRange and see OP in #22211 for context on added definitions.
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

This fixes #22212 
This also adds simpler missing definitions mentioned in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22211 -- all of those except `TextEditorElement` and `TextEditorComponent`.

One change that might be somewhat controversial, is `Grammar.name` has been marked as `readonly`. But it should pretty much follow the same rules as `scopeName`, and it was suggested that latter *should* be marked as such, so I would argue that former also deserves such treatment (technically, you could change either, but that would more often than not be on accident, and will lead to shenanigans)

### CODE REVIEW

**Review by GlenCFL — APPROVED** [review]
Looks good to me. I'll look into the other missing definitions soon if another PR doesn't follow.

File: types/atom/index.d.ts [hunk 1]
```diff
@@ -3610,7 +3619,10 @@ export class GitRepository {
 /** Grammar that tokenizes lines of text. */
 export interface Grammar {
     /** The name of the Grammar. */
-    name: string;
+    readonly name: string;
```
Comment (smhxx) [inline types/atom/index.d.ts]: I think this change makes sense, as I can't really think of any reason why the internal properties of a Grammar would ever need to be modified after instantiation... it seems to me that this would likely only break things, so making it `readonly` seems appropriate. This can always be modified if it turns out there is a legitimate reason to make these properties writable.

**Review by smhxx — APPROVED** [review]
LGTM. 👍
